### ISSUE TITLE
installation problems 

### ISSUE THREAD

**Issue by Cry0k** [snort3/snort3#100]
hi team,

while going thru the documentation of the snot3 installing on ubuntu 18 i ran into a problem when running the make command for the snort
[  0%] Documents: building commands.txt with 
/home/ubuntu/snort_src/snort3/build/src/snort: error while loading shared libraries: libdaq.so.3: cannot open shared object file: No such file or directory
doc/CMakeFiles/all_built_sources.dir/build.make:79: recipe for target 'doc/commands.txt' failed
make[2]: *** [doc/commands.txt] Error 127
make[2]: *** Deleting file 'doc/commands.txt'
CMakeFiles/Makefile2:6083: recipe for target 'doc/CMakeFiles/all_built_sources.dir/all' failed
make[1]: *** [doc/CMakeFiles/all_built_sources.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

any ideas on how to fix it?

**Comment by kdrypr** [comment]
@FaikCoskun can help you

**Comment by FaikCoskun** [comment]
Hi , I think you did not install the latest vesion of DAQ 

You need to install lbdaq3 the latest version of DAQ and then update libraries with ldconfig command

I hope it helps.

**Comment by Cry0k** [comment]
for some reason my ubuntu installetion can not find the packege libdaq3 can you tell me from were i can download it?

**Comment by FaikCoskun** [comment]
You can download it from github via [https://github.com/snort3/libdaq](url)

**Comment by Xiche** [comment]
Thank you for pointing them in the right direction, @FaikCoskun
