### ISSUE TITLE
make snort3 fails. cannot find libdaq.so.3. It is present at the standard location. See screenshot.

### ISSUE THREAD

**Issue by leenaarora** [snort3/snort3#102]
![image](https://user-images.githubusercontent.com/56274289/66340081-77329e80-e912-11e9-90f9-8ce49ed60eb0.png)

**Comment by Xiche** [comment]
This is a problem with your system - it looks like you need to run ldconfig.  ldconfig -v will show you all of the locations it has searched and all of the items it has added to its cache to be available for loading/linking by default at runtime.

**Comment by leenaarora** [comment]
Thanks. That worked.
