### ISSUE TITLE
Is there any database solution

### ISSUE THREAD

**Issue by Gunkkk** [snort3/snort3#103]
Since the barnyard2 do not perfectly support the unified format of snort3 any more, is there any solution for the demanding that saves alert logs into database.
Thanks!

**Comment by snortadmin** [comment]
Have you considered elasticsearch?

https://blog.snort.org/2017/11/snort-30-with-elasticsearch-logstash.html

**Comment by johnarakas** [comment]
you can go to configuration file and change to this for csv file
![image](https://user-images.githubusercontent.com/46790390/67411349-2f746e00-f5c6-11e9-9f38-8f9624f451b8.png)

**Comment by finchy** [comment]
I think the json output will most likely win.
