### ISSUE TITLE
faile to compile after cmake rpm red hat error

### ISSUE THREAD

**Issue by Azaretdodo** [snort3/snort3#104]
Hello,

My own error :

`[ 98%] Built target snort2lua
Scanning dependencies of target all_built_sources
[ 98%] Documents: building commands.txt with
[ 98%] Documents: building config.txt with
/opt/snort-3.0.0/build/src/snort: error while loading shared libraries: libhwloc.so.15: cannot open shared object file: No such file or directory
/opt/snort-3.0.0/build/src/snort: error while loading shared libraries: libhwloc.so.15: cannot open shared object file: No such file or directory
doc/CMakeFiles/all_built_sources.dir/build.make:80: recipe for target 'doc/commands.txt' failed
make[2]: *** [doc/commands.txt] Error 127
make[2]: *** Deleting file 'doc/commands.txt'
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:6037: recipe for target 'doc/CMakeFiles/all_built_sources.dir/all' failed
make[1]: *** [doc/CMakeFiles/all_built_sources.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2`

Thank you in advance to help me install snort 3 !

Regards.

Azaretdodo.

**Comment by Xiche** [comment]
Your system is not set up correctly; it doesn't have the path to libhwloc.so.15 in its LD_LIBRARY_PATH (default nor explicit).  The build process executes Snort by default to generate the documentation dynamically at the end, so you need to either disable that or have the proper library run-time paths set up.
