### ISSUE TITLE
appid enable_debug() not working 

### ISSUE THREAD

**Issue by dreizehnutters** [snort3/snort3#106]
Hi,

i would like to configure appId inspector module in a way so that for each event i get a debug msg that shows which src:port <-> dst:port was involved with the app.
How do you execute the `appid.enable_debug(proto, src_ip, src_port, dst_ip, dst_port)` command ? 

VERSION:
o")~   Snort++ 3.0.0-250

**Comment by dreizehnutters** [comment]
i found a workaround using `log_all_sessions = true`, but i would still like to know how to set the proper debug

**Comment by rvshravan** [comment]
"appid.log_all_sessions = true" is the right way to enable debug for AppId.

You could also use "packet_tracer = { enable = true }" to see packet-level debug that includes AppId information.

**Comment by dreizehnutters** [comment]
thanks for the hint @rvshravan! how do you tell the packet_tracer to log to a file ?
`packet_tracer = { output = file }` will compile but i cant seem to find its output (even with -l local_log_dir/)

**Comment by rvshravan** [comment]
Can you try the following?
packet_tracer =
{
  enable = true,
  output = 'file'
}

You should see packet tracer output in a file called packet_trace.txt.
