### ISSUE TITLE
Snort Crashes after about 10 min working

### ISSUE THREAD

**Issue by AkiJ5** [snort3/snort3#110]
VM, CentOS8, 4xCPU, 8GBxRAM.
Snort3 is assembled from source code for the manual from official web page.
Launching up by command:
`/usr/local/snort/bin/snort -c  /usr/local/snort/etc/snort/snort.lua -v -M -z 2 -s 65535 -k none -l /var/log/snort -i ens160 -i ens192 -m 0x1b`
Snort unexpectedly stoped process after about 10 minutes working.
I read it might happened due tcmalloc module. After that I removed tcmalloc and rebuilt Snort, but unsuccessfully.
Here are snort.lua, snort_default.lua and syslog output:
[snort3.zip](https://github.com/snort3/snort3/files/3968885/snort3.zip)
[syslog.txt](https://github.com/snort3/snort3/files/3968930/syslog.txt)

I have ran out of ideas, so, maybe somebody had same issue and came up with a solution.

**Comment by snortadmin** [comment]
Are you saying you used built from the tarball from snort.org?  That is *way* out of date.  Please pull from here and try.

**Comment by AkiJ5** [comment]
I used guide from snort.org called "Snort 3 on CentOS8" (https://www.snort.org/documents/snort-3-on-centos8). Here was link to github with actual Snort version.
In addition, that is my output of `snort -V`:

>   ,,_     -*> Snort++ <*-
>   o"  )~   Version 3.0.0 (Build 266)
>    ''''    By Martin Roesch & The Snort Team
>            http://snort.org/contact#team
>            Copyright (C) 2014-2019 Cisco and/or its affiliates. All rights reserved.
>            Copyright (C) 1998-2013 Sourcefire, Inc., et al.
>            Using DAQ version 3.0.0
>            Using LuaJIT version 2.1.0-beta3
>            Using OpenSSL 1.1.1 FIPS  11 Sep 2018
>            Using libpcap version 1.9.0-PRE-GIT (with TPACKET_V3)
>            Using PCRE version 8.42 2018-03-20
>            Using ZLIB version 1.2.11
>            Using FlatBuffers 1.11.0
>            Using Hyperscan version 5.2.0 2019-12-13
>            Using LZMA version 5.2.4

As you can see, I'm using latest build, which was post on github.

**Comment by snortadmin** [comment]
OK, Snort is crashing.  Can you provide us with a backtrace from your core file?

In the meantime, do you have  http_inspect.detained_inspection = true?  Try setting that to false as a workaround.

**Comment by AkiJ5** [comment]
Backtrace:
`BFD: warning: /var/lib/systemd/coredump/core.snort.0.48690aa1842845c6a4cc21b66380a05d.7105.1576507604000000 is truncated: expected core file size >= 2446954496, found: 2147483648
[New LWP 7106]
[New LWP 7107]
[New LWP 7105]
Cannot access memory at address 0x7f5a8ce91128
Cannot access memory at address 0x7f5a8ce91120
Failed to read a valid object file image from memory.
Core was generated by `/usr/local/snort/bin/snort -c /usr/local/snort/etc/snort/snort.lua -v -M -z 2 -'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000006ea8b6 in TcpStreamTracker::finalize_held_packet (this=<error reading variable: Cannot access memory at address 0x7f5a855a6a68>, cp=<error reading variable: Cannot access memory at address 0x7f5a855a6a60>) at /root/sources/snort3/src/stream/tcp/tcp_stream_tracker.cc:698
698         if ( held_packet )
[Current thread is 1 (LWP 7106)]
#0  0x00000000006ea8b6 in TcpStreamTracker::finalize_held_packet (this=<error reading variable: Cannot access memory at address 0x7f5a855a6a68>, cp=<error reading variable: Cannot access memory at address 0x7f5a855a6a60>) at /root/sources/snort3/src/stream/tcp/tcp_stream_tracker.cc:698
Backtrace stopped: Cannot access memory at address 0x7f5a855a6a78`

http_inspect didn't change and is set by default:
`http_inspect = { }`

**Comment by snortadmin** [comment]
Can you try setting this first in your Snort execution environment:

$ ulimit -c unlimited

Or whatever the equivalent is on your system to get a full core dump.  You might get a better backtrace that way.

Also, does this crash with -z 1?  You will get a smaller core.

**Comment by AkiJ5** [comment]
> Can you try setting this first in your Snort execution environment:
> 
> $ ulimit -c unlimited
> 
> Or whatever the equivalent is on your system to get a full core dump. You might get a better backtrace that way.

I executed that command and got next core dump:
[coredump_backtrace_2_core.txt](https://github.com/snort3/snort3/files/3977609/coredump_backtrace_2_core.txt)

It seems bigger than last one but is it better?

> Also, does this crash with -z 1? You will get a smaller core.

Yes. it does.
[coredump_backtrace_1_core.txt]
(https://github.com/snort3/snort3/files/3977616/coredump_backtrace_1_core.txt)

**Comment by snortadmin** [comment]
That is awesome.  We will investigate and get back to you.

Thanks!

**Comment by AkiJ5** [comment]
Hello!
Is there any updates?

**Comment by Xiche** [comment]
Sorry for the delay - I believe that I fixed this back in March with commit 58f0ee1242b83968a7a982558085597eb76c49fd.  Please reopen (or open a new issue) if you see this again.
