### ISSUE TITLE
snort_alert file doesn't exist or isn't writable

### ISSUE THREAD

**Issue by mntn0x** [snort3/snort3#115]
When i try to run such command
`snort -i ens33 -A alert_unixsock`
I get such output:
```
--------------------------------------------------
o")~   Snort++ 3.0.0-267
--------------------------------------------------
--------------------------------------------------
pcap DAQ configured to passive.
Commencing packet processing
++ [0] ens33
./snort_alert file doesn't exist or isn't writable
```
How can i solve this problem? I want to send alert messages to another program.

**Comment by snortadmin** [comment]
alert_unixsock writes to a Unix domain datagram socket.  The default name is ./snort_alert as shown above.  This must exist to write alerts to it.  You need a utility to listen on that socket and log events to it.  Here is an old example, you may find others:

https://www.snort.org/faq/readme-unsock

**Comment by mntn0x** [comment]
Thank you for your answer. But I got some errors when I ran the given code example. 
```
error: ‘Packet’ was not declared in this scope
   Packet *p;
```
Where can I find the definition of Packet?

**Comment by snortadmin** [comment]
That code is out of date.  For Snort 3, you can find Packet in <install>/include/snort/protocols/packet.h.  You will need to update the code accordingly.

**Comment by imagineTh4t** [comment]
I have same problem. I try so much unix socket logging. But i dont do it. Please help me ! ! !
