### ISSUE TITLE
Usage about multi threads 

### ISSUE THREAD

**Issue by Gunkkk** [snort3/snort3#121]
I have issues about the multi-threads options(-z). I have no idea that whether only when i want to process multi pcap files or monitor multi interfaces can i use multi threads in snort.
Can i monitor single interface or one pcap file using multithreads(-z)? Iv tried but failed.
Thanks!

**Comment by Xiche** [comment]
Hi Gunkkk,
This issue tracker is meant for bug reports and feature enhancement requests.  For general questions and discussions about Snort usage, please use the Snort-Users mailing list.  For discussion about Snort code development, use the Snort-Devel mailing list.  Information about the mailing lists can be found here: https://snort.org/community#mailing_lists.
