### ISSUE TITLE
seems log_pcap doesn't work

### ISSUE THREAD

**Issue by kwansikkim** [snort3/snort3#122]
Dear All,

I am trying to log pcap using Snort3. but it seems not working properly.

What i am doing is explained below.
-----------------snort.lua-----------------
include 'snort_defaults.lua'

stream = { }
stream_icmp = { }
stream_tcp = { }
stream_udp = { }

wizard = default_wizard

local_rules =
[[
alert tcp (msg:"Confidential Test"; content:"fiden";sid:1;)
]]

ips =
{
    rules = local_rules,
}

log_pcap = { limit=0 }
alert_fast = { file = true }

-----------------command-----------------
snort -r mystring.pcap -c snort.lua -l logs/ -s 65535 -k none

-----------------result-----------------
Two files were generated. alert_fast.txt look okay, but log.pcap file was empty like below
1. alert_fast.txt
 command: cat alert_fast.txt
 result:  03/26-10:42:13.180153 [**] [1:1:0] "Confidential Test" [**] [Priority: 0] {TCP} 192.168.56.101:16986 - > 192.168.56.107:5555

2. log.pcap.1585195712
 command: tcpdump -r log.pcap.1585195712
 result: reading from file log.pcap.1585195712, link-type EN10MB (Ethernet)

Is there something that I missed?
Thanks for your reply in advance.

Sincerely,

**Comment by snortadmin** [comment]
Hi, to activate pcap logging, add -L pcap to your command line.

In the future, please direct questions about usage to the Snort-Users mailing list (see https://snort.org/community#mailing_lists).

Thanks
Russ
