### ISSUE TITLE
named pipe as input for snort

### ISSUE THREAD

**Issue by dreizehnutters** [snort3/snort3#125]
Hello,

I have a named pipe which gets fed by a tcpdump loop. I would like to pass the pipe as an input for snort.
I tried doing it via -i, but DAQ does not recognize it as an valid interface. Also -r stops after the first pcap.
Any suggestion on how to solve the issue ?

**Comment by Xiche** [comment]
Is your expectation that they are treated as separate pcaps or a single large pcap?  (If the latter, you'll have to be careful about having the timestamps monotonically increase.)

**Comment by dreizehnutters** [comment]
timestamps do not matter for my case, i am mainly using appID.

I managed to get something working via:

keeping the pipe open and preventing EOF with `cat pipe &`
`(tcpdump -r first.pcap -w- ; tcpdump -r second.pcap -w-)  > pipe `


but snort  (DAQ) can not handle the stream 
`snort -r pipe &`
gives
```
pcap DAQ configured to read-file.
Commencing packet processing
++ [0] pipe
Error receiving message from the DAQ instance: invalid packet capture length 1577470442, bigger than maximum of 262144
-- [0] pipe
--------------------------------------------------
Packet Statistics
--------------------------------------------------
daq
                    pcaps: 1
                 received: 101
                 analyzed: 101
                    allow: 101
                 rx_bytes: 64896
```

(both pcaps contain 100 packets)

```
   ,,_     -*> Snort++ <*-
  o"  )~   Version 3.0.0 (Build 263)
   ''''    By Martin Roesch & The Snort Team
           http://snort.org/contact#team
           Copyright (C) 2014-2019 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using DAQ version 3.0.0
           Using LuaJIT version 2.1.0-beta3
           Using OpenSSL 1.1.1  11 Sep 2018
           Using libpcap version 1.8.1
           Using PCRE version 8.43 2019-02-23
           Using ZLIB version 1.2.11
           Using LZMA version 5.2.2
```

**Comment by AnnaNorokh** [comment]
Hi @dreizehnutters, what is the main goal of using tcpdump loop in this case? 

If you want to use a multiple pcaps you can go with these options:
```
--pcap-file <file> file that contains a list of pcaps to read - read mode is implied
--pcap-list <list> a space separated list of pcaps to read - read mode is implied
--pcap-dir <dir> a directory to recurse to look for pcaps - read mode is implied
```
