### ISSUE TITLE
Snort ld error. 

### ISSUE THREAD

**Issue by noodlehair-git** [snort3/snort3#126]
I get a set fault error when I run snort. When I check for the snort version, it does display it along with another error: 

```Inconsistency detected by ld.so: dl-fini.c: 87: _dl_fini: Assertion `ns != LM_ID_BASE || i == nloaded' failed!```

**Comment by Xiche** [comment]
Which operating system?  How did you build Snort?

**Comment by Xiche** [comment]
Closing due to no followup information.  Please reopen with additional information if you'd like to get to the bottom of this.
