### ISSUE TITLE
How to kill states/sessions/flows for a source IP address ?

### ISSUE THREAD

**Issue by ozkankirik** [snort3/snort3#127]
Is it possible to kill all states/sessions/flows for a source IP address?

It's important for Captive Portal integration. When a user authenticates on captive portal, ruleset is updated and snort is reloaded by scripts. 

I want to kill all states from source IP when user logged out from captive portal.

**Comment by snortadmin** [comment]
Hi - there is no existing API to do that.  It seems like something you should implement as part of your feature.  That said, flows to get removed when the clear, get pruned, or time out.  What motivates clearing stuff immediately?

**Comment by ozkankirik** [comment]
The motivation is user logout event on captive portal.
When a user logged out, all sessions belongs to this source IP address, should be flushed.

**Comment by finchy** [comment]
TCP timeout should handle this just fine without extra coding.  and the TCP timeouts would be handled differently depending on OS.
