### ISSUE TITLE
Install snotr3 

### ISSUE THREAD

**Issue by dejay77** [snort3/snort3#128]
Hello everyone Install Snotr3 on " Ubuntu 18.04.4 LTS"
I have an error on the level:
According to the manual:
[(https://snort-org-site.s3.amazonaws.com/production/document_files/files/000/000/251/original/Snort_3_on_Ubuntu.pdf)]

```
 cd ~/snort_src
git clone git://github.com/snortadmin/snort3.git
cd snort3

./configure_cmake.sh --prefix=/usr/local --enable-tcmalloc
cd build
make
```

1. sudo make installroot@es-System-Product-Name:~/snort_src/snort3/build#
2.  sudo make install
3. 
4. [  0%] Built target tcp_connector
5. [  0%] Building CXX object src/actions/CMakeFiles/ips_actions.dir/actions.cc.o
6. In file included from /root/snort_src/snort3/src/detection/rules.h:30:0,
7.                  from /root/snort_src/snort3/src/detection/detect.h:24,
8.                  from /root/snort_src/snort3/src/actions/actions.cc:25:
9. /root/snort_src/snort3/src/main/policy.h: In member function ‘const Shell* PolicyMap::get_shell_by_policy(unsigned int) const’:
10. /root/snort_src/snort3/src/main/policy.h:274:24: error: parameter declared ‘auto’
11.              [=](auto&& p) { return p.second->ips and p.second->ips->policy_id == id; });
12.                         ^
13. /root/snort_src/snort3/src/main/policy.h: In lambda function:
14. /root/snort_src/snort3/src/main/policy.h:274:36: error: ‘p’ was not declared in this scope
15.              [=](auto&& p) { return p.second->ips and p.second->ips->policy_id == id; });
16.                                     ^
17. In file included from /usr/include/c++/4.8/algorithm:62:0,
18.                  from /root/snort_src/snort3/src/main/policy.h:35,
19.                  from /root/snort_src/snort3/src/detection/rules.h:30,
20.                  from /root/snort_src/snort3/src/detection/detect.h:24,
21.                  from /root/snort_src/snort3/src/actions/actions.cc:25:
22. /usr/include/c++/4.8/bits/stl_algo.h: In instantiation of ‘_InputIterator std::__find_if(_InputIterator, _InputIterator, _Predicate, std::input_iterator_tag) [with _InputIterator = std::__detail::_Node_const_iterator<std::pair<Shell* const, std::shared_ptr<PolicyTuple> >, false, false>; _Predicate = PolicyMap::get_shell_by_policy(unsigned int) const::__lambda0]’:
23. /usr/include/c++/4.8/bits/stl_algo.h:4465:41:   required from ‘_IIter std::find_if(_IIter, _IIter, _Predicate) [with _IIter = std::__detail::_Node_const_iterator<std::pair<Shell* const, std::shared_ptr<PolicyTuple> >, false, false>; _Predicate = PolicyMap::get_shell_by_policy(unsigned int) const::__lambda0]’
24. /root/snort_src/snort3/src/main/policy.h:274:87:   required from here
25. /usr/include/c++/4.8/bits/stl_algo.h:150:56: error: no match for call to ‘(PolicyMap::get_shell_by_policy(unsigned int) const::__lambda0) (const std::pair<Shell* const, std::shared_ptr<PolicyTuple> >&)’
26.        while (__first != __last && !bool(__pred(*__first)))
27.                                                         ^
28. In file included from /root/snort_src/snort3/src/detection/rules.h:30:0,
29.                  from /root/snort_src/snort3/src/detection/detect.h:24,
30.                  from /root/snort_src/snort3/src/actions/actions.cc:25:
31. /root/snort_src/snort3/src/main/policy.h:274:15: note: candidate is:
32.              [=](auto&& p) { return p.second->ips and p.second->ips->policy_id == id; });
33.                ^
34. /root/snort_src/snort3/src/main/policy.h:274:25: note: PolicyMap::get_shell_by_policy(unsigned int) const::__lambda0
35.              [=](auto&& p) { return p.second->ips and p.second->ips->policy_id == id; });
36.                          ^
37. /root/snort_src/snort3/src/main/policy.h:274:25: note:   candidate expects 0 arguments, 1 provided
38. src/actions/CMakeFiles/ips_actions.dir/build.make:62: recipe for target 'src/actions/CMakeFiles/ips_actions.dir/actions.cc.o' failed
39. make[2]: *** [src/actions/CMakeFiles/ips_actions.dir/actions.cc.o] Error 1
40. CMakeFiles/Makefile2:373: recipe for target 'src/actions/CMakeFiles/ips_actions.dir/all' failed
41. make[1]: *** [src/actions/CMakeFiles/ips_actions.dir/all] Error 2
42. Makefile:151: recipe for target 'all' failed
43. make: *** [all] Error 2

Help!!!)

**Comment by Xiche** [comment]
You do not appear to be building on Ubuntu 18.04, as that would have had GCC 7.5.  Whatever system you are building on has GCC 4.8, which is too old and does not support C++14 (this is listed in the documentation as a dependency).
