### ISSUE TITLE
byte_jump without relative, from_beginning, or from_end behaves nonsensically

### ISSUE THREAD

**Issue by manger** [snort3/snort3#129]
The example of byte_jump in section 5.4.5 "Testing Numerical Values" (page 35) of the Snort 3 manual is:
`byte_jump:4,36,align;`
The text assumes this jumps to the end of the field starting 36 bytes in with the format: <4-byte length><text><pad to 4-byte boundary>. The example has a 10-byte text so the assumption is that byte_jump goes to 36+4+10+2 = 52.
But the jump actually goes to position 80. It is just a fluke both locations (52 & 80) match the next check in the example's rule.

When not from_beginning or from_end, the jump should be from the length field. This happens when the length field is found with a relative offset, but not when the offset is from the start of the buffer. In the latter case the given offset is used twice: as an offset from the start of the buffer to the length field; and as part of the jump from the current position. That is incomprehensible.

Quick rough suggestion for 'ips_options/ips_byte_jump.cc' is to change line 312 from:

>      else
>         pos = c.get_pos() + offset + payload_bytes_grabbed + jump;

to:

>     else if ( bjd->relative_flag )
>         pos = c.get_pos() + offset + payload_bytes_grabbed + jump;
>     else
>         pos = offset + payload_bytes_grabbed + jump;

Alternative, throw an error when a byte_jump element doesn't have relative, from_beginning, or from_end, because it has almost no chance of working how the author expects.

**Comment by InverseRE** [comment]
Fixed in https://github.com/snort3/snort3/commit/391d92f426b303b088e5ac60d97306a52c684a9c
