### ISSUE TITLE
Snort Jumbo Packets

### ISSUE THREAD

**Issue by bombblaster007** [snort3/snort3#130]
I am using Snort 2.9.16 in Ubuntu 18.04 as a virtual machine in VMWare. I wish to process packets greater than 1500 bytes which is the standard MTU of ethernet networks in Linux. I did:

1. Allowed jumbo packets in the Device Manager properties of the VMWare Virtual Ethernet Adapter.
2. Defined MTU to be 9000 in Ubuntu by the command "sudo ifconfig ens33 mtu 9000" (ens33 is my ethernet interface)
3. Changed "config snaplen:9000" in snort.conf file.

Even after doing all this, Snort still cannot analyse jumbo packets and drop if the packet size goes beyond 1500. Any suggestions on what I am doing wrong?

**Comment by snortadmin** [comment]
Please redirect to the snort-users list for Snort 2.X questions.  This is for Snort 3 only.  You should send your command line and shutdown counts too.  Thanks.

https://lists.snort.org/mailman/listinfo/snort-users
