### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by bombblaster007** [snort3/snort3#131]
Is multithreading enabled by default or do I need to make some changes in snort.conf or run using a different command? right now i am using "sudo snort -dve -i ens33:ens38 -c /etc/snort/snort.conf" to run the snort

**Comment by Xiche** [comment]
Hi bombblaster007,

This issue tracker is meant for bug reports and feature enhancement requests. For general questions and discussions about Snort usage, please use the Snort-Users mailing list. For discussion about Snort code development, use the Snort-Devel mailing list. Information about the mailing lists can be found here: https://snort.org/community#mailing_lists.
