### ISSUE TITLE
Snort can not start

### ISSUE THREAD

**Issue by topsekadmin** [snort3/snort3#134]
I use snort -dev -l /var/log/snort/ -h 192.168.30.0/24 -c /etc/snort/rules/etc/snort.conf start snort,shwo below
![image](https://user-images.githubusercontent.com/59950798/91241618-e954e180-e777-11ea-9bab-12729340c1b3.png)

config file show below
![image](https://user-images.githubusercontent.com/59950798/91241563-c7f3f580-e777-11ea-8a2c-cb6e8153ca85.png)

please help me, thank you very much

**Comment by snortadmin** [comment]
Post to the snort-users list.  This is for Snort 3 development.

https://snort.org/community#mailing_lists

Thanks
Russ
