### ISSUE TITLE
snort2lua

### ISSUE THREAD

**Issue by Gunkkk** [snort3/snort3#135]
As I convert snort2. rules 2 rules for snort3 with the command snort2lua -c a.rules, the converted rules are wrong for snort3.
 
ERROR: snort.lua:10743 !any is not allowed: ![$SMTP_SERVERS,$DNS_SERVERS].

**Comment by snortadmin** [comment]
Need to see the the original rules that aren't converting and the variable assignments for any variables used.

**Comment by Gunkkk** [comment]
eg：
**raw rules:**
alert udp !$DNS_SERVERS any -> $DNS_SERVERS 53 (msg:"MALWARE Inside host may be infected with IE7 worm Dec2008 based on DNS lookup jcl-0007.cn"; content:"|08|jcl-0007|02|cn"; nocase; classtype:trojan-activity; reference:url,www.shadowserver.org/wiki/pmwiki.php?n=Calendar.20081210; reference:url,www.kb.cert.org/vuls/id/493881; sid:1097249; rev:3;)
**converted:**
alert udp !$DNS_SERVERS any -> $DNS_SERVERS 53 ( msg:"MALWARE Inside host may be infected with IE7 worm Dec2008 based on DNS lookup baidu-du2.cn"; content:"|09|baidu-du2|02|cn",nocase; classtype:trojan-activity; reference:url,www.shadowserver.org/wiki/pmwiki.php?n=Calendar.20081210; reference:url,www.kb.cert.org/vuls/id/493881; sid:1097115; rev:3; )  
**info:**
ERROR: snort.lua:159 !any is not allowed: !$DNS_SERVERS. 


And I also value the DNS_SERVERS in config file .
It seems that there is no difference between raw rule and the converted. 
Thanks!





> Need to see the the original rules that aren't converting and the variable assignments for any variables used.

**Comment by snortadmin** [comment]
That converted rule is slightly different.  nocase must be comma separated for Snort 3 since it is part of the content option.

The problem appears to be with your snort.lua configuration.  It looks like that (or whatever it includes) has DNS_SERVERS = 'any' (possibly by way of HOME_NET).

This is not a bug so please follow up on the snort-users list if you have other questions about it.
