### ISSUE TITLE
snort.lua:31:attmpt to call global 'include' (a nil value)

### ISSUE THREAD

**Issue by minichameleon** [snort3/snort3#138]
When I try to execute ‘ snort -c /path/to/snorty/etc/snort/snort.lua'，return error: loading /path/to/snorty/etc/snort/snort.lua: FATAL: can't init /path/to/snorty/etc/snort/snort.lua: /path/to/snorty/etc/snort/snort.lua:31:attempt to call global 'include’ （a nil value). Fatal error Quiting.
what should I do to address the error？

**Comment by Xiche** [comment]
Hi minichameleon,
This issue tracker is meant for bug reports and feature enhancement requests. For general questions and discussions about Snort usage, please use the Snort-Users mailing list. For discussion about Snort code development, use the Snort-Devel mailing list. Information about the mailing lists can be found here: https://snort.org/community#mailing_lists.
