### ISSUE TITLE
NFQ inline mode    error (FATAL: Active response: can't open)

### ISSUE THREAD

**Issue by shirley04** [snort3/snort3#142]
1.   config snort.lua
daq =
{
        module_dirs =
        {
                '/usr/local/lib/daq'
        },
        modules =
        {
                {
                        name = 'nfq',
                        mode = 'inline'
                }
        },
        inputs =
        {
                '42'
        },
        snaplen = 65535
}

2.  run snort -T -c /usr/local/etc/snort/snort.lua -u snort -g snort  -Q
   display:
search engine
--------------------------------------------------
nfq DAQ configured to inline.

Snort successfully validated the configuration (with 0 warnings).
o")~   Snort exiting

3. run sudosnort -c /usr/local/etc/snort/snort.lua -s 65535  -k none -l /var/log/snort -Q
error dispaly:

nfq DAQ configured to inline.
Commencing packet processing
++ [0] 42
FATAL: Active response: can't open
Fatal Error, Quitting..

**Comment by matirko** [comment]
Hi, 

We are working on a fix for this issue, but in the meantime, please try adding the following to your snort.lua, prior to the definitions for the daq:

```lua
active = { device = 'ip' }
``` 
This will force the active module to attempt to use dnet's ```ip_open()``` for packet injection.

Please see [this file in our documentation](https://github.com/snort3/snort3/blob/master/doc/user/active.txt ) for more details about the use of active.device

**Comment by Xiche** [comment]
Should hopefully be resolved with 38e5bf308d68d62756f5dcbca47f3883e832edbd.
