### ISSUE TITLE
make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by DigiAngel** [snort3/snort3#144]
New box....I've got build-essential, make, automake, and autoconf installed (Ubuntu 20).  Any idea what I'm missing?  Thanks.

**Comment by Xiche** [comment]
Hi DigiAngel,

You seem to have missed some vital steps in building Snort.  Please consult the README.

This issue tracker is meant for bug reports and feature enhancement requests. For general questions and discussions about Snort usage, please use the Snort-Users mailing list. For discussion about Snort code development, use the Snort-Devel mailing list. Information about the mailing lists can be found here: https://snort.org/community#mailing_lists.
