### ISSUE TITLE
FATAL: ips.rules:3 undefined variable name: BUILTIN_RULE_PATH.

### ISSUE THREAD

**Issue by anonimou0** [snort3/snort3#146]
On a fresh compilation and install, when trying to start snort3 with a service or with `/usr/local/bin/snort -c /usr/local/etc/snort/snort.lua -i ens4 -s 65535 -k none -l /var/log/snort ` I get the following output:

```
Finished /usr/local/etc/snort/snort.lua:
Loading ips.rules:
FATAL: ips.rules:3 undefined variable name: BUILTIN_RULE_PATH.
Fatal Error, Quitting..
```

Notice that the BUILTIN_RULE_PATH variable is defined in `/usr/local/etc/snort/snort_defaults.lua` .
```
   ,,_     -*> Snort++ <*-
  o"  )~   Version 3.0.3 (Build 4)
   ''''    By Martin Roesch & The Snort Team
           http://snort.org/contact#team
           Copyright (C) 2014-2020 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using DAQ version 3.0.0
           Using LuaJIT version 2.1.0-beta3
           Using OpenSSL 1.1.1  11 Sep 2018
           Using libpcap version 1.8.1
           Using PCRE version 8.43 2019-02-23
           Using ZLIB version 1.2.11
           Using FlatBuffers 1.12.0
           Using Hyperscan version 5.3.0 2020-11-13
           Using LZMA version 5.2.2
```

**Comment by Xiche** [comment]
Hi anonimou0,

This issue tracker is meant for bug reports and feature enhancement requests. For general questions and discussions about Snort usage, please use the Snort-Users mailing list. For discussion about Snort code development, use the Snort-Devel mailing list. Information about the mailing lists can be found here: https://snort.org/community#mailing_lists.

While I appreciate you reporting this issue, it is really a misconfiguration and if you had looked on the mailing lists, you would have seen that it has come up twice already in the last couple days.  As you noted the variable is defined in snort_defaults.lua in default_variables.paths.  Your snort.lua then needs to set the ips.variables to default_variables or something that includes that (the default snort.lua does this).

**Comment by anonimou0** [comment]
Sorry for opening this issue here.

Something has changed on Snort 3.0.3, from first builds to 4 and newer. 

For those from the future that are following [this tutorial](https://snort-org-site.s3.amazonaws.com/production/document_files/files/000/000/251/original/Snort_3_on_Ubuntu.pdf) or similars, 

I was using the downloaded one that I modified (based on build 1). I had that on an ansible script that was deploying fine, except on build 4.

You need to include
**variables = default_variables**
on the **ips** block at the `snort.lua` file. It will be something similar to:

```
ips =
{
    enable_builtin_rules = true,

    rules = [[
        include $BUILTIN_RULE_PATH/builtins.rules
        include $RULE_PATH/all_snort3.rules
    ]],

    variables = default_variables,
}

```

Something probably changed between build 1 and build 4 (snort 3.0.3) and explicitly calling the default_variables is now necessary. I had a 'include snort_default.lua' on the 'snort.lua' file, but that didn't work.
