### ISSUE TITLE
Hi anonimou0,

### ISSUE THREAD

**Issue by jlowmiller** [snort3/snort3#148]
Here is a feature request. 

How about you actually use the issues tracker for things such as this, because the public is not going to know the difference between a code or configuration problem. 

Mailing lists are archaic, and an unnecessary hoop to jump through for something that was just recently introduced in a commit. 

-----
Hi anonimou0,

This issue tracker is meant for bug reports and feature enhancement requests. For general questions and discussions about Snort usage, please use the Snort-Users mailing list. For discussion about Snort code development, use the Snort-Devel mailing list. Information about the mailing lists can be found here: https://snort.org/community#mailing_lists.

While I appreciate you reporting this issue, it is really a misconfiguration and if you had looked on the mailing lists, you would have seen that it has come up twice already in the last couple days.  As you noted the variable is defined in snort_defaults.lua in default_variables.paths.  Your snort.lua then needs to set the ips.variables to default_variables or something that includes that (the default snort.lua does this).

_Originally posted by @Xiche in https://github.com/snort3/snort3/issues/146#issuecomment-726964402_

**Comment by anonimou0** [comment]
Hello @jlowmiller .

I just saw this ticket.

In fact, this was just a configuration issue and I apologized on the original ticket #146 . While this is just a configuration issue, it could be considered a bug as it was INTRODUCED on a new build? Or not? Anyway, I pointed what changed on that ticket if anyone is curious.

Same files, same configuration files, same rules, same everything except the the build and its code have changed. I know it is not totally related, but might worth the read: https://lkml.org/lkml/2012/12/23/75 .  Also, I acknowledge that Snort 3 is in constant development which, of course, I appreciate. I know it's almost out of beta. But such a change, without a "Release note" pointing out, between releases, might be bad for users and Snort PR as well.

When I created that ticket I was not sure which side that would fall (config vs bug) as I am now. So, sorry for bothering you.

**Comment by Xiche** [comment]
@anonimou0 I'm not sure what this issue was (it popped out of nowhere and was bizarrely passive aggressive and then closed).  The commenter here does not represent the Snort team.  It doesn't seem to have had anything to do with you other than latching onto a response that I had sent to you in a previous issue.
