### ISSUE TITLE
Issues to compile: collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by dragonxtek** [snort3/snort3#149]
I'm trying to compile snort3 from the github version. To do it I installed libdaq from github version.
When I tried to compile snort3 I had the following issue, after compiled snort2lua:

> Scanning dependencies of target snort2lua
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[100%] Building CXX object tools/snort2lua/CMakeFiles/snort2lua.dir/init_state.cc.o
[100%] Building CXX object tools/snort2lua/CMakeFiles/snort2lua.dir/snort2lua.cc.o
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[100%] Linking CXX executable snort2lua
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[100%] Linking CXX executable snort
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[100%] Built target snort2lua
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq.cc.o: in function `AddDaqModuleConfig(SFDAQModuleConfig const*)':
/tmp/snort3/src/packet_io/sfdaq.cc:170: undefined reference to `daq_module_config_new'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:185: undefined reference to `daq_module_config_set_mode'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:191: undefined reference to `daq_module_config_set_variable'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:195: undefined reference to `daq_module_config_destroy'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:200: undefined reference to `daq_config_push_module_config'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:202: undefined reference to `daq_module_get_name'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:204: undefined reference to `daq_module_config_destroy'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq.cc.o: in function `snort::SFDAQ::load(SFDAQConfig const*)':
/tmp/snort3/src/packet_io/sfdaq.cc:67: undefined reference to `daq_load_static_modules'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:69: undefined reference to `daq_load_dynamic_modules'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq.cc.o: in function `snort::SFDAQ::print_types(std::ostream&)':
/tmp/snort3/src/packet_io/sfdaq.cc:86: undefined reference to `daq_modules_first'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:120: undefined reference to `daq_module_get_variable_descs'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:135: undefined reference to `daq_modules_next'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:95: undefined reference to `daq_module_get_name'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:95: undefined reference to `daq_module_get_version'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:97: undefined reference to `daq_module_get_type'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq.cc.o: in function `snort::SFDAQ::init(SFDAQConfig const*, unsigned int)':
/tmp/snort3/src/packet_io/sfdaq.cc:231: undefined reference to `daq_config_new'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:237: undefined reference to `daq_config_set_msg_pool_size'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:238: undefined reference to `daq_config_set_snaplen'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:239: undefined reference to `daq_config_set_timeout'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:262: undefined reference to `daq_module_get_type'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:280: undefined reference to `daq_config_destroy'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:241: undefined reference to `daq_config_set_total_instances'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:231: undefined reference to `daq_config_new'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:250: undefined reference to `daq_config_destroy'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:269: undefined reference to `daq_config_destroy'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq.cc.o: in function `snort::SFDAQ::term()':
/tmp/snort3/src/packet_io/sfdaq.cc:300: undefined reference to `daq_config_destroy'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq.cc.o: in function `snort::SFDAQ::can_run_unprivileged()':
/tmp/snort3/src/packet_io/sfdaq.cc:323: undefined reference to `daq_config_top_module_config'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:329: undefined reference to `daq_config_next_module_config'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:326: undefined reference to `daq_module_config_get_module'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq.cc:327: undefined reference to `daq_module_get_type'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::~SFDAQInstance()':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:53: undefined reference to `daq_instance_destroy'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::init(_daq_config*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:76: undefined reference to `daq_config_set_input'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq_instance.cc:77: undefined reference to `daq_config_get_total_instances'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq_instance.cc:79: undefined reference to `daq_instance_instantiate'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `DAQ_ValidateInstance':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:58: undefined reference to `daq_instance_get_capabilities'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::init(_daq_config*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:90: undefined reference to `daq_instance_set_filter'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq_instance.cc:92: undefined reference to `daq_instance_get_error'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq_instance.cc:78: undefined reference to `daq_config_set_instance_id'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::reload()':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:105: undefined reference to `daq_instance_config_load'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq_instance.cc:108: undefined reference to `daq_instance_config_swap'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq_instance.cc:109: undefined reference to `daq_instance_config_free'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq_instance.cc:111: undefined reference to `daq_instance_config_free'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::can_inject() const':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:132: undefined reference to `daq_instance_get_capabilities'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::can_inject_raw() const':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:137: undefined reference to `daq_instance_get_capabilities'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::can_replace() const':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:142: undefined reference to `daq_instance_get_capabilities'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::can_start_unprivileged() const':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:147: undefined reference to `daq_instance_get_capabilities'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::can_whitelist() const':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:152: undefined reference to `daq_instance_get_capabilities'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::receive_messages(unsigned int)':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:194: undefined reference to `daq_instance_msg_receive'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::finalize_message(_daq_msg const*, DAQ_Verdict)':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:203: undefined reference to `daq_instance_msg_finalize'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::get_tunnel_capabilities()':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:219: undefined reference to `daq_instance_get_capabilities'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::was_started() const':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:252: undefined reference to `daq_instance_check_status'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::stop()':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:252: undefined reference to `daq_instance_check_status'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq_instance.cc:263: undefined reference to `daq_instance_stop'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq_instance.cc:266: undefined reference to `daq_instance_get_error'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::start()':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:157: undefined reference to `daq_instance_start'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq_instance.cc:165: undefined reference to `daq_instance_get_msg_pool_info'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq_instance.cc:180: undefined reference to `daq_instance_get_datalink_type'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq_instance.cc:160: undefined reference to `daq_instance_get_error'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq_instance.cc:168: undefined reference to `daq_instance_get_error'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::interrupt()':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:283: undefined reference to `daq_instance_interrupt'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::get_stats()':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:290: undefined reference to `daq_instance_get_stats'
/usr/bin/ld: /tmp/snort3/src/packet_io/sfdaq_instance.cc:292: undefined reference to `daq_instance_get_error'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::modify_flow_opaque(_daq_msg const*, unsigned int)':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:317: undefined reference to `daq_instance_ioctl'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::set_packet_verdict_reason(_daq_msg const*, unsigned char)':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:327: undefined reference to `daq_instance_ioctl'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::set_packet_trace_data(_daq_msg const*, unsigned char*, unsigned int)':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:338: undefined reference to `daq_instance_ioctl'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::add_expected(snort::Packet const*, snort::SfIp const*, unsigned short, snort::SfIp const*, unsigned short, IpProtocol, unsigned int, unsigned int)':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:404: undefined reference to `daq_instance_ioctl'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::get_error()':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:211: undefined reference to `daq_instance_get_error'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::inject(_daq_msg const*, int, unsigned char const*, unsigned int)':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:273: undefined reference to `daq_instance_inject_relative'
/usr/bin/ld: packet_io/CMakeFiles/packet_io.dir/sfdaq_instance.cc.o: in function `snort::SFDAQInstance::ioctl(DAQ_IoctlCmd, void*, unsigned long)':
/tmp/snort3/src/packet_io/sfdaq_instance.cc:308: undefined reference to `daq_instance_ioctl'
/usr/bin/ld: utils/CMakeFiles/utils.dir/util.cc.o: in function `DisplayBanner()':
**/tmp/snort3/src/utils/util.cc:105: undefined reference to `daq_version_string'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/snort.dir/build.make:1604: src/snort] Error 1
make[1]: *** [CMakeFiles/Makefile2:333: src/CMakeFiles/snort.dir/all] Error 2
make: *** [Makefile:152: all] Error 2**

What is the reason for this error?

**Comment by Xiche** [comment]
It is not successfully linking against libdaq.  Make sure that you don't have two versions of libdaq installed, that could confuse it at link time.

**Comment by dragonxtek** [comment]
You are right
I remove libdaq-dev and now it works!
Thanks
