### ISSUE TITLE
Snort tcp alerts are not visible in Wireshark

### ISSUE THREAD

**Issue by Darthzner** [snort3/snort3#151]
Hello everyone, i have a problem when i want to see the alerts of snort on wireshark gui, contextualizing, i mount a xmpp sv and client on docker containers, and display snort on my host machine, when snort generate an icmp alert, the alerts are visible in wireshark gui, but if is tcp are not visible on this gui.

How can i see tcp alerts on wireshark?

I hope you can help me with this problem.
Thanks.

**Comment by InverseRE** [comment]
Hi,
Can you specify if you can see TCP alerts in console. For example, running it with -A cmg option?

**Comment by Darthzner** [comment]
Hi,
yep, the alerts are visible in console, and i try with wireshark 3.2.3 and 3.4, but i can't see the alerts.

I friend testing with the version 3.2.7 , can see tcp alerts.


![image](https://user-images.githubusercontent.com/58405045/101679556-45e5bf00-3a3e-11eb-812f-84f8d9e5f956.png)

**Comment by InverseRE** [comment]
In that case I guess, it could be due to Wireshark Display Filters or Preference Settings (like, showing alerts in reassembled frames).

Could be helpful:
https://gitlab.com/wireshark/wireshark/-/wikis/Snort
https://www.wireshark.org/docs/dfref/s/snort.html

Regards.

**Comment by finchy** [comment]
Sounds like this needs to be adjusted in WireShark.  Not here.
