### ISSUE TITLE
snort3 crashed for segmentation fault

### ISSUE THREAD

**Issue by Gunkkk** [snort3/snort3#152]
When we use snort3 in the production environment, it was killed after some hours, which seems related to the rules and alerts.
CTX
![image](https://user-images.githubusercontent.com/24769606/105569409-45c52880-5d39-11eb-829e-ba4cb0a96e38.png)

Backtrrace from abrt:
[abrt_mail.txt](https://github.com/snort3/snort3/files/5859708/abrt_mail.txt)
It seems crash in DCE2_CoSetRopts, with repsect to service_inspectors/dec_rpc
@Xiche @snortadmin 
Thanks!

**Comment by snortadmin** [comment]
Are you able to run it in a non-production environment?

Really can't assess w/o more information.  Have you tried to configure abrt to get more information?  I see ProcessUnpackaged = no.  See https://abrt.readthedocs.io/en/latest/faq.html#how-to-enable-handling-of-unpackaged-software for more on that setting but you may have other steps to take.

If you can run a custom build in your production environment, you can build with libunwind to get a backtrace upon a fatal signal:

libunwind from https://www.nongnu.org/libunwind/ to attempt to dump a somewhat readable backtrace when a fatal signal is received

**Comment by Gunkkk** [comment]
> Are you able to run it in a non-production environment?
> 
> Really can't assess w/o more information. Have you tried to configure abrt to get more information? I see ProcessUnpackaged = no. See https://abrt.readthedocs.io/en/latest/faq.html#how-to-enable-handling-of-unpackaged-software for more on that setting but you may have other steps to take.
> 
> If you can run a custom build in your production environment, you can build with libunwind to get a backtrace upon a fatal signal:
> 
> libunwind from https://www.nongnu.org/libunwind/ to attempt to dump a somewhat readable backtrace when a fatal signal is received

I think the reason is that the memory was consumed by snort thus causing OOM, is there any solutions to limit memory use in snort3.
Thanks!

**Comment by Gunkkk** [comment]
> > Are you able to run it in a non-production environment?
> > Really can't assess w/o more information. Have you tried to configure abrt to get more information? I see ProcessUnpackaged = no. See https://abrt.readthedocs.io/en/latest/faq.html#how-to-enable-handling-of-unpackaged-software for more on that setting but you may have other steps to take.
> > If you can run a custom build in your production environment, you can build with libunwind to get a backtrace upon a fatal signal:
> > libunwind from https://www.nongnu.org/libunwind/ to attempt to dump a somewhat readable backtrace when a fatal signal is received
> 
> I think the reason is that the memory was consumed by snort thus causing OOM, is there any solutions to limit memory use in snort3.
> Thanks!

It reports segmentation fault！

**Comment by Gunkkk** [comment]
[abrt_mail.txt](https://github.com/snort3/snort3/files/5859682/abrt_mail.txt)
Here is the backtrace.
Thanks!
@snortadmin @Xiche

**Comment by Xiche** [comment]
Are you really using 3.0.0-247?  That's an early beta build from over two years ago.

**Comment by Gunkkk** [comment]
> Are you really using 3.0.0-247? That's an early beta build from over two years ago.

emmm yes, so the problem has already solved in new version right?
Thanks

**Comment by Xiche** [comment]
> > Are you really using 3.0.0-247? That's an early beta build from over two years ago.
> 
> emmm yes, so the problem has already solved in new version right?
> Thanks

I can't guarantee that, but all of the code has a changed a lot in that time.

**Comment by Gunkkk** [comment]
> Are you really using 3.0.0-247? That's an early beta build from over two years ago.

emmm yes, so the problem has already solved in new version right?
Thanks

**Comment by Gunkkk** [comment]
> > > Are you really using 3.0.0-247? That's an early beta build from over two years ago.
> > 
> > 
> > emmm yes, so the problem has already solved in new version right?
> > Thanks
> 
> I can't guarantee that, but all of the code has a changed a lot in that time.
And in new snort3.1, the libdaq cannot be build in centos7, is there any solutions about this? 
I think we cannot change our platform easily, Thanks.

**Comment by Gunkkk** [comment]
> > > Are you really using 3.0.0-247? That's an early beta build from over two years ago.
> > 
> > 
> > emmm yes, so the problem has already solved in new version right?
> > Thanks
> 
> I can't guarantee that, but all of the code has a changed a lot in that time.

Or in the backtrace, what have caused the problem, how can we improve it with right config.

**Comment by Gunkkk** [comment]
solved by disabling dce service.

**Comment by snortadmin** [comment]
Assuming fixed.  Reopen the issue if you still see it in the latest.

Thanks.

**Comment by Xiche** [comment]
> > I can't guarantee that, but all of the code has a changed a lot in that time.
> And in new snort3.1, the libdaq cannot be build in centos7, is there any solutions about this?
> I think we cannot change our platform easily, Thanks.

See my response in the libdaq repository to your issue raised about AFPacket on CentOS 7 about it being a bit of an awkward time capsule from 2013.  We currently have no plans to try to make Snort work on CentOS 7 because of all the missing dependencies and even the deficiencies in the toolchain (we require c++14 support, a standard that was finalized after CentOS 7 was even released much less the code was frozen).
