### ISSUE TITLE
Packet number display wrong problem

### ISSUE THREAD

**Issue by Zoeliuliu** [snort3/snort3#153]
1. Is the packet number frame.number of wiresshark?
2. By analyzing the file, we found that the packet number of the ssh-type event is one bit different from the wireshark frame number
But other types of events are the same as wireshark's frame number

**Comment by git4lad** [comment]
Hi Zoeliuliu

Yes, the packet number should correspond to the frame number in Wireshark.
An event may come after the actual packet containing the event if Snort is running in post-ack (passive or inline-test) mode.

Also this issue tracker is meant for bug reports and feature enhancement requests. For general questions and discussions about Snort usage, please use the Snort-Users mailing list. For discussion about Snort code development, use the Snort-Devel mailing list. Information about the mailing lists can be found here: https://snort.org/community#mailing_lists.
