### ISSUE TITLE
repeat alerts problem

### ISSUE THREAD

**Issue by Gunkkk** [snort3/snort3#154]
![image](https://user-images.githubusercontent.com/24769606/105672428-4fd35c80-5edc-11eb-8590-2d7eabe71292.png)
It seems that my snort will generate double repeat alerts, only with different timestamp, even with basic cmd to monitor single interface.
Is that normal?
Thanks!

**Comment by Xiche** [comment]
I really do appreciate your willingness to put in the effort to report issues, but before we go any further, can you please confirm the version of Snort 3 that you are using?  If it's still the beta version from two and a half years ago like in the last issue you raised, it's not going to be a good use of our resources to debug the issue.
