### ISSUE TITLE
Error 2 when I try to compile snort

### ISSUE THREAD

**Issue by dragonxtek** [snort3/snort3#155]
Hi,
Recently I formatted my pc and I installed Ubuntu 20.10
I downloaded snort 3.1. After configured it, without issues, I tried to compile it, but I got the following error:
![Selection_004](https://user-images.githubusercontent.com/10552658/105737252-7f05c000-5f14-11eb-8d54-fac1603ce867.png)
How can I fix it?

**Comment by Xiche** [comment]
That's a warning, not an error; you didn't post the actual error.

**Comment by dragonxtek** [comment]
The first lines are warnings, but the last are error. 
make stops and it not continued

**Comment by Xiche** [comment]
It is reporting than an error occurred previously and is stopping compilation.  There will be somewhere above in the output the actual error message when it was encountered (filename:line: error: ...).

**Comment by dragonxtek** [comment]
I run make again and now I have this error. Maybe this can help
![Selection_005](https://user-images.githubusercontent.com/10552658/105754167-7fa85180-5f28-11eb-9a5b-f7f747344cb6.png)

**Comment by Xiche** [comment]
Your libdaq is out-of-date.  Make sure you have libdaq 3.0.0 (final) either from GitHub or snort.org.
