### ISSUE TITLE
SIGSEGV fatal signal - Snort 3.1.2.0 - v2

### ISSUE THREAD

**Issue by WingerHusar** [snort3/snort3#165]
Hi, 
I have again this problem. I followed this instruction:  "Snort 3.1.0.0 on Ubuntu 18 & 20" but I took a source code from github so I have snort version 3.1.2.0 and libdaq 3.0.1.

I installed also hyperscan.
It worked for 4 hours (this logs) but sometimes it works for 14 hours.

I think when there is something in incoming traffic, snort can't handle it.

<pre>
Snort (PID 7) caught fatal signal: SIGSEGV (11)
Version: 3.1.2.0

Backtrace:
  #0 0x558082b39534 in _ZN3Ssh4evalEPN5snort6PacketE.cold+0x28 (/usr/local/bin/snort @0x5580829a1000)
  #1 0x558082c1f763 in _ZN5snort16InspectorManager15full_inspectionILb0EEEvPNS_6PacketE+0x63 (/usr/local/bin/snort @0x5580829a1000)
  #2 0x558082c1fc98 in _ZN5snort16InspectorManager16internal_executeILb0EEEvPNS_6PacketE+0x4e8 (/usr/local/bin/snort @0x5580829a1000)
  #3 0x558082b87cfc in _ZN5snort15DetectionEngine7inspectEPNS_6PacketE+0x6c (/usr/local/bin/snort @0x5580829a1000)
  #4 0x558082c000b4 in _ZN8Analyzer15inspect_rebuiltEPN5snort6PacketE+0x34 (/usr/local/bin/snort @0x5580829a1000)
  #5 0x558082c80b3f in _ZN14TcpReassembler12flush_to_seqER19TcpReassemblerStatejPN5snort6PacketEj+0xbf (/usr/local/bin/snort @0x5580829a1000)
  #6 0x558082c84591 in _ZN10TcpSession13flush_trackerER16TcpStreamTrackerPN5snort6PacketEjb+0x51 (/usr/local/bin/snort @0x5580829a1000)
  #7 0x558082c831f9 in _ZN10TcpSession21update_session_on_rstER20TcpSegmentDescriptorb+0x39 (/usr/local/bin/snort @0x5580829a1000)
  #8 0x558082c856c8 in _ZN17TcpStateCloseWait8rst_recvER20TcpSegmentDescriptorR16TcpStreamTracker+0x38 (/usr/local/bin/snort @0x5580829a1000)
  #9 0x558082c876f0 in _ZN15TcpStateMachine4evalER20TcpSegmentDescriptor+0x90 (/usr/local/bin/snort @0x5580829a1000)
  #10 0x558082c8484f in _ZN10TcpSession18process_tcp_packetER20TcpSegmentDescriptorPKN5snort6PacketE+0x1f (/usr/local/bin/snort @0x5580829a1000)
  #11 0x558082c8500e in _ZN10TcpSession7processEPN5snort6PacketE+0x28e (/usr/local/bin/snort @0x5580829a1000)
  #12 0x558082c1fd70 in _ZN5snort16InspectorManager16internal_executeILb0EEEvPNS_6PacketE+0x5c0 (/usr/local/bin/snort @0x5580829a1000)
  #13 0x558082b87cfc in _ZN5snort15DetectionEngine7inspectEPNS_6PacketE+0x6c (/usr/local/bin/snort @0x5580829a1000)
  #14 0x558082c00031 in _ZL14process_packetPN5snort6PacketE+0xb1 (/usr/local/bin/snort @0x5580829a1000)
  #15 0x558082c01224 in _ZN8Analyzer19process_daq_pkt_msgEPK8_daq_msgb+0xb4 (/usr/local/bin/snort @0x5580829a1000)
  #16 0x558082c014c8 in _ZN8Analyzer15process_daq_msgEPK8_daq_msgb+0x248 (/usr/local/bin/snort @0x5580829a1000)
  #17 0x558082c01dd6 in _ZN8Analyzer16process_messagesEv+0x1a6 (/usr/local/bin/snort @0x5580829a1000)
  #18 0x558082c0211b in _ZN8Analyzer7analyzeEv+0x5b (/usr/local/bin/snort @0x5580829a1000)
  #19 0x558082c022e1 in _ZN8AnalyzerclEP7Swappert+0xd1 (/usr/local/bin/snort @0x5580829a1000)
  #20 0x7fec28f7dd84 in _ZNKSt10error_code23default_error_conditionEv+0x34 (/lib/x86_64-linux-gnu/libstdc++.so.6 @0x7fec28ea7000)
  #21 0x7fec2975c609 in start_thread+0xd9 (/lib/x86_64-linux-gnu/libpthread.so.0 @0x7fec29753000)
  #22 0x7fec28c6b293 in clone+0x43 (/lib/x86_64-linux-gnu/libc.so.6 @0x7fec28b49000)

= Current DAQ Message (Type 1) =

== Header (48) ==
2930 5b60 0000 0000 6d29 0f00 0000 0000
3c00 0000 ffff ffff ffff ffff ffff ffff
0000 0000 0000 0000 0000 0000 0000 0000

== Data (60) ==
0000 0011 1111 0031 4619 bdbc 0800 4500
0028 f099 4000 3a06 c83f 0586 d7f0 9c11
0e6f 01bb f0e7 4fcd 3de0 0000 0000 5004
0000 a799 0000 0000 0000 0000

xxxx.sh line 3:     7 Segmentation fault      (core dumped) /usr/local/bin/snort -c /usr/local/etc/snort/snort.lua -u snort -s 65535 -k none -l /var/log/snort -i $INTERFACE -D

</pre>

<pre>
   ,,_     -*> Snort++ <*-
  o"  )~   Version 3.1.2.0
   ''''    By Martin Roesch & The Snort Team
           http://snort.org/contact#team
           Copyright (C) 2014-2020 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using DAQ version 3.0.1
           Using LuaJIT version 2.1.0-beta3
           Using OpenSSL 1.1.1f  31 Mar 2020
           Using libpcap version 1.9.1 (with TPACKET_V3)
           Using PCRE version 8.44 2020-02-12
           Using ZLIB version 1.2.11
           Using FlatBuffers 1.12.0
           Using Hyperscan version 5.3.0 2021-03-18
           Using LZMA version 5.2.4
</pre>

**Comment by samaraya** [comment]
We are looking at it and can you please add PCAP related to it? 

Thanks,
Samuel

**Comment by WingerHusar** [comment]
Actually it works now really good but without hyperscan and related software. I can't add pcap now.

**Comment by anonimou0** [comment]
Not saying that this is fixed, but I haven't had an issue with version 3.1.7 in almost 13 days (which is a record for Snort3 on my scenario).
