### ISSUE TITLE
compilation error 2

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [snort3/snort3#166]
Hi,

last git (today March 25th)

OS: Fedora 33 64bits
gcc: version 10

many repeating warnings, this is the last part
/home/src/snort3/src/sfip/sf_ip.h:387:10: warning: taking address of packed member of ‘snort::SfIp’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  387 |     p1 = ip32;
      |          ^~~~
/home/src/snort3/src/sfip/sf_ip.h:388:14: warning: taking address of packed member of ‘snort::SfIp’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  388 |     p2 = ip2.ip32;
      |          ~~~~^~~~
/home/src/snort3/src/sfip/sf_ip.h: In member function ‘bool snort::SfIp::fast_eq6(const snort::SfIp&) const’:
/home/src/snort3/src/sfip/sf_ip.h:417:10: warning: taking address of packed member of ‘snort::SfIp’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  417 |     p1 = ip32;
      |          ^~~~
/home/src/snort3/src/sfip/sf_ip.h:418:14: warning: taking address of packed member of ‘snort::SfIp’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  418 |     p2 = ip2.ip32;
      |          ~~~~^~~~
In file included from /home/src/snort3/src/sfip/sf_cidr.h:24,
                 from /home/src/snort3/src/main/snort_config.h:37,
                 from /home/src/snort3/src/file_api/file_api.h:33,
                 from /home/src/snort3/src/file_api/file_policy.h:26,
                 from /home/src/snort3/src/file_api/file_service.h:27,
                 from /home/src/snort3/src/file_api/file_service.cc:30:
/home/src/snort3/src/sfip/sf_ip.h: In member function ‘const uint32_t* snort::SfIp::get_ip4_ptr() const’:
/home/src/snort3/src/sfip/sf_ip.h:137:12: warning: taking address of packed member of ‘snort::SfIp’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  137 |     return &ip32[3];
      |            ^~~~~~~~
/home/src/snort3/src/sfip/sf_ip.h: In member function ‘const uint32_t* snort::SfIp::get_ip6_ptr() const’:
/home/src/snort3/src/sfip/sf_ip.h:142:12: warning: taking address of packed member of ‘snort::SfIp’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  142 |     return ip32;
      |            ^~~~
/home/src/snort3/src/sfip/sf_ip.h: In member function ‘const uint32_t* snort::SfIp::get_ptr() const’:
/home/src/snort3/src/sfip/sf_ip.h:148:16: warning: taking address of packed member of ‘snort::SfIp’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  148 |         return &ip32[3];
      |                ^~~~~~~~
/home/src/snort3/src/sfip/sf_ip.h:149:12: warning: taking address of packed member of ‘snort::SfIp’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  149 |     return ip32;
      |            ^~~~
/home/src/snort3/src/sfip/sf_ip.h: In member function ‘SfIpRet snort::SfIp::_ip6_cmp(const snort::SfIp&) const’:
/home/src/snort3/src/sfip/sf_ip.h:311:10: warning: taking address of packed member of ‘snort::SfIp’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  311 |     p1 = ip32;
      |          ^~~~
/home/src/snort3/src/sfip/sf_ip.h:312:14: warning: taking address of packed member of ‘snort::SfIp’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  312 |     p2 = ip2.ip32;
      |          ~~~~^~~~
/home/src/snort3/src/sfip/sf_ip.h: In member function ‘bool snort::SfIp::fast_lt6(const snort::SfIp&) const’:
/home/src/snort3/src/sfip/sf_ip.h:357:10: warning: taking address of packed member of ‘snort::SfIp’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  357 |     p1 = ip32;
      |          ^~~~
/home/src/snort3/src/sfip/sf_ip.h:358:14: warning: taking address of packed member of ‘snort::SfIp’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  358 |     p2 = ip2.ip32;
      |          ~~~~^~~~
/home/src/snort3/src/sfip/sf_ip.h: In member function ‘bool snort::SfIp::fast_gt6(const snort::SfIp&) const’:
/home/src/snort3/src/sfip/sf_ip.h:387:10: warning: taking address of packed member of ‘snort::SfIp’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  387 |     p1 = ip32;
      |          ^~~~
/home/src/snort3/src/sfip/sf_ip.h:388:14: warning: taking address of packed member of ‘snort::SfIp’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  388 |     p2 = ip2.ip32;
      |          ~~~~^~~~
/home/src/snort3/src/sfip/sf_ip.h: In member function ‘bool snort::SfIp::fast_eq6(const snort::SfIp&) const’:
/home/src/snort3/src/sfip/sf_ip.h:417:10: warning: taking address of packed member of ‘snort::SfIp’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  417 |     p1 = ip32;
      |          ^~~~
/home/src/snort3/src/sfip/sf_ip.h:418:14: warning: taking address of packed member of ‘snort::SfIp’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  418 |     p2 = ip2.ip32;
      |          ~~~~^~~~
[ 15%] Built target file_api
make: *** [Makefile:171: all] Error 2

**Comment by Xiche** [comment]
I know it might be hard to see beyond the warnings (you can silence those with -Wno-address-of-packed-member), but you didn't actually include the error here, only the delayed error status from an earlier error.  You want something that says <filename>: error: <error>.

**Comment by ROBERT-MCDOWELL** [comment]
attached log of stderr
[log.txt](https://github.com/snort3/snort3/files/6207965/log.txt)

**Comment by Xiche** [comment]
```
/home/src/snort3/src/main/analyzer.cc:168:11: error: ‘DAQ_FlowStats_t’ does not name a type; did you mean ‘DAQ_Stats_t’?
  168 |     const DAQ_FlowStats_t *stats = (const DAQ_FlowStats_t*) daq_msg_get_hdr(msg);
```
You need the latest version of libdaq (3.0.1).

**Comment by Xiche** [comment]
Next push of Snort will have an updated version requirement for libdaq so that it will fail during the configure step.  Thanks.

**Comment by ROBERT-MCDOWELL** [comment]
ha ok, this is something I easily forget... thanks
