### ISSUE TITLE
ERROR: can't compile content '<SCRIPT'

### ISSUE THREAD

**Issue by jeremy-loukinas** [snort3/snort3#171]
Ubuntu 5.4.0-71-generic #79-Ubuntu SMP Wed Mar 24 10:56:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux 2 20.04 LTS

I have followed the installation instructions to the letter, when I run: 

snort -c /usr/local/etc/snort/snort.lua

--------------------------------------------------
o")~   Snort++ 3.1.0.0
--------------------------------------------------
ERROR: can't compile content '<SCRIPT'
ERROR: can't compile content '</SCRIPT>'
Loading /usr/local/etc/snort/snort.lua:
Loading snort_defaults.lua:
Finished snort_defaults.lua:
Loading file_magic.lua:

pcap DAQ configured to passive.
FATAL: see prior 2 errors (0 warnings)
Fatal Error, Quitting..

What does can't compile content mean?

**Comment by snortadmin** [comment]
It means the hyperscan library can't compile the script pattern because your runtime environment doesn't support the required CPU architecture. See these for how to fix it:

https://github.com/snort3/snort3/issues/167
https://github.com/snort3/snort3/issues/158
