### ISSUE TITLE
Are sequential intrusion patterns supported in snort?

### ISSUE THREAD

**Issue by inf3rno** [snort3/snort3#174]
I read an old article about mining sequential intrusion patterns for different threats: [Building intrusion pattern miner for Snort network intrusion detection system](https://www.sciencedirect.com/science/article/abs/pii/S0164121206003517#!)  Was this feature ever included to snort? If not, then why?

**Comment by inf3rno** [comment]
@inf3rno Please check fast parallel sequential pattern mining solutions when you plan it. This one is in theory a lot faster than any other: http://resources.mpi-inf.mpg.de/d5/mg-fsm/mg-fsm-sigmod13.pdf I read many articles about these algorithms, and I have the impression that security ppl don't use them, because they are slow, but they try out 20 years old algorithms... In theory they can do something similar than a machine learning based approach or they can complement each other.

**Comment by snortadmin** [comment]
Thanks.
