### ISSUE TITLE
3.1.4.0: can't find reputation.blacklist

### ISSUE THREAD

**Issue by da667** [snort3/snort3#178]
Hi there,

I pulled down Snort 3.1.4.0 today, and compiled it on Ubuntu 20.04 with libdaq 3.0.3. I'm using the standard `snort.lua` with the following includes:
`snort_defaults.lua`
`file_magic.lua`

All three of these files are in their default state. The reputation preprocessor is commented out in snort.lua, and snort_defaults has both the WHITE_LIST_PATH and BLACK_LIST_PATH variables commented out. 

I also have a custom include appended to the very end of `snort.lua`, `virtual_labs_tweaks.lua`. Here are the contents of that file:

```
--These configuration lines will perform the following tasks:
--enables the built-in preproc rules, and snort.rules file
--enables hyperscan as the search engine for pattern matching
--enables the DAQ for inline mode
--enables the IP reputation blacklist
--enables JSON alerting for snort alerts
--enables appid, the appid listener, and logging appid events.

ips =
{
    enable_builtin_rules = true,

    include = "/usr/local/etc/rules/snort.rules",

    variables = default_variables
}

search_engine = { search_method = "hyperscan" }

detection =
{
    hyperscan_literals = true,
    pcre_to_regex = true
}

daq =
{
    module_dirs =
    {
        '/usr/local/lib/daq',
    },
    modules =
    {
        {
            name = 'afpacket',
            mode = 'inline',
            variables =
            {
                'fanout_type=hash'
            }
        }
    },
    inputs =
    {
        'ens192:ens224',
    }
}

reputation=
{
    blacklist = '/usr/local/etc/lists/default.blocklist',
}

alert_json =
{
    file = true,
    limit = 1000,
    fields = 'seconds action class b64_data dir dst_addr dst_ap dst_port eth_dst eth_len \
    eth_src eth_type gid icmp_code icmp_id icmp_seq icmp_type iface ip_id ip_len msg mpls \
    pkt_gen pkt_len pkt_num priority proto rev rule service sid src_addr src_ap src_port \
    target tcp_ack tcp_flags tcp_len tcp_seq tcp_win tos ttl udp_len vlan timestamp',
}

appid =
{
    app_detector_dir = '/usr/local/lib',
}

appid_listener =
{
    json_logging = true,
    file = "/var/log/snort/appid-output.log",
}
```
This configuration file worked perfectly fine on Snort 3.1.0.0. However, as of snort 3.1.4.0, here is the output from:
`snort -T -c /usr/local/etc/snort/snort.lua`:

```
root@ips:/usr/local/etc/snort# snort -T -c /usr/local/etc/snort/snort.lua
--------------------------------------------------
o")~   Snort++ 3.1.4.0
--------------------------------------------------
[snipped for brevity]
ERROR: /usr/local/etc/snort/snort.lua: can't find reputation.blacklist
[snipped for brevity]
FATAL: see prior 1 errors (0 warnings)
Fatal Error, Quitting..
```

For some reason, snort seems to be attempting to look for the file `reputation.blacklist`. On my system, all of the snort lua files (including the custom one I did up above) are in /usr/local/etc/snort. Running the grep command against all of these files returns zero results for reputation.blacklist:
```
root@ips:/usr/local/etc/snort# pwd
/usr/local/etc/snort
root@ips:/usr/local/etc/snort# ls -al
total 9848
drwxr-xr-x 2 root root    4096 Apr 29 23:12 .
drwxr-xr-x 7 root root    4096 Apr 29 22:21 ..
-rw-r--r-- 1 root root     590 Apr 21 20:06 balanced.lua
-rw-r--r-- 1 root root     616 Apr 21 20:06 connectivity.lua
-rw-r--r-- 1 root root   38693 Apr 21 20:06 file_magic.lua
-rw-r--r-- 1 root root     410 Apr 21 20:06 inline.lua
-rw-r--r-- 1 root root    1268 Apr 21 20:06 max_detect.lua
-rw-r--r-- 1 root root     959 Apr 21 20:06 security.lua
-rw-r--r-- 1 root root 9941038 Apr 29 22:22 sid-msg.map
-rw-r--r-- 1 root root   46539 Apr 21 20:06 snort_defaults.lua
-rw-r--r-- 1 root root    8282 Apr 29 22:21 snort.lua
-rw-r--r-- 1 root root     874 Apr 21 20:06 talos.lua
-rw-r--r-- 1 root root    1809 Apr 29 23:12 virtual_labs_tweaks.lua
root@ips:/usr/local/etc/snort# grep -F reputation.blacklist *.lua
root@ips:/usr/local/etc/snort#
```
as you can see, zero results. I have no idea where snort is looking for the file reputation.blacklist, when I defined `default.blocklist` as my preferred blacklist file. I've tried
`strace -e open,read snort -c /usr/local/etc/snort/snort.lua`

and the output doesn't show snort attempting to open or read reputation.blacklist, just that it can't find the file.

I've also tried `ltrace` and running snort with the `-v` option. 

My blacklist file is located in: `/usr/local/etc/lists/default.blocklist`. It was created using pulledpork, and to my knowledge, the formatting is correct.

commenting out the lines:
```
reputation=
{
    blacklist = '/usr/local/etc/lists/default.blocklist',
}
```

Causes snort to start up correctly with no hitches. 

Any ideas?

**Comment by git4lad** [comment]
Hi da667, 

Please change 'blacklist =' in your configuration to 'blocklist = ' 
We changed these terms recently and hence it's giving you an error about reputation.blacklist. 

Try blow, 

```lua
reputation =
{
    blocklist = '/usr/local/etc/lists/default.blocklist',
}
```
check this file for more - https://github.com/snort3/snort3/releases/download/3.1.4.0/snort_reference.html (search for reputation) 

hope this will help!

**Comment by da667** [comment]
Thanks for your help. This solved my problem. Have a great weekend.
