### ISSUE TITLE
The documentation files are not generated in the system after Snort3 installation

### ISSUE THREAD

**Issue by jiangrij** [snort3/snort3#183]
The Snort3 readme indicates:
> Take a look at the manual, parts of which are generated by the code so it stays up to date:
> $my_path/share/doc/snort/snort_manual.pdf
> $my_path/share/doc/snort/snort_manual.html
> $my_path/share/doc/snort/snort_manual/index.html

However, I cannot find these generated documentation files above from the system installed with Snort3, the directory keeps the TXT files only.
> -rw-r--r-- 1 root root   5334 May 15 09:05 active.txt
> -rw-r--r-- 1 root root    583 May 15 09:05 appendix.txt
> -rw-r--r-- 1 root root   8701 May 15 09:05 appid.txt
> -rw-r--r-- 1 root root   2098 May 15 09:05 binder.txt
> -rw-r--r-- 1 root root   1406 May 15 09:05 building.txt
> -rw-r--r-- 1 root root   1589 May 15 09:05 byte_extract.txt
> -rw-r--r-- 1 root root    756 May 15 09:05 byte_jump.txt
> -rw-r--r-- 1 root root   1209 May 15 09:05 byte_math.txt
> -rw-r--r-- 1 root root   6236 May 15 09:05 byte_options.txt
> -rw-r--r-- 1 root root   1105 May 15 09:05 byte_test.txt
> -rw-r--r-- 1 root root  12036 May 15 09:05 concepts.txt
> -rw-r--r-- 1 root root  16634 May 15 09:05 config_changes.txt
> -rw-r--r-- 1 root root   3174 May 15 09:05 connectors.txt
> -rw-r--r-- 1 root root  14481 May 15 09:05 daq.txt
> -rw-r--r-- 1 root root  14624 May 15 09:05 dcerpc.txt
> -rw-r--r-- 1 root root  13050 May 15 09:05 differences.txt
> -rw-r--r-- 1 root root   8385 May 15 09:05 dump_config.txt
> -rw-r--r-- 1 root root    645 May 15 09:05 enviro.txt
> -rw-r--r-- 1 root root   1177 May 15 09:05 errors.txt
> -rw-r--r-- 1 root root  21700 May 15 09:05 extending.txt
> -rw-r--r-- 1 root root   1282 May 15 09:05 features.txt
> -rw-r--r-- 1 root root   5153 May 15 09:05 file_processing.txt
> -rw-r--r-- 1 root root   6222 May 15 09:05 ftp.txt
> -rw-r--r-- 1 root root   1566 May 15 09:05 high_availability.txt
> -rw-r--r-- 1 root root   1687 May 15 09:05 http2_inspect.txt
> -rw-r--r-- 1 root root  28984 May 15 09:05 http_inspect.txt
> -rw-r--r-- 1 root root   3744 May 15 09:05 iec104.txt
> -rw-r--r-- 1 root root  14951 May 15 09:05 overview.txt
> -rw-r--r-- 1 root root   2559 May 15 09:05 params.txt
> -rw-r--r-- 1 root root   3599 May 15 09:05 perf_monitor.txt
> -rw-r--r-- 1 root root   1770 May 15 09:05 pop_imap.txt
> -rw-r--r-- 1 root root  10113 May 15 09:05 port_scan.txt
> -rw-r--r-- 1 root root    562 May 15 09:05 README.u2boat
> -rw-r--r-- 1 root root   4576 May 15 09:05 sensitive_data.txt
> -rw-r--r-- 1 root root   1924 May 15 09:05 side_channel.txt
> -rw-r--r-- 1 root root   6572 May 15 09:05 smtp.txt
> -rw-r--r-- 1 root root   9320 May 15 09:05 snort2lua.txt
> -rw-r--r-- 1 root root   6070 May 15 09:05 snort2x.png
> -rw-r--r-- 1 root root  11490 May 15 09:05 snort3x.png
> -rw-r--r-- 1 root root    300 May 15 09:05 snort_devel.txt
> -rw-r--r-- 1 root root 486174 May 15 09:05 snort_reference.text
> -rw-r--r-- 1 root root   2027 May 15 09:05 snort_reference.txt
> -rw-r--r-- 1 root root  53490 May 15 09:05 snort_upgrade.text
> -rw-r--r-- 1 root root    354 May 15 09:05 snort_upgrade.txt
> -rw-r--r-- 1 root root 220716 May 15 09:05 snort_user.text
> -rw-r--r-- 1 root root    568 May 15 09:05 snort_user.txt
> -rw-r--r-- 1 root root  36975 May 15 09:05 snorty.png
> -rw-r--r-- 1 root root  13191 May 15 09:05 style.txt
> -rw-r--r-- 1 root root    573 May 15 09:05 telnet.txt
> -rw-r--r-- 1 root root   2978 May 15 09:05 terms.txt
> -rw-r--r-- 1 root root  23773 May 15 09:05 trace.txt
> -rw-r--r-- 1 root root  10620 May 15 09:05 tutorial.txt
> -rw-r--r-- 1 root root   7467 May 15 09:05 usage.txt
> -rw-r--r-- 1 root root   1587 May 15 09:05 wizard.txt

**Comment by snortadmin** [comment]
Only the .text formats you listed are included in the repo and the docs are not generated by default with a top-level make. If you have the toolchain required, cd into <build>/doc/ and do `make help` to see the list of targets, or just do make docs-all to build all. Note that make all does not do anything intentionally so ignore that target.

**Comment by jiangrij** [comment]
@snortadmin Thanks for the information. When I tried to build the docs, I got the following errors. What kind of rule is needed for building docs-user-pdf?
> [ 85%] Documents: building snort_user.html and snort_online.html
> asciidoc: WARNING: overview.txt: line 262: section title out of sequence: expected level 2, got level 3
> asciidoc: WARNING: overview.txt: line 262: section title out of sequence: expected level 2, got level 3
> [ 85%] Built target docs-user-html
> Scanning dependencies of target docs-user
> make[3]: *** No rule to make target '../doc/docs-user-pdf', needed by 'doc/CMakeFiles/docs-user'.  Stop.
> make[2]: *** [CMakeFiles/Makefile2:6991: doc/CMakeFiles/docs-user.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:6900: doc/CMakeFiles/docs-all.dir/rule] Error 2
> make: *** [Makefile:258: doc/CMakeFiles/docs-all.dir/rule] Error 2

**Comment by snortadmin** [comment]
1. Ignore the asciidoc warnings for now. We will fix those but the content should still be rendered, if a little off.

2. If you do cd <builddir>/doc/; make help, those are the targets available in that directory. If you do cd <builddir>/doc/user/; make help, those are the targets available in that directory. To build docs-user-pdf, do it from doc/user/. To build docs-user, do it from doc/.

**Comment by jiangrij** [comment]
@snortadmin Thanks for the update.
This is output while I running `make docs-user` under /doc/, 
> [ 98%] Documents: building version.txt
> [ 98%] Built target usr_built_sources
> [100%] Documents: building snort_user.html and snort_online.html
> asciidoc: WARNING: overview.txt: line 262: section title out of sequence: expected level 2, got level 3
> asciidoc: WARNING: overview.txt: line 262: section title out of sequence: expected level 2, got level 3
> [100%] Built target docs-user-html
> make[3]: *** No rule to make target 'doc/docs-user-pdf', needed by 'doc/CMakeFiles/docs-user'.  Stop.
> make[2]: *** [CMakeFiles/Makefile2:6032: doc/CMakeFiles/docs-user.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:6039: doc/CMakeFiles/docs-user.dir/rule] Error 2
> make: *** [Makefile:322: doc/CMakeFiles/docs-user.dir/rule] Error 2

This is output while I running `make help` under /doc/user/, I didn't find the option to build docs-user-pdf. Please advise.
> The following are some of the valid targets for this Makefile:
> ... all (the default if no target is provided)
> ... clean
> ... depend
> ... edit_cache
> ... install
> ... install/local
> ... install/strip
> ... list_install_components
> ... package
> ... package_source
> ... rebuild_cache
> ... docs-user-html
> ... usr_built_sources

**Comment by snortadmin** [comment]
You are probably missing dblatex. Check the user manual under Tutorial / Dependencies.
