### ISSUE TITLE
Pdf  and elf file detection

### ISSUE THREAD

**Issue by dev2021-ctrl** [snort3/snort3#188]
Snort version 2.9.17 linux OS
I am trying to detect the pdf file via ftp .
I have build snort from source in linux and using option --enable-file-inspect
I am using the below preprocessor in snort.conf
preprocessor file_inspect: type_id

Also below is the local.rules
alert tcp any any -> any any ( msg:”PDF”; file_type:PDF; )

But it is not working .The above rule is not triggered.

Please advise
A bit urgent

**Comment by snortadmin** [comment]
This is for Snort 3 development. You already posted to the snort-users list which is where to get help for Snort 2. That said, you might be better off with Snort 3.

**Comment by dev2021-ctrl** [comment]
ok i  just installed snort3 and compiled as above mentioned steps.
But still it is not detecting pdf .
Can you share the working rules for the same.
Do I need to enable some preprocessors

**Comment by snortadmin** [comment]
This is a user question. Post it to snort-users as a Snort 3 question and I'm sure someone will help. This is not the place for usage queries.

Thanks
Russ
