### ISSUE TITLE
How to configure correctly Snort3 with Docker 

### ISSUE THREAD

**Issue by Jakub41** [snort3/snort3#189]
Hello,

My inquiry is about a project I'm building in Docker with Snort3 and what should be the correct way to have it set it up to get in the console the alerts logs.
The project is here: [Docker Snort3 demo](https://github.com/Jakub41/snort3-traefik-docker-demo) 

I tried many researchers but was unable to make the correct setup for the HOME_NET and to see the alerts when I try to ping any of the IP addresses I set up in the snort.lua

Would be possible to get help to set it up correctly in my project?

I would like to make it work and correctly. 

Please help me to improve my knowledge on this matter and the way I should make the set up with Docker to run Snort3 as should be.

Thank you for yours help :)

**Comment by InverseRE** [comment]
Hi.

To get familiar with Snort3, it's better to start running it locally outside of any containers (such as Docker).
Once you have a successful build, try some simple configurations. snort3_demo project could be handy.

For example, https://github.com/snort3/snort3_demo/blob/master/tests/loggers/alert_ex has a simple config and a rule to detect ICMP packets or you can add your own:
`alert icmp ( msg:"ICMP"; gid:1; sid:1; rev:1; )`

When you get alerts, you can proceed with Docker and other components (like trying a full set of rules).

**Comment by Jakub41** [comment]
Hi thank you for the suggestion.
I already did am entire configuration between a Kali Linux and Ubuntu virtual machines and I had no problems.

My problem is in Docker as I configured everything as same way but the alerts are not showing up.

I suspect is because of how docker network works and maybe some specific configuration of this. 

If you know how to make it run with Docker please help. I'm stuck on make the alerts work and to try ping on the docker network I'm trying to monitoring.

Thank you

**Comment by snortadmin** [comment]
Hi - post this to the [snort-users](https://snort.org/community#mailing_lists) mailer where you will find a wider audience of users. This is for development issues only.
