### ISSUE TITLE
[Question] Dumping dynamic rules in Snort3

### ISSUE THREAD

**Issue by redbaron4** [snort3/snort3#190]
I have been using snort2 and using pulledpork to manage the rules. Now I am trying out Snort3 to get a hang of it. I have managed to compile and install v3.1.5.0 & also have the correct ruleset (snortrules-snapshot-3150.tar.gz).

When I run pulledpork, the static rules get copied correctly but dynamic rules give an error like

```
Reading rules...
Snort 3.0 detected, future Snort 3.0 processing
Generating Stub Rules....
        Generating shared object stubs via:/usr/bin/snort -c /etc/snort/snort.lua --dump-dynamic-rules=/tmp/tha_rules/so_rules/
        An error occurred: ERROR: can't set --dump-dynamic-rules /tmp/tha_rules/so_rules/

        An error occurred: ERROR: usage: --dump-dynamic-rules output stub rules for all loaded rules libraries

        An error occurred: FATAL: see prior 2 errors

        An error occurred: Fatal Error, Quitting..

        Done
        Reading rules...
        Reading rules...
```

This is not a fatal error but dynamic rules do not get dumped. I have verified that so_rules exist in the ruleset so it means they should be supported.

I tried to run the command to dump rules manaually

```
# /usr/bin/snort -c /etc/snort/snort.lua --dump-dynamic-rules
no rules to dump

# /usr/bin/snort -c /etc/snort/snort.lua --dump-dynamic-rules=/tmp/so_rules/
ERROR: can't set --dump-dynamic-rules /tmp/so_rules/
ERROR: usage: --dump-dynamic-rules output stub rules for all loaded rules libraries
FATAL: see prior 2 errors
Fatal Error, Quitting..
```

The option `--dump-dynamic-rules` seems to be missing from help and yet is accepted by command line. There is also a function `void SoManager::dump_rule_stubs(const char*, SnortConfig* sc)` in `src/managers/so_manager.cc`.

Am I doing something wrong or is it a bug in Snort command line parsing?

**Comment by InverseRE** [comment]
Hi


```
> ./snort --help-options dump-dynamic-rules
--dump-dynamic-rules output stub rules for all loaded rules libraries
```
The option doesn't need a value. It dumps the rules Snort sees from configuration files (and/or from plugins).

**Comment by redbaron4** [comment]
Thanks @InverseRE for pointing out this change.

Looks like there is also an open bug in pulledpork https://github.com/shirkdog/pulledpork/issues/359 for same.
