### ISSUE TITLE
snort 3.1.6.0 can't drop packet

### ISSUE THREAD

**Issue by hebtuerror404** [snort3/snort3#193]
My snort.lua（Part）
```lua
---------------------------------------------------------------------------
-- Snort++ configuration
---------------------------------------------------------------------------

-- there are over 200 modules available to tune your policy.
-- many can be used with defaults w/o any explicit configuration.
-- use this conf as a template for your specific configuration.

-- 1. configure defaults
-- 2. configure inspection
-- 3. configure bindings
-- 4. configure performance
-- 5. configure detection
-- 6. configure filters
-- 7. configure outputs
-- 8. configure tweaks

daq =
{
    module_dirs =
    {
        '/usr/local/lib/daq',
    },
    modules =
    {
        {
            name = 'afpacket',
            mode = 'inline',
            variables =
            {
                'fanout_type=hash'
            }
        }
    },
    inputs =
    {
        'ens38:ens39',
    }
}

---------------------------------------------------------------------------
-- 1. configure defaults
---------------------------------------------------------------------------
......
---------------------------------------------------------------------------
-- 5. configure detection
---------------------------------------------------------------------------

references = default_references
classifications = default_classifications

ips =
{
    mode = inline,
    -- use this to enable decoder and inspector alerts
    enable_builtin_rules = true,

    -- use include for rules files; be sure to set your path
    -- note that rules files can include other rules files
    --include = 'snort3-community.rules',
    -- include = '/usr/local/etc/rules/local.rules',

    variables = default_variables
}
```
My local.rule（Part）
```
drop tcp any any -> any 8000
(
    msg:"drop_test detected!";
    sid:10000002;
)
```
Start command：
```
sudo snort -c lua/snort.lua -R rules/local.rules --daq-dir /usr/local/lib/daq --daq afpacket --daq-var fanout_type=hash -i ens38:ens39 -A alert_fast -s 65535 -k none -Q
```
log shows：
```
06/21-20:49:33.631019 [drop] [**] [1:10000002:0] "drop_test detected!" [**] [Priority: 0] {TCP} 192.168.253.128:48560 -> 192.168.253.129:8000
06/21-20:49:33.630995 [drop] [**] [1:10000002:0] "drop_test detected!" [**] [Priority: 0] {TCP} 192.168.200.130:48560 -> 192.168.253.129:8000
06/21-20:49:37.776024 [drop] [**] [1:10000002:0] "drop_test detected!" [**] [Priority: 0] {TCP} 192.168.253.128:48560 -> 192.168.253.129:8000
06/21-20:49:37.775982 [drop] [**] [1:10000002:0] "drop_test detected!" [**] [Priority: 0] {TCP} 192.168.200.130:48560 -> 192.168.253.129:8000
```
But！192.168.253.129 still can receive message from 192.168.200.130！
192.168.253.129 use `nc -lv 8000`
192.168.200.130 use `nc 192.168.253.129 8000`
snort3 exec in gateway PC.

**Comment by leibaogit** [comment]
We encounter the same issue, and looking forward a solution.

**Comment by ma-dagon** [comment]
In order to triage the issue, can you please provide a sample pcap and the config files you are using? Thanks!

**Comment by hebtuerror404** [comment]
> In order to triage the issue, can you please provide a sample pcap and the config files you are using? Thanks!

Because snort3 has correctly displayed the traffic matching information and displayed the actions that will be performed. The problem is that snort3 does not perform this action as shown in its log. Therefore, providing a local pcap file may not be of great help in solving the problem. You can take the following steps to reproduce this problem:
1. Use VMware Workstation (my version is VMware® Workstation 16 Pro) to create three virtual machines. PC1-Ubuntu 18.04, PC2-Ubuntu 18.04, PC3-Kali 2021
2. Add two additional virtual network cards (ens38, ens39) to PC2.
3. Connect PC1 and PC2 (ens38) to the host-only virtual network VMnet4.
4. Connect PC3 and PC2 (ens39) to the host-only virtual network VMnet5.
5. PC2 (ens33) still maintains a NAT connection with the physical machine.
6. Configure NAT rules through iptables on PC2 and enable ip forwarding.
7. Configure the gateway address of PC1 as the IP address of PC2 (ens38).
8. Configure the gateway address of PC3 as the IP address of PC2 (ens39).
9. Try to ping PC3 from PC1, it should respond normally.
10. Run `nc -lv 8000` on PC1
11. Run `nc <PC1_address> 8000` on PC3
12. Now, PC1 and PC3 have established a TCP-based communication channel.
13. Run `sudo snort -c lua/snort.lua -R rules/local.rules --daq-dir /usr/local/lib/daq --daq afpacket --daq-var fanout_type=hash -i on PC2 ens38:ens39 -A alert_fast -s 65535 -k none -Q` (lua/snort.lua and rules/local.rules have been provided above)
14. Send any information on PC3, PC2's snort3 alarms and prompts drop information.**But, PC1 can still receive TCP messages from PC3.**

The traffic captured on the gateway PC (PC2) for ens38 and ens39, local rule files and local lua files will be uploaded to Google Drive later.

**Comment by ma-dagon** [comment]
Thank you for the information. A couple of questions:
Has this test and topology worked for you in the past? 
Are you able to send netcat messages without Snort running?

**Comment by hebtuerror404** [comment]
Q: Has this test and topology worked for you in the past?
A:No,I only started to try snort3 four days ago.So I am not sure if this issue is related to the version 3.1.6.0.
Q: Are you able to send netcat messages without Snort running?
A:Of course I can,the real problem is that no matter whether snort3 is running or not, netcat messages can be sent and received normally, which means that the IPS function of snort3 has not taken effect.BTW,According to the content of the document, snort3 is not a routing management tool. Therefore, it is impossible that ,netcat messages can be sent and received normally if snort3 is running, and when snort3 is stopped, netcat messages cannot be sent and received normally：）

**Comment by Xiche** [comment]
>     6\. Configure NAT rules through iptables on PC2 and enable ip forwarding.

This is where you're going to get into trouble.  AFPacket's inline mode is L2 forwarding; it will simply spit the L2 packets it receives on one side of the inline pair out the other.  If you've configured the DUT (PC2) to forward the packets outside of Snort, they'll still be forwarded regardless of what Snort does as AFPacket operates on a copy of the packets rather than the original.  What you should see if you dump on either of endpoints without that rule to drop is that there are two copies of each packet coming out of PC2 - the original forwarded by AFPacket and the one forwarded by the Linux kernel's forwarding.

**Comment by Xiche** [comment]
In case it wasn't clear from what I was describing, the proper AFPacket inline setup will look like this:
`[PC1 - eth0 (1.1.1.1)] <-> [eth1 (no IP) - PC2 - eth2 (no IP)] <-> [eth0 (1.1.1.2) - PC2]`
As opposed to what you've described, which would be like this:
`[PC1 - eth0 (1.1.1.2)] <-> [eth1 (1.1.1.1) - PC2 - eth2 (2.2.2.1)] <-> [eth0 (2.2.2.2) - PC2]`
With the IP forwarding being handled by PC2's kernel.

**Comment by hebtuerror404** [comment]
In other words, snort is unable to intercept the original package, right?
Because I need to filter the gateway traffic, and snort itself does not have the ability of NAT. This is why I chose to use iptables for additional network configuration. So if I want to complete the above requirements, how should I set up snort?

**Comment by Xiche** [comment]
The traditional IPS setup would have a transparent inline IPS device that does L2 forwarding through a pair of inline interfaces; that is was AFPacket was designed for.  If you absolutely must combine your IPS and IP forwarding/routing into a single device, you'll need to use something like the NFQ DAQ module instead that allows Snort to see and vote on traffic as it's being routed.

**Comment by hebtuerror404** [comment]
Ok i see, thanks for your explanation.
