### ISSUE TITLE
build err 

### ISSUE THREAD

**Issue by traveler0007** [snort3/snort3#195]
/home/snort3/src/main/policy.h: In lambda function:
/home/snort3/src/main/policy.h:272:99: error: ‘p’ was not declared in this scope
         auto it = std::find_if(std::begin(shell_map), std::end(shell_map), [=](auto&& p) { return p.second->ips and p.second->ips->policy_id == id; });
                                                                                                   ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /home/snort3/src/main/policy.h:35,
                 from /home/snort3/src/detection/rules.h:31,
                 from /home/snort3/src/detection/detect.h:24,
                 from /home/snort3/src/actions/actions.cc:25:
/usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of ‘_InputIterator std::__find_if(_InputIterator, _InputIterator, _Predicate, std::input_iterator_tag) [with _InputIterator = std::__detail::_Node_const_iterator<std::pair<Shell* const, std::shared_ptr<PolicyTuple> >, false, false>; _Predicate = PolicyMap::get_shell_by_policy(unsigned int) const::__lambda0]’:
/usr/include/c++/4.8.2/bits/stl_algo.h:4465:41:   required from ‘_IIter std::find_if(_IIter, _IIter, _Predicate) [with _IIter = std::__detail::_Node_const_iterator<std::pair<Shell* const, std::shared_ptr<PolicyTuple> >, false, false>; _Predicate = PolicyMap::get_shell_by_policy(unsigned int) const::__lambda0]’
/home/snort3/src/main/policy.h:272:150:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:150:56: error: no match for call to ‘(PolicyMap::get_shell_by_policy(unsigned int) const::__lambda0) (const std::pair<Shell* const, std::shared_ptr<PolicyTuple> >&)’
       while (__first != __last && !bool(__pred(*__first)))
                                                        ^
In file included from /home/snort3/src/detection/rules.h:31:0,
                 from /home/snort3/src/detection/detect.h:24,
                 from /home/snort3/src/actions/actions.cc:25:
/home/snort3/src/main/policy.h:272:78: note: candidate is:
         auto it = std::find_if(std::begin(shell_map), std::end(shell_map), [=](auto&& p) { return p.second->ips and p.second->ips->policy_id == id; });
                                                                              ^
/home/snort3/src/main/policy.h:272:88: note: PolicyMap::get_shell_by_policy(unsigned int) const::__lambda0
         auto it = std::find_if(std::begin(shell_map), std::end(shell_map), [=](auto&& p) { return p.second->ips and p.second->ips->policy_id == id; });

**Comment by snortadmin** [comment]
If you figured out something, please share the solution for others. Thanks.
