### ISSUE TITLE
[Question] Logging int timestamps when using JSON or CSV outputs?

### ISSUE THREAD

**Issue by redbaron4** [snort3/snort3#198]
I am evaluating Snort3 for upgrade from Snort2. Right now we use unified2 output but with that being deprecated, we are looking to move to JSON/CSV as those outputs seem well supported.

While testing I enabled the JSON plugin and saw alerts logged in following format

```
{ "timestamp" : "07/14-17:50:02.758763", "pkt_num" : 4547595114, "proto" : "TCP", "pkt_gen" : "stream_tcp", "pkt_len" : 20061, "dir" : "S2C", "src_ap" : "192.168.0.1:80", "dst_ap" : "192.168.0.2:65494", "rule" : "1:xxxxx:7", "action" : "allow" }
```

The `timestamp` column seems to be using local time as a string. Is it possible to have int timestamps (epoch time) in the output via a configuration switch? If we plan to send data to ELK the int timestamps would be easier to integrate because then we don't have to worry about timezone conversions.

**Comment by snortadmin** [comment]
There is not currently an epoch time field but it would be trivial to implement. However, you can use the -U argument to get UTC timestamps. Would that work?

**Comment by redbaron4** [comment]
> However, you can use the -U argument to get UTC timestamps. Would that work?

Thanks for the tip @snortadmin . Yes that might work. But IMO snort should not be concerned with timezones at all. It should always use UTC (hence timestamps) deferring timezoning to the the programs used to store/visualize alert data. This is followed in `unified2` where snort always outputs timestamps and `barnyard2` is responsible for doing the timezone conversion (if user requires it or even barnyard may output date in UTC and the visualization program handles user timezone conversion). Logstash etc. work well with timestamps so will play nicer if JSON had int timestamps.

The current string format is also missing the year part. That may seem unnecessary but a user could hit an edge case where they try to process 2 year worth of alerts in one go & that would cause year collision.

**Comment by snortadmin** [comment]
There is a year option:

$ snort --help-config | grep year
bool output.show_year = false: include year in timestamp in the alert and log files (same as -y)
implied snort.-y: include year in timestamp in the alert and log files

That will get you YY/MM/DD format.

**Comment by redbaron4** [comment]
Thanks I wan't aware of that!

Maybe outputs can have an additional output field for int timestamps in addtion to the current time field?

**Comment by redbaron4** [comment]
@snortadmin Is there any consensus on this? Other logs written by Snort3 (perfmon, appid) also provide unix timestamps so it would be nice if alert logs also did so. If compatibility with existing versions is an issue maybe alerts logs can provide this as a separate field (say `unix_time`).

**Comment by Crowy-o** [comment]
Thanks for pointing it out, we will take a look

**Comment by redbaron4** [comment]
It seems I was mistaken when opening this issue. Snort config has a `timestamp` option for `fields` setting for the `alert_json` module which logs the UNIX timestamp for the alert.
