### ISSUE TITLE
[Issue] Snort3 code Value::get_uint8/16/32/64() behave differently on x86 and arm platforms for negative Value::num.

### ISSUE THREAD

**Issue by liangxwa01** [snort3/snort3#199]
Considering below code snippet similar as Snort3 Value::get_uint8() usage in src/framework/value.h:

```
double num = -1;
int max_depth = (uint8_t)num;
```

max_depth will be **255** on x86 host, but **0** on arm host.  Value::get_uint16(), Value::get_uint32() and Value::get_uint64() have similar symptom. 

**Note:** if num is defined as int type instead of double in above snippet, then no this issue. 

Snort3 profiler module is one example affected by this divergence.  With below profiler module configuration in Snort3 lua config file, profiler.modules.max_depth is viewed as 255 on x86, where as 0 on arm.

```
profiler = { }
profiler.modules = { sort = 'total_time', }
```

Should this divergence issue be avoided on x86 and arm platforms? Thanks.

**Comment by matirko** [comment]
Hi, thanks for submitting this issue. I've filed a bug, and we will look into it.

**Comment by liangxwa01** [comment]
Thanks @matirko . Looking forward to the fix.

**Comment by snortadmin** [comment]
Hi - you mention a generic problem and a specific one. The specific problem, that profiler.*.max_depth has a range of -1:255 and is cast to a unit8_t, will be fixed. The uint8_t is too small.

As to the generic problem, you are saying that there is a problem with all Value::get_uint*(). Can you provide other specific examples? Can you paste here what you are seeing in a debugger (other than the above problem)?

**Comment by liangxwa01** [comment]
Hi, thanks for asking. The generic problem is actually that casting a negative double value to an unsigned integral type is not a defined behavior by c/c++ standard. This casting behavior did diverge on x86 and arm paltforms.

Consider below code snippet similar with Snort3 Value::get_uint*():

```
        double i = -1;
        printf("%#x ", (uint8_t)i);
        printf("%#x ", (uint16_t)i);
        printf("%#x ", (uint32_t)i);
        printf("%#lx\n", (uint64_t)i);
```
The output is **0xff 0xffff 0xffffffff 0xffffffffffffffff** on x86 host versus **0 0 0 0** on arm host.

Regarding the the specific example, I noticed only profiler.*.max_depth can trigger Value::get_uint8() for -1. Seems no other code path can trigger Value::get_uint16/32/64() for -1.

**Comment by snortadmin** [comment]
OK, so you are referring to this in general:

https://stackoverflow.com/questions/10541200/is-the-behaviour-of-casting-a-negative-double-to-unsigned-int-defined-in-the-c-s

We bumped into that not because we wanted -1 to appear as 255 but because the profiler call to get_uint8 should be get_int16.

Thanks for pointing this out.

**Comment by liangxwa01** [comment]
Thanks for the explanation. As long as Value::get_uint*() is avoided for negative Value::num, that's fine.

**Comment by mjs717** [comment]
Thanks for catching this.
It is addressed in the next release (next week).
