### ISSUE TITLE
Rule File Format Request

### ISSUE THREAD

**Issue by JockDaRock** [snort3/snort3#20]
Anyway you can make the rules files and config files in a JSON or yaml format???  This way it will follow a standard and will be easier to parse rules and configs.

**Comment by snortadmin** [comment]
That's interesting and obviously possible but not something we are designing for:

1.  The rules language has evolved over many years and Snort++ introduces only small tweaks towards uniformity to facilitate more robust parsing and extensibility.  If you can understand a Snort 2.X rule, you can understand a Snort++ rule.  This is basically a defacto industry standard so is not something we want to change.

2.  The config is in Lua (we actually use LuaJIT), which is well documented, simple, and executable.  This supports considerable functionality and flexibility.  It is a huge improvement over the 2.X format and there is considerable command line support to facilitate scriptability.

What exactly is your use case for parsing?  While the rules and conf aren't likely to change much, we may be able to address your concerns with other changes.

**Comment by JockDaRock** [comment]
so here is the use case: I was working on putting a RESTful API in front of snort on a container (using an Alpine container to get the footprint as small as possible).  I am putting in full CRUD functionality for the rules.  I am able to control the snort program just fine through my API.  However, managing snort rules through the rule text files is a little clunky with regex.  I have a document DB I am using to store the rules, when I make changes I obviously need to update both the DB and the rules files.

That being said I am looking to deploy this container on Edge computing resources and was working on as much programmatic control as possible.  would also be ideal to use multiple snort containers to break up the processing of packets through rules in a microservice type of architecture.  Possibilities for this would be to only deploy certain snort containers with specific rules to look for certain traffic on a network only if determined necessary. And to deploy super quickly.  Deploying through the container / microservice allows for great speed.

I have only used snort lightly in the past so there may be some best practices for creating, updating, and deleting snort rules easily I am unaware of.  Please point me in the right direction on that.

Also, I am doing this as a bit of a side project, but I also work for Cisco as part of DevNet.  I think this would also be an interesting story for developers and another reason I am pursuing it.

**Comment by InverseRE** [comment]
Snort3 can dump its configuration in JSON format, and also it is able to read the configuration in JSON format with a little help from LUA library (https://gist.github.com/tylerneylon/59f4bcf316be525b30ab or similar).

Take a look at https://github.com/snort3/snort3_demo/tree/master/tests/dump_config
