### ISSUE TITLE
[Question] ContentData::setup_bm() in ips_content.cc doesn't enable Hyperscan by default?

### ISSUE THREAD

**Issue by liangxwa01** [snort3/snort3#200]
When ContentData::searcher is instantiated in ContentData::setup_bm(), hyperscan is not chosen by default.

```
void ContentData::setup_bm()
{
    const uint8_t* pattern = (const uint8_t*)pmd.pattern_buf;
    searcher = LiteralSearch::instantiate(search_handle, pattern, pmd.pattern_size, pmd.is_no_case());
}
```
Any consideration here to not use hyperscan for ips content single pattern matching? Thanks.

**Comment by snortadmin** [comment]
detection.hyperscan_literals = true takes a little longer to startup but is generally faster. We are planning to enable it in the demo configs, just haven't done so yet. I don't think we'll force it if the search method is hyperscan.

**Comment by liangxwa01** [comment]
Thanks for the info.
