### ISSUE TITLE
[Question] Snort3 cmake --enable-tsc-clock option support for aarch64 

### ISSUE THREAD

**Issue by liangxwa01** [snort3/snort3#201]
I notice Snort3 cmake **--enable-tsc-clock** option can also work well on aarch64 host to improve the snort3 performance. So should below option description in configure_cmake.sh be updated to included arm? Thanks.

   **--enable-tsc-clock      use timestamp counter register clock (x86 only)**

**Comment by snortadmin** [comment]
Good catch. We'll update. Thanks.

**Comment by Xiche** [comment]
configure_cmake.sh help output updated accordingly in a8dd0cd8b2299cb75ecc635797f49d589b76d959 - thanks!
