### ISSUE TITLE
Packet not logging from command line arguments

### ISSUE THREAD

**Issue by prabhat0987** [snort3/snort3#202]
Hello,
I am using Snort 3.1.6.0 on Ubuntu 20.04 .
Packets are not logged to the directory mentioned by `-l` argument instead it shows on console when I give the command - 
`~/Desktop$ sudo snort -c /usr/local/etc/snort/snort.lua -l snort_log/txt_log/ -i ens33 -A alert_fast`
`snort_log/` is in `~/Desktop` directory. I tried with both absolute and relative path of log directory.

But when I specify in `snort.lua` , it log the packet where I want.
```
alert_fast = { 
    file = true,
    packet = false,
    }
```
Why is it not logging when `-l <dir>` is specified as a command line argument?

**Comment by serhii-vlasiuk** [comment]
Hello,
The option -l just configures output path.
It is required to configure alert_fast module if you would like to output into dedicated file.

**Comment by snortadmin** [comment]
In summary, the log directory and whether any given logger use it are two different things.

**Comment by prabhat0987** [comment]
Hi,
I am interested more into how data is acquired and preprocessed, filtered, logged in pcap(or any other formats like csv, json). As soon as a packet reaches the network interface, which modules of snort become active in process mentioned in [snort3x.png](https://github.com/snort3/snort3/blob/master/doc/user/snort3x.png)? Which are the basic modules and plugins that are used in  decoding phase to logging phase?

**Comment by snortadmin** [comment]
This is a general question about Snort 3 and not a development issue (also, you are hijacking a closed thread). Redirect to the snort-users mailer and we can pick up there.
