### ISSUE TITLE
`snort2lua` version outputs also an ERROR.

### ISSUE THREAD

**Issue by A-Pisani** [snort3/snort3#213]
After Installing Snort there is an issue when checking the version of snort2lua executable:
```shell
$ snort2lua -V
Snort2Lua 0.2.0ERROR: Snort configuration file required!!
        Use either '-c' or '--conf-file' option
```

I think the error should be output only when it is run without any CL parameter. It can easily be fixed by adding `exit(0)` [here](https://github.com/snort3/snort3/blob/270295cc76b822ebc7ad46647593dd5d9e077d26/tools/snort2lua/helpers/parse_cmd_line.cc#L280):
```C
static void print_version(const char* /*key*/, const char* /*val*/)
{
    std::cout << "Snort2Lua\t0.2.0";
    exit(0);
}
```

**Comment by snortadmin** [comment]
Thanks for pointing this out and opening a PR. See my comment on the PR and we can follow up there.
