### ISSUE TITLE
Syntax for alert_syslog = { }

### ISSUE THREAD

**Issue by Wajiullah** [snort3/snort3#216]
Hey, can anybody guide me about the syntax to log Syslog to a remote IP in Snort 3.  I tried 

alert_syslog = { host = IP:PORT, LOG_AUTH LOG_ALERT }

but it gives an error.

**Comment by jason51553262** [comment]
An example somewhere would be helpful. 

Snort-users List Archive Search only gives back 404 errors.

**Comment by jason51553262** [comment]
This works for me:
```
alert_syslog =
{
    facility = 'local6',
    level = 'alert',
    options = {'pid', 'ndelay', 'cons', 'perror'}
}
```
