### ISSUE TITLE
Bug:An exception branch handling may cause a memory leak

### ISSUE THREAD

**Issue by coolc4** [snort3/snort3#217]
tools/u2boat/u2boat.cc

static int GetRecord(FILE* input, u2record* rec)
{
。。。
    /* Read in the data portion of the record */
    if (rec->length > buffer_size)
    {
        tmp = (uint8_t*)malloc(rec->length * sizeof(uint8_t));
        if (tmp == nullptr)
        {
            fprintf(stderr, "Error: memory allocation failed.\n");
            return FAILURE;
        }
        else
        {
            if (rec->data != nullptr)
            {
                free(rec->data);
            }
            rec->data = tmp;
            buffer_size = rec->length;
        }
/////////malloc  rec->data
。。。
    }
    items_read = fread(rec->data, sizeof(uint8_t), rec->length, input);
    if (items_read != rec->length)
    {
        fprintf(stderr, "Error: incomplete record. %u of %u bytes read.\n",
            items_read, rec->length);
///////cause the memery leak。
        return FAILURE;
    }
}

**Comment by AnnaNorokh** [comment]
Thank you  @coolc4 for your contribution. Snort3 team will check this issue.

**Comment by AnnaNorokh** [comment]
@coolc4 Investigation result:  there is no actual memory leak. Code is correct.
rec->data would be freed at u2boat.cc:92 even if we will leave GetRecord() at u2boat.cc:229.
