### ISSUE TITLE
no results with "security" policy rules in snort 3

### ISSUE THREAD

**Issue by aziel12** [snort3/snort3#218]
Hello, Im getting with snort no "security related" results. All config seem to be fine. If  I use security policy rules then update with pulledpork3, I get no results. If I use max-detect policy then update with pulledpork3, it will output alot (as expected) results. So where am I be wrong? 

Pcap file:  bigFlows.pcap from http://tcpreplay.appneta.com/wiki/captures.html
cmd: snort -c snort.lua -k none -r bigFlows.pcap --plugin-path=/path_to_so_rules -A alert_fast -s 65535

snort version:
![snort3](https://user-images.githubusercontent.com/87038792/139055003-dd90cd62-3df6-4084-a0c0-8ecc02d51f0b.png)

IPS part from snort.lua
![snort2](https://user-images.githubusercontent.com/87038792/139054849-22adbcba-d419-4533-89ff-64cb4f21c7ee.png)

loaded rules:
![snort](https://user-images.githubusercontent.com/87038792/139054383-6b297d9c-fca9-4808-a0a5-693b7f1711eb.png)

**Comment by aziel12** [comment]
actually issue is still there. 
If I use max-detect, I see expected alerts such as ssh bruteforce, bot checking it's public IP
![snort1](https://user-images.githubusercontent.com/87038792/140093482-9a59b894-78ed-4271-9af5-c52041675eda.png)
If I use policy=security then update rules, snort does not create any rules, both output files are empty
![snort2](https://user-images.githubusercontent.com/87038792/140093701-4526fbb0-54e8-4d04-8987-a8f0f691240b.png)

**Comment by Priyanka-Gurudev** [comment]
Hello,

Are you referring to this rule **sid:19559; rev:14;** in particular? 
If yes, this rule is enabled only in max-detect policy of Talos_LightSPD.

**Comment by aziel12** [comment]
not sure about  sid:19559; rev:14, but anyway with security policy it should output more > 0bytes

**Comment by Priyanka-Gurudev** [comment]
For the pcap bigFlows.pcap, with latest snort and rules/policy published, there are alerts for security policy

_Loading ips.states:
Loading ../../rules/3.0.0.0/rulestates-security-ips.states:
Finished ../../rules/3.0.0.0/rulestates-security-ips.states:
Loading ../../builtins/3.0.0.0-0/rulestates-security-ips.states:
Finished ../../builtins/3.0.0.0-0/rulestates-security-ips.states:
Loading ../../modules/stubs/rulestates-security-ips.states:
Finished ../../modules/stubs/rulestates-security-ips.states:
Finished ips.states:
...
rule counts
       total rules loaded: 46010
               text rules: 42557
            builtin rules: 595
                 so rules: 2858
            option chains: 46010
            chain headers: 25909
...
ips policies rule stats
              id  loaded  shared enabled    file
               0   46010       0   18281    policies/3.1.11.0-0/security-over-connectivity.lua
...
...
Commencing packet processing
++ [0] /home/pcap-dir/bigFlows.pcap
All pthreads started
02/26-22:02:40.393599, 12059, TCP, stream_tcp, 2071, C2S, 172.16.133.41:52672, 199.102.234.31:80, 1:49724:1, block
02/26-22:02:41.831425, 15848, TCP, stream_tcp, 2164, C2S, 172.16.133.41:52688, 199.102.234.31:80, 1:49724:1, block
02/26-22:03:09.742663, 97965, TCP, stream_tcp, 2375, C2S, 172.16.133.41:52776, 199.102.234.31:80, 1:49724:1, block
02/26-22:03:15.952213, 118511, TCP, stream_tcp, 2220, C2S, 172.16.133.41:52785, 199.102.234.31:80, 1:49724:1, block
02/26-22:03:19.247515, 128487, TCP, stream_tcp, 2251, C2S, 172.16.133.41:52923, 199.102.234.31:80, 1:49724:1, block_

**Comment by aziel12** [comment]
two issues identified: 
1)
used with bigFlows.pcap and policy "security" , snort generates alerts => fine
used with 1.8GB.pcap and policy "security", snort generates empty logs.
1.8GB pcap from http://mawi.wide.ad.jp/mawi/samplepoint-F/2021/202110311400.pcap.gz

2) snort3 parsed above 1.8GB pcap file in about 6min40sec with default settings. Is it already using multicore/multithread features of snort3 or do I have enable it somehow? I called snort3 with -z 20 option, but it same amount of time.
