### ISSUE TITLE
snort3.service: Main process exited, code=killed, status=11/SEGV

### ISSUE THREAD

**Issue by a937287837** [snort3/snort3#220]
snort3 version 3.1.6.0
Frequency：twice since 20211102
description：snort  worked normally for two days  but don'know why it quit unexpectedly，if need log，tell me pelase
`11月 04 10:03:30 snort-server snort[7729]:   #0 0x564494a70e94 in _ZN3Ssh4evalEPN5snort6PacketE.cold+0x28 (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #1 0x564494b5cec3 in _ZN5snort16InspectorManager15full_inspectionILb0EEEvPNS_6PacketE+0x63 (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #2 0x564494b5d7c0 in _ZN5snort16InspectorManager16internal_executeILb0EEEvPNS_6PacketE+0x8b0 (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #3 0x564494ac262c in _ZN5snort15DetectionEngine7inspectEPNS_6PacketE+0x6c (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #4 0x564494b3d6e4 in _ZN8Analyzer15inspect_rebuiltEPN5snort6PacketE+0x34 (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #5 0x564494bbeabf in _ZN14TcpReassembler12flush_to_seqER19TcpReassemblerStatejPN5snort6PacketEj+0xbf (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #6 0x564494bc2524 in _ZN10TcpSession13flush_trackerER16TcpStreamTrackerPN5snort6PacketEjb+0x54 (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #7 0x564494bc1179 in _ZN10TcpSession21update_session_on_rstER20TcpSegmentDescriptorb+0x39 (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #8 0x564494bc3658 in _ZN17TcpStateCloseWait8rst_recvER20TcpSegmentDescriptorR16TcpStreamTracker+0x38 (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #9 0x564494bc5680 in _ZN15TcpStateMachine4evalER20TcpSegmentDescriptor+0x90 (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #10 0x564494bc27df in _ZN10TcpSession18process_tcp_packetER20TcpSegmentDescriptorPKN5snort6PacketE+0x1f (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #11 0x564494bc2f9e in _ZN10TcpSession7processEPN5snort6PacketE+0x28e (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #12 0x564494b5d618 in _ZN5snort16InspectorManager16internal_executeILb0EEEvPNS_6PacketE+0x708 (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #13 0x564494ac262c in _ZN5snort15DetectionEngine7inspectEPNS_6PacketE+0x6c (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #14 0x564494b3c5dc in _ZL14process_packetPN5snort6PacketE+0xcc (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #15 0x564494b3d244 in _ZN8Analyzer19process_daq_pkt_msgEPK8_daq_msgb+0xb4 (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #16 0x564494b3d4e8 in _ZN8Analyzer15process_daq_msgEPK8_daq_msgb+0x248 (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #17 0x564494b3e8a6 in _ZN8Analyzer16process_messagesEv+0x1a6 (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #18 0x564494b3ebeb in _ZN8Analyzer7analyzeEv+0x5b (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #19 0x564494b3edb1 in _ZN8AnalyzerclEP7Swappert+0xd1 (/usr/local/bin/snort @0x5644948cf000)
11月 04 10:03:30 snort-server snort[7729]:   #20 0x7fd98a823de4 in _ZNKSt10error_code23default_error_conditionEv+0x34 (/lib/x86_64-linux-gnu/libstdc++.so.6 @0x7fd98a74d000)
11月 04 10:03:30 snort-server snort[7729]:   #21 0x7fd98b003609 in start_thread+0xd9 (/lib/x86_64-linux-gnu/libpthread.so.0 @0x7fd98affa000)
11月 04 10:03:30 snort-server snort[7729]:   #22 0x7fd98a511293 in clone+0x43 (/lib/x86_64-linux-gnu/libc.so.6 @0x7fd98a3ef000)
11月 04 10:03:30 snort-server snort[7729]: = Current DAQ Message (Type 1) =
11月 04 10:03:30 snort-server snort[7729]: == Header (48) ==
11月 04 10:03:30 snort-server snort[7729]: 723f 8361 0000 0000 5b06 0900 0000 0000
11月 04 10:03:30 snort-server snort[7729]: 4000 0000 ffff ffff ffff ffff ffff ffff
11月 04 10:03:30 snort-server snort[7729]: 0000 0000 0000 0000 0000 0000 0000 0000
11月 04 10:03:30 snort-server snort[7729]: == Data (64) ==
11月 04 10:03:30 snort-server snort[7729]: 707b e876 9da9 18c0 4dfb 23b4 8100 0012
11月 04 10:03:30 snort-server snort[7729]: 0800 4500 0028 a315 4000 8006 c6ef c0a8
11月 04 10:03:30 snort-server snort[7729]: 0f78 c0a8 0002 f4e6 0016 ff0c 21f8 de53
11月 04 10:03:30 snort-server snort[7729]: 1832 5014 0000 127e 0000 0000 0000 0000
11月 04 10:03:31 snort-server systemd[1]: snort3.service: Main process exited, code=killed, status=11/SEGV
11月 04 10:03:31 snort-server systemd[1]: snort3.service: Failed with result 'signal'.
`

**Comment by Crowy-o** [comment]
Thank you for your report.
We'll take a look!

**Comment by Crowy-o** [comment]
Hello @a937287837.

Can you send your core files and some recorded traffic?
Also can you share information about your snort's dependencies like what is included and their versions.

Information about your OS can help as well!

**Comment by a937287837** [comment]
> Hello @a937287837.
> 
> Can you send your core files and some recorded traffic? Also can you share information about your snort's dependencies like what is included and their versions.
> 
> Information about your OS can help as well!

update 3.3.1.16.0, so far it's work ok，if happes again，i will reopened the issue

**Comment by Crowy-o** [comment]
Can you still give information about your OS and dependencies information (about daq, dnet and etc.)?
Information (records or just protocols in it) about traffic can help

**Comment by a937287837** [comment]
> @a937287837
> 
> Can you still give information about your OS and dependencies information (about daq, dnet and etc.)? Information (records or just protocols in it) about traffic can help
   ,,_     -*> Snort++ <*-
  o"  )~   Version 3.1.16.0
   ''''    By Martin Roesch & The Snort Team
           http://snort.org/contact#team
           Copyright (C) 2014-2021 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using DAQ version 3.0.5
           Using LuaJIT version 2.1.0-beta3
           Using OpenSSL 1.1.1f  31 Mar 2020
           Using libpcap version 1.9.1 (with TPACKET_V3)
           Using PCRE version 8.45 2021-06-15
           Using ZLIB version 1.2.11
           Using FlatBuffers 2.0.0
           Using Hyperscan version 5.4.0 2021-11-01
           Using LZMA version 5.2.4
