### ISSUE TITLE
snort3 multithreading

### ISSUE THREAD

**Issue by aziel12** [snort3/snort3#221]
Hello, does snort3 with default settings work in multithread? Im testing 
1.8GB pcap from http://mawi.wide.ad.jp/mawi/samplepoint-F/2021/202110311400.pcap.gz

snort3 parsed above 1.8GB pcap file in about 6min40sec with default settings. Is it already using multicore/multithread features of snort3 or do I have enable it somehow? I called snort3 with -z 20 option, but it took same amount of time.

**Comment by snortadmin** [comment]
The above comment re -z N not correct. -z N will enable N packet threads, but by default a single pcap goes to only one thread. If you want to give the same pcap to all N threads, you must also add --pcap-loop N. Being picky here, but it doesn't literally assign a copy of the file in the --pcap-loop case. It just opens the same file N times.

Snort does not yet do internal load balancing so it won't split the pcap across multiple packet threads to speed up processing. But if you had multiple pcaps (and don't use --pcap-loop) they will be assigned to the next available packet thread and processed in parallel.
