### ISSUE TITLE
Snort3 Performance

### ISSUE THREAD

**Issue by AqsaKashaf** [snort3/snort3#223]
Hi,

I am trying to profile snort3 in IPS mode with af_packet. I noticed that when I stress the system by sending large number of packets, the processing time of snort3 goes down. I am not sure why that is happening. I am running snort3 with just one thread. I am using only one rule that tracks the number of tcp syns per source. I am sending packets with just one source ip.

I will really appreciate nay help.

**Comment by nihdeflow** [comment]
Hello,

Thank you for reporting this. Few questions.

Can you please explain your use case here? Are you comparing your results against previous runs, and if so, can you please share results here? And how are you determining that process time of snort3 goes down? Is it always same type of traffic and same number of packets with same config/rules?

Can we get copy of your config/rules and sample traffic?

What version of snort are you running?

Thanks!

**Comment by InverseRE** [comment]
For the described conditions, one can expect Snort processing time going down.
Other parts of the system (say, some logging is enabled) start consuming CPU time, leaving less for Snort itself.

**Comment by InverseRE** [comment]
Feel free to reopen the issue if you still have questions.
