### ISSUE TITLE
How to compile snort into a library 

### ISSUE THREAD

**Issue by FirsthandSage** [snort3/snort3#228]
Hi,

I only want to use the rule matching and Threat Intelligence matching functions of snort3, I hope to compile snort3 to a library and add it to my project.What should I do?

I will really appreciate nay help.

**Comment by snortadmin** [comment]
Snort 3 is an application. If you want to convert it into a library, you'll need to fork and start hacking away to eliminate main and so on. There is much infrastructure required to get the functionality you want so it might be easier to invert your strategy and embed the functionality of your project into Snort 3 plugins or other hooks you add. Good luck.
