### ISSUE TITLE
how to use jemalloc

### ISSUE THREAD

**Issue by a937287837** [snort3/snort3#231]
Snort v3.1.18.0 add support for jemalloc
./configure_cmake.sh --prefix=/usr/local --enable-jemalloc
but not work
`/home/snort/snort3-3.1.18.0/src/memory/memory_cap.cc:32:10: fatal error: jemalloc/jemalloc.h: No such file or directory
 #include <jemalloc/jemalloc.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.`
how can i do use  jemalloc

update
i try install jemalloc
and ./configure_cmake.sh --prefix=/usr/local --enable-jemalloc --enable-tcmalloc
seems works

**Comment by a937287837** [comment]
update
i try install jemalloc
and ./configure_cmake.sh --prefix=/usr/local --enable-jemalloc --enable-tcmalloc
seems work

**Comment by snortadmin** [comment]
That most likely just got you tcmalloc. Those options are intended to be mutually exclusive. What does this show?

$ ldd <snort_binary> | grep malloc

Did you set PKG_CONFIG_PATH?

**Comment by a937287837** [comment]
> That most likely just got you tcmalloc. Those options are intended to be mutually exclusive. What does this show?
> 
> $ ldd <snort_binary> | grep malloc
> 
> Did you set PKG_CONFIG_PATH?
        


        ldd /usr/local/bin/snort | grep malloc
        libtcmalloc.so.4 => /usr/local/lib/libtcmalloc.so.4 (0x00007fced821f000)
        libjemalloc.so.2 => /usr/local/lib/libjemalloc.so.2 (0x00007fced7f76000)

**Comment by snortadmin** [comment]
Oof. That's not good. Still not clear why you needed to --enable both.

So, what is your PKG_CONFIG_PATH set to?

**Comment by a937287837** [comment]
Use the default 
i will try only jemalloc
./configure_cmake.sh --prefix=/usr/local --enable-jemalloc

**Comment by a937287837** [comment]
--enable-jemalloc memory is less than --enable-tcmalloc，before --enable-jemalloc system Memory gradually increases until the system goes down，--enable-jemalloc system Memory seems ok

Snort v3.1.18.0 ./configure_cmake.sh --prefix=/usr/local  --enable-jemalloc --enable-tcmalloc
`kbmemfree   kbavail kbmemused  %memused kbbuffers  kbcached  kbcommit   %commit  kbactive   kbinact   kbdirty
07时05分01秒   5246344  13907804   1938936     11.89    583756   7986016   4416040      9.29   2044876   8299676      2784
07时15分01秒   4922196  13622724   2223804     13.64    585948   8021212   4629032      9.73   2048008   8615956       924
07时25分01秒   5182712  13911908   1934640     11.87    587908   8046448   4890152     10.28   2050644   8350860      5792
07时35分01秒   4296560  13065956   2780604     17.05    589844   8083192   5163560     10.86   2054140   9233740       912
07时45分01秒   3725652  12550616   3295880     20.21    592296   8134368   5807656     12.21   2067392   9784928      1360
07时55分01秒   2788268  11677288   4168932     25.57    594252   8194396   6618148     13.92   2071924  10713432      8488
08时05分01秒   1922364  10905384   4940768     30.30    596212   8282460   7278120     15.30   2076204  11568440      3928
08时15分01秒    307820   9528772   6316424     38.74    598460   8509036   8966696     18.85   2302712  12946908      1532
08时25分01秒    704012   9271296   6574132     40.32    588448   7872192   9488936     19.95   2503416  12353844      7040
08时35分01秒    184684   8691168   7153588     43.87    588172   7815984   9527724     20.03   2431216  12948488     23904
08时45分01秒    402572   8447124   7398264     45.37    587800   7355624   9766976     20.54   2363284  12805444      8368
08时55分01秒    475644   8556156   7289252     44.71    585980   7394432  10245184     21.54   2358584  12742008     17400
09时05分01秒    597220   8282724   7562180     46.38    573248   7012180  10512448     22.10   2219300  12747264      5784
09时15分01秒    193264   7748184   8096728     49.66    568300   6885040  10520640     22.12   2139376  13236884     11260
09时25分01秒    650060   7731336   8113608     49.76    567176   6413328  10520640     22.12   2085820  12832052      6532
09时35分01秒   1007304   8268052   7577108     46.47    569324   6588872  10552384     22.19   2115292  12444488      6568
09时45分01秒    161800   7508984   8336496     51.13    569224   6674008  10685504     22.47   2109728  13294756     17208
09时55分01秒    182576   7559668   8285856     50.82    568200   6703548  10685504     22.47   2115716  13263292     24596
10时05分01秒    252008   7547692   8297932     50.89    561988   6628976  10839104     22.79   2119572  13189588     18552
10时15分01秒    550272   7794768   8050520     49.37    559384   6583484  10847296     22.81   2077860  12937552      4080
10时25分01秒    170212   7366200   8479348     52.00    556848   6541000  10855488     22.83   2097744  13302184      9188
10时35分01秒    519848   7357908   8487168     52.05    557916   6183148  10855488     22.83   2094104  12957536      5756
10时45分01秒    610052   7551896   8293416     50.86    556008   6293640  11183168     23.51   2131200  12830028      9372
10时55分01秒    158112   7063252   8782280     53.86    556388   6259020  11185216     23.52   2006044  13418968    149248
11时05分01秒    176000   5192852  10652984     65.34    507644   4506836  13035648     27.41   1784656  13703472     14388
11时15分01秒    184808   4837132  11008376     67.51    491128   4178480  13399168     28.17   1773192  13725452      4148
11时25分01秒    188372   4831428  11014404     67.55    490000   4175960  13415708     28.21   1842920  13664908      6444
11时35分01秒    502876   5219728  10625708     65.17    484340   4262520  13415644     28.21   1831320  13360676     14356
11时45分01秒    200604   4805252  11040168     67.71    475380   4161948  13415644     28.21   1707992  13789820      5304
11时55分01秒    178244   4849812  10995528     67.44    469352   4236020  13415644     28.21   1683800  13846316      7604
`

Snort v3.1.20.0 ./configure_cmake.sh --prefix=/usr/local  --enable-jemalloc
`00时00分01秒 kbmemfree   kbavail kbmemused  %memused kbbuffers  kbcached  kbcommit   %commit  kbactive   kbinact   kbdirty
00时05分01秒   2450140  10373316   5471868     33.56    362704   7525624   3619176      7.61   1758248  11413084      2536
00时15分01秒   2150364  10127984   5717080     35.06    364884   7575304   3637608      7.65   1762684  11707460      3388
00时25分01秒   2456476  10462020   5383408     33.02    366988   7599100   3637608      7.65   1766416  11399712      1200
00时35分01秒   2588796  10617732   5227344     32.06    369028   7618604   3595496      7.56   1767324  11260496      1360
00时45分01秒   2072240  10137392   5707600     35.00    371196   7650356   3637608      7.65   1773832  11768048      1468
00时55分01秒   3035808  11128704   4716584     28.93    373308   7674032   3637608      7.65   1777912  10802772      2556
01时05分01秒   3340756  11460172   4384988     26.89    375480   7696528   3595496      7.56   1781456  10489372      2672
01时15分01秒   2891764  11042288   4802992     29.46    377636   7723268   3637608      7.65   1785924  10933644       632
01时25分01秒   3545584  11702752   4142412     25.41    379748   7724508   3637608      7.65   1789268  10273900      2792
01时35分01秒   3889156  12072552   3772744     23.14    381824   7747576   3595496      7.56   1792764   9921912       944
01时45分01秒   3330512  11542188   4302832     26.39    384040   7771960   3637608      7.65   1798404  10475628      1248
01时55分01秒   3666960  11902232   3943080     24.18    386056   7792300   3637608      7.65   1801464  10133132      3556
02时05分01秒   4044528  12303916   3541360     21.72    388080   7813024   3619176      7.61   1802952   9754068      1404
02时15分01秒   4066148  12362700   3481820     21.35    390156   7846396   3686448      7.75   1808764   9720316      7912
02时25分01秒   3938876  12256372   3588112     22.01    392220   7863612   3683304      7.74   1811728   9846428      3628
02时35分01秒   4189740  12527568   3317172     20.34    394172   7880184   3663720      7.70   1814664   9589028       280
02时45分01秒   3683660  12047520   3797676     23.29    396216   7902400   3683304      7.74   1818120  10092044      2376
02时55分01秒   4127904  12669560   3175116     19.47    399560   8074932   3683304      7.74   1857100   9607536       780
03时05分01秒   4072584  12734520   3110316     19.08    401976   8189940   3695452      7.77   1935236   9580292     10752
03时15分01秒   3605212  12277704   3567256     21.88    404140   8197104   3683304      7.74   1937140  10042972       760
03时25分01秒   3497396  12213016   3632028     22.28    406212   8236224   3683304      7.74   1940276  10147340      3044
03时35分01秒   3474780  12222796   3622256     22.22    408280   8264424   3683304      7.74   1943376  10164552      2180
03时45分01秒   3419740  12191396   3653488     22.41    410320   8284420   3683304      7.74   1946268  10214516      1656
03时55分01秒   3409636  12205012   3639808     22.32    412332   8304452   3683304      7.74   1949048  10223636      1488
04时05分01秒   3675216  12493592   3351040     20.55    414540   8323664   3683304      7.74   1996076   9906848      2788
04时15分01秒   3888220  12732204   3113056     19.09    416536   8345544   3637608      7.65   2000436   9689648      1804
04时25分01秒   3935532  12799112   3046096     18.68    418544   8361396   3637608      7.65   2003524   9638388      2848
04时35分01秒   3926688  12815072   3030316     18.59    420584   8382404   3629416      7.63   2006576   9642284      1368
04时45分01秒   3916668  12826328   3018944     18.52    422580   8400348   3629416      7.63   2009284   9645664      1076
04时55分01秒   3878336  12803424   3042180     18.66    424708   8411536   3659988      7.70   2026528   9664660     11500
05时05分01秒   3284052  12227200   3618036     22.19    426708   8426084   3637608      7.65   2029196  10255660      3028
05时15分01秒   3804664  12782064   3062948     18.79    428744   8456448   3629416      7.63   2031948   9727908      3736
05时25分01秒   3807172  12820560   3024536     18.55    430728   8488644   3654684      7.68   2035136   9720452     13556
05时35分01秒   3154604  12182524   3662112     22.46    432732   8499608   3637608      7.65   2038192  10372176      1420
05时45分01秒   3739812  12786908   3057920     18.75    434788   8515176   3619176      7.61   2038152   9784968       488
05时55分01秒   3051368  12143744   3700976     22.70    436820   8556092   3638180      7.65   2044004  10461892      2672
06时05分01秒   3144748  12258852   3585544     21.99    438796   8574128   3637608      7.65   2046852  10369028       628
06时15分01秒   3594104  12729868   3114544     19.10    440944   8592000   3629416      7.63   2047156   9916600      6492
06时25分01秒   3548252  12716512   3127676     19.18    443088   8620548   3643048      7.66   2050552   9951632     11492
06时35分01秒   3418340  12736788   3107084     19.06    445332   8762880   3637608      7.65   2050556  10080988       476
06时45分01秒   3389784  12753764   3089956     18.95    447528   8804828   3658060      7.69   2054336  10100176     13012
06时55分01秒   2853908  12235796   3607564     22.13    449940   8818480   3637608      7.65   2056496  10631644       560
07时05分01秒   3315340  12726416   3116624     19.11    452388   8843328   3637608      7.65   2061156  10166148       700
07时15分01秒   2661940  12103460   3739836     22.94    454976   8869584   3638896      7.65   2065016  10811604      6936
07时25分01秒   2346528  11822852   4020208     24.66    457308   8899916   3637608      7.65   2068124  11124192      2780
07时35分01秒   2816276  12345648   3497232     21.45    459452   8948312   3637944      7.65   2071380  10648112      5196
07时45分01秒   2565688  12213148   3629284     22.26    461676   9060312   3662016      7.70   2084288  10879096     15788
07时55分01秒   1707140  11388060   4454112     27.32    463724   9089372   3637608      7.65   2082616  11738240      5772
08时05分01秒   1890980  11617648   4224212     25.91    465752   9130444   3641388      7.66   2092376  11543560      5620
`

conclusion： jemalloc is much better memory use in my machine
@ snortadmin
