### ISSUE TITLE
can't find fild_id errors

### ISSUE THREAD

**Issue by Warter21** [snort3/snort3#234]
Hi,

I got this error message with the latest 2 versions (3.1.21.0 and 3.1.22.0) but it is working fine before (version =<3.1.20.0.)

ERROR: /etc/snort/snort.lua: can't find file_id.file_policy
ERROR: /etc/snort/snort.lua: can't find file_id.enable_signature
ERROR: /etc/snort/snort.lua: can't find file_id.enable_type

snort.lua config:
file_id =
{
    enable_type = true,
    enable_signature = true,
    file_rules = file_magic,
    file_policy =
    {
        { use = { verdict = 'log', enable_file_type = true, enable_file_signature = true } }
    }
}

Any advice appreciated.

Thanks,
Warter

**Comment by Priyanka-Gurudev** [comment]
file_policy is moved out of file_id.
enable_type, enable_signature and enable_capture moved from file_id to file_policy. 
Please use documentation or --help-module or --help-config for file_id or file_policy for further details.

**Comment by Warter21** [comment]
Thanks a lot!
