### ISSUE TITLE
Snort3 on Windows

### ISSUE THREAD

**Issue by mihdim777** [snort3/snort3#237]
Hello!

I'd like to find out if there is any date on the roadmap for Windows release of Snort 3?

Thank you!

**Comment by snortadmin** [comment]
We are getting close to a release for Windows but no official timeline as of yet unfortunately.

**Comment by celevra** [comment]
Any news on this?

**Comment by Priyanka-Gurudev** [comment]
The work is in-progress. We will be publishing the windows support as soon as it is available.
