### ISSUE TITLE
block AppID

### ISSUE THREAD

**Issue by TobRein** [snort3/snort3#239]
Hello,

I use snort in inline mode and some rules are blocking the "googlebot"
Here the rules:

22/04/08-13:33:17.129543 [block] [**] [1:2015529:2] "ET INFO Googlebot User-Agent Outbound (likely malicious)" [**] [Classification: Potentially Bad Traffic] [Priority: 2] [AppID: Googlebot] {TCP} 66.249.75.247:61624 -> 172.17.190.13:80
22/04/08-13:33:17.129543 [block] [**] [1:1852:11] "SERVER-WEBAPP robots.txt access" [**] [Classification: Access to a potentially vulnerable web application] [Priority: 2] [AppID: Googlebot] {TCP} 66.249.75.247:61624 -> 172.17.190.13:80
22/04/08-13:33:17.129543 [block] [**] [1:2003394:9] "ET USER_AGENTS User Agent Containing http Suspicious - Likely Spyware/Trojan" [**] [Classification: A Network Trojan was detected] [Priority: 1] [AppID: Googlebot] {TCP} 66.249.75.247:61624 -> 172.17.190.13:80

It is possible to whitelist the rules via OpenAppID in the whitelist.conf file ?

Best regards
T. Reineck

**Comment by finchy** [comment]
Well:
I would recommend setting your HOME_NET variable in your snort.conf file.
