### ISSUE TITLE
Snort security bugs report

### ISSUE THREAD

**Issue by 1ncande5cence** [snort3/snort3#240]
Hi! I reported a snort security bug which could bypass http rules through bugs@snort.org two weeks ago. I haven't received any news back. So did you get the emails? Cause I find several more and I am not sure reporting to bugs@snort.org is the correct way. Thanks !

**Comment by snortadmin** [comment]
I don't see any email from you other than this github issue. I get bugs@snort.org. Resend please.

**Comment by 1ncande5cence** [comment]
I send it with my another email account. The email title begins with "Security Bugs: Bypass of Payload Detection on..." . Thanks !

**Comment by snortadmin** [comment]
Got it thanks. We can leave this open and answer back here.

**Comment by snortadmin** [comment]
Actually, let's stick to the bugs mailer for now.

Thanks
