### ISSUE TITLE
How can I fix this error on centos 8 ?

### ISSUE THREAD

**Issue by susl16c** [snort3/snort3#242]
Finished /usr/local/snort/etc/snort/snort.lua:
--------------------------------------------------
ERROR: Could not find requested DAQ module: pcap

**Comment by VytalyGorbatov** [comment]
@susl16c 
Hi, you can add the `--daq-dir` flag to your Snort startup line. It will look something like this:
`snort --daq-dir <libdaq_path>/lib/daq ...`
