### ISSUE TITLE
The performance about snort

### ISSUE THREAD

**Issue by Natruel** [snort3/snort3#247]
The description about environment：
（1）	Two virutal machines：Both of them are ubuntu 16.04 LTS
（2）	Snort：2.9.19

The description about two VMs：
The two VMS are connected to the host using NAT. So they are on the same LAN.The first VM，called VM1，is equipped with a snort and its IP is 192.168.191.137. The second VM is  called VM2 and its IP is 192.168.191.140. Both of them is equipped with the telnet service.

The description about problem：
I want to detect the telnet connection from the VM1 to VM2 by using the snort. And I write the local rule, as follows:

alert tcp 192.168.191.137/32 any -> 192.168.191.140/32 23 (msg:"rules 2 "; sid:10000001;)

It dosen’t work. So I try other rules to achieve the goal:

alert tcp 192.168.191.137/32 any -> 192.168.191.140/32 any (msg:"rules 2 "; sid:10000001;)
alert tcp 192.168.191.137/32 any -> 192.168.191.0/24 any (msg:"rules 2 "; sid:10000001;)

But both of them don’t work. And I continue to try the rules:

alert tcp 192.168.191.140/32 any -> 192.168.191.137/32 any (msg:"rules 2 "; sid:10000001;)
alert tcp 192.168.191.0/24 any -> 192.168.191.137/32 any (msg:"rules 2 "; sid:10000001;)

And they work. After that I try the rule:

alert tcp 192.168.191.137/32 any -> ![192.168.191.0/24] any (msg:"rules1"; sid:10000002;)

It means that I want to detect the TCP connection from VM1 to the host which is not in the same LAN with VM1. And it still works. 

Note that when I try, the local.rules only contains one rule which means I test the above mentioned rules by turns. Therefore, there doesn’t exist the confilct between the rules. And when I test the rule:

alert tcp 192.168.191.137/32 any -> 192.168.191.0/24 any (msg:"rules 2 "; sid:10000001;)

I can see the data package by using the snort. But I can’t see the alert. That’s so weird and I want to know why.

Ps：I also test the rule on kali 2022.1, but it still dosen’t work.
PPs: I find the rules:

alert tcp 192.168.191.137/32 any -> 192.168.191.140/32 any (msg:"rules 2 "; sid:10000001;)
alert tcp 192.168.191.140/32 any -> 192.168.191.137/32 any (msg:"rules 2 "; sid:10000001;)

There is no difference between the two rules. Because a TCP connection requires a three-way handshake. So no matter who initiates the TCP connection, the two will exchange TCP packets. In fact, even though I only wrote the following rule:

alert tcp 192.168.191.140/32 any -> 192.168.191.137/32 any (msg:"rules 2 "; sid:10000001;)

And I used VM1(192.168.191.137 ) to initiate a Telnet connection with VM2(192.168.191.140). I find the snort still has the alert.

**Comment by snortadmin** [comment]
Thanks. Please direct user questions to the snort-users list. Include a pcap of your traffic otherwise we can't determine which rules should fire.

https://lists.snort.org/mailman/listinfo/snort-users
