### ISSUE TITLE
[Question / installation problem] CMake Error: The following variables are used in this project, but they are set to NOTFOUND

### ISSUE THREAD

**Issue by DalekDave** [snort3/snort3#249]
Hi I'm trying to install snort3 (snort version 3.1.29.0) on Ubuntu 20.04 following the instructions in https://linoxide.com/install-snort-on-ubuntu/

All goes well until I get to step 3 / sub-step 3.  When I try to execute:

./configure_cmake.sh --prefix=/usr/local --enable-tcmalloc

it fails with the error message:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FLEX_INCLUDES (ADVANCED)
   used as include directory in directory /root/snort-source-files/snort3/src
   used as include directory in directory /root/snort-source-files/snort3/src
   used as include directory in directory /root/snort-source-files/snort3/src
   used as include directory in directory /root/snort-source-files/snort3/src
   used as include directory in directory /root/snort-source-files/snort3/src
   used as include directory in directory /root/snort-source-files/snort3/src
  ...
  ......

```
Would you have any suggestions how I can get past this error, please?

And thanks for your work on Snort! :)

**Comment by VytalyGorbatov** [comment]
Hi @DalekDave!
It seems like your machine lacks Flex. You can check this with `apt list --installed | grep flex` or `which flex`. If output is empty install flex with `apt install flex`.

**Comment by DalekDave** [comment]
Hello Vytaly,

Thanks for your reply. I do seem to have flex installed. The output from 'apt list --installed | grep flex' results in :

flex/focal,focal,now 2.6.4-6.2 amd64 [installed]

Would you have any other ideas per chance?

With all best wishes,

Dave

**Comment by snortadmin** [comment]
Did you get this fixed? It looks like you need to configure with --with-flex-prefix and/or --with-flex-includes.

**Comment by thrull** [comment]
FlexLexer.h check failed, on Ubuntu 20.04 You need to install libfl-dev

apt install libfl-dev

**Comment by InverseRE** [comment]
Please, feel free to re-open if the issue still persists.
