### ISSUE TITLE
Snort not block alert

### ISSUE THREAD

**Issue by y-shevchenko** [snort3/snort3#252]
I am using snort Version 3.1.17.0
My rules are in local.rules
alert icmp any any -> any any ( msg:"ICMP Traffic Detected"; sid:10000001; metadata:policy security-ips reject; )
I get an alert but the ping continues to work

Why isn't blocking happening?

**Comment by allewi** [comment]
Is snort inline? Is the rule set to drop/block?

Albert Lewis
ENGINEER.SOFTWARE ENGINEERING
Cisco Systems Inc.
Email: ***@***.******@***.***>



From: y-shevchenko ***@***.***>
Reply-To: snort3/snort3 ***@***.***>
Date: Saturday, May 21, 2022 at 8:42 AM
To: snort3/snort3 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [snort3/snort3] Snort not block alert (Issue #252)


I am using snort Version 3.1.17.0
My rules are in local.rules
alert icmp any any -> any any ( msg:"ICMP Traffic Detected"; sid:10000001; metadata:policy security-ips reject; )
I get an alert but the ping continues to work

Why isn't blocking happening?

**Comment by y-shevchenko** [comment]
/usr/local/etc/snort/snort.lua
```ips =
{
    mode="inline",
    -- use this to enable decoder and inspector alerts
    --enable_builtin_rules = true,

    -- use include for rules files; be sure to set your path
    -- note that rules files can include other rules files
    -- (see also related path vars at the top of snort_defaults.lua)

--    variables = default_variables
--    enable_builtin_rules = true,
    include = RULE_PATH .. "/local.rules",
    variables = default_variables
}
```
start in console
`snort -c /usr/local/etc/snort/snort.lua -i eth0 -Q -A alert_fast`

/usr/local/etc/rules/local.rules
`reject icmp any any -> any any (itype:8; detection_filter:track by_src, count 1, seconds 5; sid:100121;)`

Here are the settings, everything is correct?

**Comment by snortadmin** [comment]
Snort does not send ICMP messages in response to ICMP messages per RFC 792.

This issue tracker is meant for bug reports and feature enhancement requests. For general questions and discussions about Snort usage, please use the Snort-Users mailing list. For discussion about Snort code development, use the Snort-Devel mailing list. Information about the mailing lists can be found here: https://snort.org/community#mailing_lists. There is also a Snort Discord server available here for more interactive discussion: https://discord.com/invite/Sdgsg8MtQQ.

**Comment by y-shevchenko** [comment]
https://discord.com/invite/Sdgsg8MtQQ. not work
