### ISSUE TITLE
PCRE2 support

### ISSUE THREAD

**Issue by istiak101** [snort3/snort3#254]
PCRE is currently EOL(https://www.pcre.org/) and many projects moving to PCRE2 library. Many distros will slowly remove older PCRE library from their distribution. Is there any plan to support the newer PCRE2 library in Snort?

https://github.com/PCRE2Project/pcre2/releases

**Comment by snortadmin** [comment]
And that didn't happen. There is always *this* year.

**Comment by Neustradamus** [comment]
@snortadmin, @bsachdev18, @davism-cisco: In 2022, it was announced that PCRE2 will be supported.

We are in 2024, any news on it?

Thanks in advance.

Linked to:
- https://github.com/snort3/snort3/pull/326
- https://github.com/snort3/snort3/issues/301
- https://github.com/chimera-linux/cports/pull/2912
- https://github.com/openwrt/packages/issues/22006
- ...

cc: @Ansuel, @matirko, @graysky2, @xxxx81, @i3roly, @VytalyGorbatov, @MiShtaz, @crza, @BKPepe, @rbgarga.

**Comment by rbgarga** [comment]
@istiak101 I don't see any commits of pcre2 implementation, was this issue closed by mistake?

**Comment by Neustradamus** [comment]
@istiak101: Yes I think there is a mistake, can you reopen this ticket?

**Comment by rbgarga** [comment]
> @istiak101: Yes I think there is a mistake, can you reopen this ticket?

unfortunately I can't but certainly someone can cc: @snortadmin
