### ISSUE TITLE
Feature Request: IEEE 802.1ad - QinQ Codec

### ISSUE THREAD

**Issue by ozkankirik** [snort3/snort3#260]
Snort3, cannot match packets which have double tagged vlans.
Is there any plan to develop IEEE 802.1ad - QinQ Codec?
Thanks, regards

**Comment by snortadmin** [comment]
Snort can decode multiple vlan tags with the existing vlan codec. Send a pcap and the relevant config that doesn't match.

**Comment by ozkankirik** [comment]
Hello, 

Thank you, you're right. But as you can see from the URL below., many switch vendors supports setting custom ether_types for QinQ packets.

http://www.h3c.com/en/Support/Resource_Center/Technical_Documents/Home/Switches/00-Public/Configure/Configuration_Guides/H3C_S5130S-SI[LI]_S5120V2-SI[LI]_CG-R612x-6W102/03/201909/1228011_294551_0.htm

For solution, is it possible to configure the codec module, to get supported ether_types for QinQ frames from lua ?

Regards

**Comment by snortadmin** [comment]
Yes, that can be done. Do you have such a pcap?

**Comment by ozkankirik** [comment]
Hello, 

Yes the pcap could be downloaded from https://drive.google.com/file/d/1Q8mOgF3aG5Mod4rpCYZ-nafw-AYd-0DQ/view?usp=sharing

The pcap contains 4 packets:
- 1st Packet:
  - DST: 00 1b d4 1b a4 d8 SRC: 00 13 c3 df ae 18 ETH_TYPE: 0x8200 VLANID: 0x0076 (118)
  - NEXT ETH_TYPE 0x8100 VLANID: 0x000a (10)
  - NEXT ETH_TYPE 0x0800 SRC: 10.118.10.1 DST: 10.118.10.2
  - PROTO: ICMP
- 2nd packet is ICMP reply of 1st packet
- 3rd and 4th ones are the same of 1st and 2nd packets.

If we can add custom eth_types (like 0x8200) in addition to 0x8100, 0x88A8 it'll work.

Regards

**Comment by snortadmin** [comment]
This was fixed in 2022-08-25: 3.1.40.0 (dc77923a7) with the addition of this parameter:

int_list vlan.extra_tpid_ether_types = '0x9100 0x9200': set non-standard QinQ ether types { 65535 }

Sorry we didn't close the loop here sooner!
