### ISSUE TITLE
DAQ Errors

### ISSUE THREAD

**Issue by raging-loon** [snort3/snort3#264]
I am having a strange error with DAQ. 
On an Ubuntu 22.04 VM, I'm trying to build snort from the source found on the website. I have successfully built Snort, LibDAQ, libpcap, hwloc, and LuaJIT. I've also installed other various packages such as libdnet. 

The build was successful, and I can get version info by running `snort -V` which produces this:
<pre>   ,,_     -*&gt; Snort++ &lt;*-
  o&quot;  )~   Version 3.1.36.0
   &apos;&apos;&apos;&apos;    By Martin Roesch &amp; The Snort Team
           http://snort.org/contact#team
           Copyright (C) 2014-2022 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using DAQ version 3.0.9
           Using LuaJIT version 2.1.0-beta3
           Using OpenSSL 3.0.2 15 Mar 2022
           Using libpcap version 1.10.1 (with TPACKET_V3)
           Using PCRE version 8.39 2016-06-14
           Using ZLIB version 1.2.11
</pre>
However, when I try to capture some packets or even just try to verify the config file with `snort -c /usr/local/etc/snort/snort.lua -T` I get this message:
<pre>--------------------------------------------------
search engine
--------------------------------------------------
afpacket (1): Failed to register static DAQ module.
afpacket (2): Failed to register static DAQ module.
afpacket (3): Failed to register static DAQ module.
afpacket (4): Failed to register static DAQ module.
afpacket (5): Failed to register static DAQ module.
afpacket (6): Failed to register static DAQ module.
afpacket (7): Failed to register static DAQ module.
fst (9): Failed to register static DAQ module.
fst (10): Failed to register static DAQ module.
fst (11): Failed to register static DAQ module.
fst (12): Failed to register static DAQ module.
fst (13): Failed to register static DAQ module.
fst (14): Failed to register static DAQ module.
fst (15): Failed to register static DAQ module.
gwlb (17): Failed to register static DAQ module.
gwlb (18): Failed to register static DAQ module.
gwlb (19): Failed to register static DAQ module.
gwlb (20): Failed to register static DAQ module.
gwlb (21): Failed to register static DAQ module.
gwlb (22): Failed to register static DAQ module.
gwlb (23): Failed to register static DAQ module.
savefile (25): Failed to register static DAQ module.
savefile (26): Failed to register static DAQ module.
savefile (27): Failed to register static DAQ module.
savefile (28): Failed to register static DAQ module.
savefile (29): Failed to register static DAQ module.
savefile (30): Failed to register static DAQ module.
savefile (31): Failed to register static DAQ module.
trace (33): Failed to register static DAQ module.
trace (34): Failed to register static DAQ module.
trace (35): Failed to register static DAQ module.
trace (36): Failed to register static DAQ module.
trace (37): Failed to register static DAQ module.
trace (38): Failed to register static DAQ module.
trace (39): Failed to register static DAQ module.
ERROR: Could not find requested DAQ module: pcap

FATAL: see prior 1 errors (0 warnings)
Fatal Error, Quitting..
</pre>

What can I do to fix this? 
Edit: I can fix the `ERROR: Could not find requested DAQ module: pcap` error with `--daq-dir`
Edit: After searching around Google, all j could find for `Failed to register static DAQ module.` was links to source code.

**Comment by snortadmin** [comment]
So there are two issues:

1. The pcap issue which you fixed looks like it wasn't able to find libpcap when libdaq was built. Is that what you fixed?

2. The failed to register lines are annoying but benign. The modules were registered the first time. The static DAQ modules are populated in <build>/src/packet_io/sfdaq_static_modules.h when cmake is configured. If the cmake configuration changes and then a make is done, the modules get added again. That apparently happened 7 times in your case. We will fix the build foo. To get rid of the problem, you can rebuild into an empty directory.

**Comment by raging-loon** [comment]
@snortadmin thanks. I'm glad it's benign and not a serious issue. Thanks for the help.

**Comment by arunkayambu** [comment]
This issue is fixed and will be included in the next build
