### ISSUE TITLE
file_magic.lua: No such file or directory

### ISSUE THREAD

**Issue by hansimehdi** [snort3/snort3#265]
I installed snort  v3.1.39.0 on Centos stream 8.

When I try to start snot I am facing an error `file_magic.lua: No such file or directory`.
I commented the inclusion of  file_magic.lua in snort.lua and it worked fine.

Can you advise please.

Thank you.

**Comment by snortadmin** [comment]
You have an old config. file_magic.lua is no longer used. Use the default config in snort3/lua/ or the latest Talos lightSPD package for configuration. They have this:

file_id = { rules_file = 'file_magic.rules' }

Note that this list is for development issues. Redirect to the snort-users mailing list for additional configuration help.

**Comment by hansimehdi** [comment]
Thank you.

**Comment by bhapatel92** [comment]
Hi I am installing snort3 and having the same issue. My snort_default.lua file shows the following line, but still giving the same error. 

file_id = { rules_file = 'file_magic.rules' }
