### ISSUE TITLE
Failed with result 'signal'

### ISSUE THREAD

**Issue by shirley04** [snort3/snort3#267]
ExecStart=/usr/local/bin/snort -c /usr/local/etc/snort/snort.lua -s 65535 -k none -l /var/log/snort -D -u snort -g snort -i ens9 -m 0x1b --create-pidfile --plugin-path=/usr/local/lib/snort/plugins/extra/  --plugin-path=/usr/local/etc/so_rules/

snort3.service: Main process exited, code=killed, status=9/KILL
 ips systemd[1]: snort3.service: Failed with result 'signal'.

/usr/local/bin/snort -V

   ,,_     -*> Snort++ <*-
  o"  )~   Version 3.1.39.0
   ''''    By Martin Roesch & The Snort Team
           http://snort.org/contact#team
           Copyright (C) 2014-2022 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using DAQ version 3.0.9
           Using LuaJIT version 2.1.0-beta3
           Using OpenSSL 1.1.1  11 Sep 2018
           Using libpcap version 1.8.1
           Using PCRE version 8.45 2021-06-15
           Using ZLIB version 1.2.11
           Using Hyperscan version 5.4.0 2022-07-13
           Using LZMA version 5.2.2

**Comment by matirko** [comment]
Does it work if you run it manually (i.e, not from systemd as a service?) 

Example:
`/usr/local/bin/snort -c /usr/local/etc/snort/snort.lua -s 65535 -k none -l /var/log/snort -D -u snort -g snort -i ens9 -m 0x1b --create-pidfile --plugin-path=/usr/local/lib/snort/plugins/extra/ --plugin-path=/usr/local/etc/so_rules/`

**Comment by shirley04** [comment]
If I run it manually, It crashed after 30 minutes. It is as the same as the service.

**Comment by matirko** [comment]
From these logs, it seems like it's not Snort that's crashing, but rather someone is killing it (`status=9/KILL`). Does /var/log/messages (or syslog) show anything at the time of the crash? 

Also, looking at `dmesg` might help, especially in the case it was oom-killer that is causing this

**Comment by dkyrylov** [comment]
@shirley04, the suggestion above should help in finding the SIGKILL cause. Can you get back to us if the issue persists or close this thread if the issue was resolved?

**Comment by InverseRE** [comment]
Not enough data  to proceed.
Please, feel free to re-open once you get more input on this.
