### ISSUE TITLE
[Question] How to make snort to work with dpdk?

### ISSUE THREAD

**Issue by hamidgh09** [snort3/snort3#272]
Hi, 

I need to build snort3 with dpdk support and I have already found some old repositories that provide the required daq working with DPDK16.04. 
I wonder if the latest version of snort supports dpdk without external daqs and if so, any link or documentation to follow is highly appreciated! Thanks!

**Comment by ansrb** [comment]
Hi. Short answer is that you are already on the right track.
Snort itself doesn't implement packet capture, it uses DAQ for this. For this reason, snort just doesn't have any uses for dpdk, so by definition it can't support it. DAQ does have uses for it though.
dpdk use with snort is purely a question of what DAQ is used. DAQ from https://github.com/snort3/libdaq doesn't use dpdk, as I'm aware, so you will need to find a DAQ that does.

**Comment by InverseRE** [comment]
> I wonder if the latest version of snort supports dpdk without external daqs.

Snort requires DAQ to process packets. AFAIK, there is no DAQ available to work with DPDK.

**Comment by actanble** [comment]
suricata + dpdk can suport
