### ISSUE TITLE
[Question] Time based logs?

### ISSUE THREAD

**Issue by dustinlawton** [snort3/snort3#274]
I was wondering if there is a way for snort to output alert logs on a time based interval? Currently snort is outputting files by "limit = 5". I looked through the documentation and didn't see anything related to time based log file creation. Any help would be greatly appreciated.

**Comment by ansrb** [comment]
Hi. As far as I'm aware, alerts logging doesn't have such functionality, if you want something like having logs generated for each day.
snort can filter events based on time (filters module), but I assume this is not what you are asking about.

**Comment by finchy** [comment]
What problem are you trying to solve?

**Comment by dustinlawton** [comment]
I am using Snort3 as an IDS and the research that I am doing it would be easier if the log files from the alerts were able to cut off by a time limit rather then a file size limit. I know I can do it with Linux scripting but I was wondering if Snort had the ability to cut the logs on an hourly or daily basis. If it could then my application would know when new logs are generated to go collect them.

**Comment by finchy** [comment]
You could HUP or restart Snort every $periodic timeframe
