### ISSUE TITLE
Snort Using Unix-Style Path In Windows

### ISSUE THREAD

**Issue by kronkinatorix** [snort3/snort3#275]
Using the latest windows release. snort s2_9_0. 

I'm getting this error: ERROR: OpenAlertFile() => fopen() alert file C:\snort\log\snortverb.log/alert.ids: No such file or directory.

I can't find alert.ids mentioned anywhere - it's clearly looking for a different file somewhere but it's nowhere to be found. 

nothing I say or do can make it stop using the wrong backslash. Help will be appreciated, thanks.

**Comment by matirko** [comment]
This is the issues page for Snort3. Also, this looks like it might be a config issue. Please reach out to [our email lists](https://www.snort.org/community#mailing_listsl) or [our discord](https://blog.snort.org/2021/07/join-snort-on-discord.html) for more help, as they will likely be able to help better with Snort2-related questions

If possible, include all relevant configs.
