### ISSUE TITLE
Flatbuffers not linking

### ISSUE THREAD

**Issue by Z3dKay** [snort3/snort3#278]
I've installed all dependencies for Snort 3 including latest version of Flatbuffers 22.11.23, and once I run `snort -V`, Flatbuffers does not show in the list of linked dependencies...

```
,,_     -*> Snort++ <*-
  o"  )~   Version 3.1.47.0
   ''''    By Martin Roesch & The Snort Team
           http://snort.org/contact#team
           Copyright (C) 2014-2022 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using DAQ version 3.0.9
           Using LuaJIT version 2.1.0-beta3
           Using OpenSSL 1.1.1n  15 Mar 2022
           Using libpcap version 1.10.0 (with TPACKET_V3)
           Using PCRE version 8.45 2021-06-15
           Using ZLIB version 1.2.11
           Using Hyperscan version 5.4.8 2022-11-30
           Using LZMA version 5.2.5
```
_N.B. irrelevant but using ARM fork of Hyperscan called Vectorscan hence the version_

Nor when compiling/building:
```
Feature options:
    DAQ Modules:    Static (afpacket;bpf;dump;fst;gwlb;nfq;pcap;savefile;trace)
    libatomic:      System-provided
    Hyperscan:      ON
    ICONV:          ON
    Libunwind:      ON
    LZMA:           ON
    RPC DB:         Built-in
    SafeC:          ON
    TCMalloc:       ON
    JEMalloc:       ON
    UUID:           ON
```
I have the snort directory in the same directory as the flatbuffers-build directory (that I made in which I ran `cmake ../flatbuffers-22.11.23 && make && sudo make install`

I can't seem to tell Snort3 where flatbuffers is when doing `./configure_cmake.sh` as there is no flag for that.

Is Flatbuffers intentionally hidden, am I doing something wrong, or does Snort3-3.1.47.0 not use flatbuffers anymore?

**Comment by VytalyGorbatov** [comment]
Hi, you're right, Snort 3 has stopped using flatbuffers since version 3.1.30.0 (commit 3ec1850).

**Comment by Z3dKay** [comment]
Thank you @VytalyGorbatov for confirming this. I should have checked
