### ISSUE TITLE
How can I confirm I am using Hyperscan as search engine?

### ISSUE THREAD

**Issue by PlinkPlunkT** [snort3/snort3#283]
Hi, 

I am a new learner of snort. I am using snort3 and I've installed Hyperscan. I also configured `snort.lua` and the command `snort -c ./snort.lua` ran successfully. But I can't find how to confirm I am actually using Hyperscan as search engine. Is there any way to know it?

Thank you!

**Comment by snortadmin** [comment]
Unfortunately, it isn't explicitly shown. For now, check the startup output under "search engine". The output for hyperscan looks like this:
```
search engine
                instances: 1278
                 patterns: 142898
        fast pattern only: 95446
```
The output for ac_bnfa starts like this:
```
search engine
                instances: 1278
                 patterns: 142898
            pattern chars: 3361344
...
```
And the output for ac_full starts like this:
```
search engine
           storage format: full
         finite automaton: DFA
            alphabet size: 256
...
```
We will make it explicit.

**Comment by snortadmin** [comment]
BTW, if you built with hyperscan, you will see this output:
```
$ src/snort -V | grep Hyperscan
           Using Hyperscan version 5.4.0 2022-01-20
```
But that does not mean hyperscan was configured, just that it is available.

**Comment by PlinkPlunkT** [comment]
> Unfortunately, it isn't explicitly shown. For now, check the startup output under "search engine". The output for hyperscan looks like this:
> 
> ```
> search engine
>                 instances: 1278
>                  patterns: 142898
>         fast pattern only: 95446
> ```
> 
> The output for ac_bnfa starts like this:
> 
> ```
> search engine
>                 instances: 1278
>                  patterns: 142898
>             pattern chars: 3361344
> ...
> ```
> 
> And the output for ac_full starts like this:
> 
> ```
> search engine
>            storage format: full
>          finite automaton: DFA
>             alphabet size: 256
> ...
> ```
> 
> We will make it explicit.

Hi, 
Thanks for timely reply. But can you tell me how to see this start up output? I tried `snort -r xx.pcap` as shown in README, but it seems no such output. 
Thank you!

**Comment by snortadmin** [comment]
You must specify a config file to use with -c. W/o a config file, Snort just reads the pcap and dumps some stats at the end. With a config file, Snort will load the config and dump some information before reading the pcap. That is where you will the search engine output.

In addition, you need to specify some rules to load. There are many ways to do that, eg. with -R or --rule-path. W/o rules, you will some minimal search engine usage at startup depending on your config. With rules, you will see more instances.

The README has examples on how to run with a config and rules.

**Comment by PlinkPlunkT** [comment]
> You must specify a config file to use with -c. W/o a config file, Snort just reads the pcap and dumps some stats at the end. With a config file, Snort will load the config and dump some information before reading the pcap. That is where you will the search engine output.
> 
> In addition, you need to specify some rules to load. There are many ways to do that, eg. with -R or --rule-path. W/o rules, you will some minimal search engine usage at startup depending on your config. With rules, you will see more instances.
> 
> The README has examples on how to run with a config and rules.

That helps a lot. Thank you so much!

**Comment by InverseRE** [comment]
Also, fixed in https://github.com/snort3/snort3/releases/tag/3.1.53.0
