### ISSUE TITLE
Error while configuring snort3

### ISSUE THREAD

**Issue by ENB213-xiaoh** [snort3/snort3#284]
Error as follow:
{
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBLZMA_LIBRARY
linked by target "cmTC_24263" in directory /home/enb213/snort/snort3/build/CMakeFiles/CMakeTmp

CMake Error at /usr/share/cmake-3.22/Modules/CheckLibraryExists.cmake:72 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  cmake/sanity_checks.cmake:145 (check_library_exists)
  CMakeLists.txt:31 (include)
}
No clue how to solve it so far. Please advise.

**Comment by ENB213-xiaoh** [comment]
Sorry. Problem solved.

**Comment by Lavender-exe** [comment]
How did you solve it?

**Comment by DullJZ** [comment]
`apt install liblzma-dev`
