### ISSUE TITLE
Issue faced while booting  Snort3

### ISSUE THREAD

**Issue by Yashil06** [snort3/snort3#287]
Please help me with this issue faced, thank you. 

[Untitled-2.md](https://github.com/snort3/snort3/files/10422646/Untitled-2.md)

**Comment by InverseRE** [comment]
As BUILD SNORT step 1 says:

>     Set up source directory:
>     If you are using a github clone:
>         cd snort3/
>     Otherwise, do this:
>         tar zxf snort-tarball
>     cd snort-3.0.0*

Here you have two options (for sources got from GIT or as an archive). Do not mix those. 
So, follow exclusively GIT-path (or TARBALL-path) in all build steps.

**Comment by AnnaNorokh** [comment]
Hello, @Yashil06 as you already proceed with `git clone` there is no need to `tar zxf snort-tarball`. It's required only if you download snort tarball from snort.org. In your case, you already have all necessary files in `/opt/snort3` to build snort. So you can proceed with step 2 in BUILD SNORT instruction. If you have any other questions, feel free to ask.

**Comment by Yashil06** [comment]
My steps include configuring and build the cmake,  through this command , ./configure_cmake.sh --prefix=$my_path, unfortunately while being on sudo escalated privilege, got this error message  : 

{
┌──(root㉿kali)-[/opt/snort3]                            
└─# ./configure_cmake.sh --prefix=/opt/snort3/                                                                    
./configure_cmake.sh: 486: [: -eq: unexpected operator                                                            
Build Directory : build                                  
Source Directory: /opt/snort3                            
CMake Warning:                                           
  Ignoring empty string ("") provided on the command line.                                                        


-- The CXX compiler identification is GNU 12.2.0                                                                  
-- The C compiler identification is GNU 12.2.0                                                                    
-- Detecting CXX compiler ABI info                                                                                
-- Detecting CXX compiler ABI info - done                                                                         
-- Check for working CXX compiler: /usr/bin/c++ - skipped                                                         
-- Detecting CXX compile features                                                                                 
-- Detecting CXX compile features - done                                                                          
-- Detecting C compiler ABI info                                                                                  
-- Detecting C compiler ABI info - done                                                                           
-- Check for working C compiler: /usr/bin/cc - skipped                                                            
-- Detecting C compile features                          
-- Detecting C compile features - done                                                                            
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD                                                                        
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success                                                              
-- Found Threads: TRUE                                   
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)                                                      
CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):                                                                                                                                     
  Could NOT find DAQ (missing: DAQ_LIBRARIES DAQ_INCLUDE_DIR)                                                     
Call Stack (most recent call first):                                                                              
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)                                                                                                                                    
  cmake/FindDAQ.cmake:34 (find_package_handle_standard_args)                                                      
  cmake/include_libraries.cmake:4 (find_package)                                                                  
  CMakeLists.txt:27 (include)                            


-- Configuring incomplete, errors occurred!                                                                       
See also "/opt/snort3/build/CMakeFiles/CMakeOutput.log".     
}


As i checked the logs for the error ouput under the CmakOutputLog, found the following : 


 Therefore i have attached the CMakeOutput.log for your visibility, there seem to be an issue, i used : 



             $ sudo gedit CMakeOutput.log
 
I analyzed the CmakOutputLog, starting from the "line 480 ", so please start the investigation from that point onwards, this is from where i tried the following once more : 


┌──(root㉿kali)-[/opt/snort3]                                             
  
└─# ./configure_cmake.sh --prefix=/opt/snort3              


[CMakeOutput.txt](https://github.com/snort3/snort3/files/10475545/CMakeOutput.txt)

Let me know if the CMakeOutput.txt is viewable through gedit , as i had to change this to ".txt", let me know ..

**Comment by Yashil06** [comment]
My path was for the cmake configuration was set at  : /opt/snort3/

**Comment by AnnaNorokh** [comment]
@Yashil06  As I can see, Snort can't find PkgConfig and DAQ instances. 
Please check that you successfully install PkgConfig. Try: `sudo apt-get -y install pkg-config`

As about DAQ please try to add this environment variables and build Snort again.
```
export DAQ_INCLUDE_DIR="_**<your_path_to_DAQ>**_/libdaq/install/include"
export DAQ_LIBRARIES="**_<your_path_to_DAQ>_**/libdaq/install/lib"
```

**Comment by Yashil06** [comment]
Hey sir, i followed all the instructions, as per your reply, this worked for me to export path .. onto where my libdaq has been git cloned ...."/opt " as per the below  :: 

 
Just  as a quick reference : 

┌──(kali㉿kali)-[/opt/snort3]
└─$ ls                                
build           cmake_uninstall.cmake.in  crusty.cfg  lua          tools
ChangeLog.md    config.cmake.h.in         daqs        README.md
cmake           configure_cmake.sh        doc         snort.pc.in
CMakeLists.txt  COPYING     

As i try to build snort, further steps include, running , "./configure _cmake.sh"  : 



Tried the following : 

┌──(kali㉿kali)-[/opt/snort3]

└─$ sudo ./configure_cmake.sh --prefix=/opt/snort3/  \


[sudo] password for kali:             
./configure_cmake.sh: 486: [: -eq: unexpected operator
Build Directory : build               
Source Directory: /opt/snort3
CMake Warning:                        
  Ignoring empty string ("") provided on the command line.

***************************************
************************

Here is the error message i am getting at the very bottom : 


CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find DAQ (missing: DAQ_LIBRARIES DAQ_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindDAQ.cmake:34 (find_package_handle_standard_args)
  cmake/include_libraries.cmake:4 (find_package)
  CMakeLists.txt:27 (include)

[CMakeOutput.log](https://github.com/snort3/snort3/files/10496195/CMakeOutput.log)

-- Configuring incomplete, errors occurred!
See also "/opt/snort3/build/CMakeFiles/CMakeOutput.log".


***************************

*********************
[CMakeOutput.log](https://github.com/snort3/snort3/files/10496200/CMakeOutput.log)



I have also included the CMakeOutput.log, please start from the line "4390", in order to inspect any discrepancies ,which may be preventing to run the "./configure_cmake.sh file. 

Thanks  again for all the support , so far ..

**Comment by snortadmin** [comment]
https://github.com/snort3/snort3/issues/253
