### ISSUE TITLE
Can't use -A and -L at the same time?

### ISSUE THREAD

**Issue by miamor** [snort3/snort3#289]
Hi,

I've been trying to log both alert and pcap files, but it seems like only one logging would work.
Here's my command:
```
sudo snort -c /etc/snort/snort.lua -R ~/snorty/rules/local.rules -i enp0s3 -L log_pcap -A alert_csv -s 65535
```

Here's my output config:
```
---------------------------------------------------------------------------
-- 7. configure outputs
---------------------------------------------------------------------------

-- event logging
-- you can enable with defaults from the command line with -A <alert_type>
-- uncomment below to set non-default configs
alert_csv = {
	file = true,
	limit = 10
}
alert_fast = {
	file = true,
	limit = 10
}
--alert_full = { }
--alert_sfsocket = { }
--alert_syslog = { }
unified2 = { }

-- packet logging
-- you can enable with defaults from the command line with -L <log_type>
--log_codecs = { }
--log_hext = { }
log_pcap = { }
```

I can only log one thing to one file (even `-A alert_fast -A alert_csv` would log to `alert_csv.txt` only), only the last logging option is taken into account.Is it designed that way or am I missing anything?

Many thanks!

**Comment by InverseRE** [comment]
Hi.

First of all, a command line option (-A) takes precedence over lua configurations.
The -A option cannot specify multiple loggers, just one logger (the last one in command line parameters).
Still, from the lua configuration file, you can specify multiple loggers at a time.

For example:
```
snort -c /dev/null -A cmg -A csv
snort -c /dev/null -A csv -A cmg
snort -c /dev/null --lua "alert_csv = {}; alert_fast = {};"
snort -c /dev/null --lua "alert_csv = {}; alert_fast = {};" -A csv
snort -c /dev/null --lua "alert_csv = {}; alert_fast = {};" -A cmg
```
1 - csv
2 - cmg
3 - csv **and** cmg
4 - just csv
5 - just cmg

**Comment by miamor** [comment]
Hi,
Thank you very much! It worked.
