### ISSUE TITLE
Failed to Install

### ISSUE THREAD

**Issue by FullMetalDilka** [snort3/snort3#290]
I don't have any problems until:
![Screenshot_2023-01-26_22_58_14](https://user-images.githubusercontent.com/107579869/215007010-24989b5f-4cf6-49b2-89b1-83167a709871.png)

**Comment by chris2008-dotcom** [comment]
I have the exact same problem.

**Comment by snortadmin** [comment]
You need to tell the snort3 build where to find the libdaq install, either by using --with-daq-includes/libraries (configure_cmake.sh --help for more) or exporting PKG_CONFIG_PATH=<path to directory containing libdaq.pc>.

Also, this is not a development issue so it should be reported to the snort-users list (https://snort.org/community#mailing_lists) where you will likely get more timely help.

Cheers
