### ISSUE TITLE
Problem with start SNORT 3 after installation

### ISSUE THREAD

**Issue by banannd** [snort3/snort3#291]
Hi,
When I try start SNORT after installation i have error like this below: 
It's two problem, one is with:

sudo ethtool -K eth0 gro off lro off
Cannot change large-receive-offload

and second problem:

`~ $ sudo snort -c /usr/local/etc/snort/snort.lua
--------------------------------------------------
o")~   Snort++ 3.1.18.0
--------------------------------------------------
Loading /usr/local/etc/snort/snort.lua:
Loading snort_defaults.lua:
Finished snort_defaults.lua:
Loading file_magic.lua:
Finished file_magic.lua:
        ssh
        hosts
        host_cache
        pop
        so_proxy
        stream_tcp
        mms
        smtp
        gtp_inspect
        packets
        dce_http_proxy
        stream_icmp
        normalizer
        ips
        network
        binder
        wizard
        appid
        file_id
        stream_udp
        http2_inspect
        http_inspect
        ftp_data
        search_engine
        ftp_server
        port_scan
        dce_http_server
        dce_smb
        dce_tcp
        netflow
        iec104
        cip
        telnet
        ssl
        sip
        rpc_decode
        modbus
        host_tracker
        stream_user
        stream_ip
        process
        back_orifice
        classifications
        dnp3
        active
        trace
        ftp_client
        decode
        alerts
        stream
        daq
        references
        arp_spoof
        output
        dns
        dce_udp
        imap
        file_policy
        s7commplus
        stream_file
Finished /usr/local/etc/snort/snort.lua:
--------------------------------------------------
afpacket (1): Failed to register static DAQ module.
afpacket (2): Failed to register static DAQ module.
bpf (4): Failed to register static DAQ module.
bpf (5): Failed to register static DAQ module.
dump (7): Failed to register static DAQ module.
dump (8): Failed to register static DAQ module.
fst (10): Failed to register static DAQ module.
fst (11): Failed to register static DAQ module.
gwlb (13): Failed to register static DAQ module.
gwlb (14): Failed to register static DAQ module.
nfq (16): Failed to register static DAQ module.
nfq (17): Failed to register static DAQ module.
pcap (19): Failed to register static DAQ module.
pcap (20): Failed to register static DAQ module.
savefile (22): Failed to register static DAQ module.
savefile (23): Failed to register static DAQ module.
trace (25): Failed to register static DAQ module.
trace (26): Failed to register static DAQ module.
pcap DAQ configured to passive.

Snort successfully validated the configuration (with 0 warnings).
o")~   Snort exiting
`

**Comment by snortadmin** [comment]
See https://github.com/snort3/snort3/issues/264. It was fixed, and 3.1.18.0 is over a year old. git the latest snort3 and libdaq and try again.
