### ISSUE TITLE
How to locate memory leaks？

### ISSUE THREAD

**Issue by wenhao-in-chengdu** [snort3/snort3#294]
![image](https://user-images.githubusercontent.com/38171981/224480956-ee41157b-c2e2-4969-9275-cfeb3eb1fbbb.png)
![image](https://user-images.githubusercontent.com/38171981/224480981-281ecd72-d9f7-48f3-801c-29552e99e4a0.png)
![image](https://user-images.githubusercontent.com/38171981/224481049-79481e64-8998-41c2-9d92-88c42cb1ad3e.png)
![image](https://user-images.githubusercontent.com/38171981/224481126-9e35a923-8271-49be-ab0d-481a0fc6fde0.png)
![73B49069-1E36-463e-8EC6-3B4A1FC08B6F](https://user-images.githubusercontent.com/38171981/224481266-9c922bdc-d99a-4cf6-a4b2-95d8fcd7f32e.png)
![63076BBF-31D2-4657-BB7F-1DB9F37CABCE](https://user-images.githubusercontent.com/38171981/224481273-861137ee-1336-4fdf-9ca5-9a74dde99efc.png)
![FBD66D94-BD63-409b-A668-3FD70DB4FC92](https://user-images.githubusercontent.com/38171981/224481286-1b2d50c2-dbf9-4563-a924-1d818c580479.png)

**Comment by wenhao-in-chengdu** [comment]
After the snort process continues streaming for 30 minutes, the memory usage is too high

**Comment by Xiche** [comment]
Your Snort 3 is about 2 years out of date, so I'd start by updating that first.  Next, you're going to need to provide information including your full config (including rules, command line), the DAQ module being used, better information about the generated traffic you're sending, and, last but certainly not least, why you think it's using too much memory based on everything else involved.

**Comment by InverseRE** [comment]
@wenhao-in-chengdu 
was this resolved in #273 ?
