### ISSUE TITLE
Do you apply sanctions?

### ISSUE THREAD

**Issue by alirezadigi** [snort3/snort3#295]
hi, and thanks for this great project!
i wanted to visit snort website and i couldn't access website from IRAN , i think that's because of cloudflare configuration and , america's sanctions... 
do you apply sanctions to us? and ... if you do ... so i should look for alternatives right?

**Comment by alirezadigi** [comment]
I got an error when visiting www.snort.org/.

Error code: 1020
Ray ID: 7ad1332b08c79188
Country: IR
Data center: fra08
IP: ...........
Timestamp: 2023-03-24 19:07:56 UTC

**Comment by InverseRE** [comment]
Not Snort3 code related.
