### ISSUE TITLE
How can I use two different algorithms for matching？

### ISSUE THREAD

**Issue by aRanHC** [snort3/snort3#299]
Hey SNORT team.I know Snort 3 uses Hyperscan for fast pattern matching,When I type snort -V, the output contains "Using Hyperscan version 5.4.0".
If I want to use another algorithm, such as Aho-Corasick, how should I do it?

**Comment by InverseRE** [comment]
```
> ./snort --help-module search_engine
search_engine
Help: configure fast pattern matcher
Type: basic
Usage: global
Configuration:
dynamic search_engine.search_method = ac_bnfa: set fast pattern algorithm - choose available search engine { ac_bnfa | ac_full | hyperscan }
dynamic search_engine.offload_search_method: set fast pattern offload algorithm - choose available search engine { ac_bnfa | ac_full | hyperscan }
```

In my case, only three MPSE are available.
If you want to provide another MPSE for Snort, the implementation could be added in snort3/src/search_engines directory.

**Comment by aRanHC** [comment]
@InverseRE ,thank you for your help! I am very grateful for your generous answer.
In addition, when I use the following command to detect:
`snort -c /usr/local/etc/snort/snort.lua --pcap-dir /home/ran/pcap --pcap-filter '*.pcap'`
The output doesn't seem to show what MPSE I'm using,if I want to specify the MPSE to use, how should I do it?
BTW, my version is the latest 3.1.60.0.
