### ISSUE TITLE
Fedora 38 compilation errors

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [snort3/snort3#300]
...
[ 13%] Building CXX object src/js_norm/CMakeFiles/js_norm.dir/js_identifier_ctx.cc.o
In file included from /home/src/snort3/src/js_norm/js_identifier_ctx.cc:24:
/home/src/snort3/src/js_norm/js_identifier_ctx.h:59:36: error: ‘uint32_t’ has not been declared
   59 |     JSIdentifierCtx(int32_t depth, uint32_t max_scope_depth,
      |                                    ^~~~~~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.h:79:9: error: ‘uint8_t’ does not name a type
   79 |         uint8_t type = 0;
      |         ^~~~~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.h:28:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   27 | #include <vector>
  +++ |+#include <cstdint>
   28 |
/home/src/snort3/src/js_norm/js_identifier_ctx.h:123:5: error: ‘uint32_t’ does not name a type
  123 |     uint32_t max_scope_depth;
      |     ^~~~~~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.h:123:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/src/snort3/src/js_norm/js_identifier_ctx.cc:66:1: error: no declaration matches ‘jsn::JSIdentifierCtx::JSIdentifierCtx(int32_t, uint32_t, const std::unordered_set<std::__cxx11::basic_string<char> >&, const std::unordered_set<std::__cxx11::basic_string<char> >&)’
   66 | JSIdentifierCtx::JSIdentifierCtx(int32_t depth, uint32_t max_scope_depth,
      | ^~~~~~~~~~~~~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.h:56:7: note: candidates are: ‘jsn::JSIdentifierCtx::JSIdentifierCtx(jsn::JSIdentifierCtx&&)’
   56 | class JSIdentifierCtx : public JSIdentifier
      |       ^~~~~~~~~~~~~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.h:56:7: note:                 ‘jsn::JSIdentifierCtx::JSIdentifierCtx(const jsn::JSIdentifierCtx&)’
/home/src/snort3/src/js_norm/js_identifier_ctx.h:59:5: note:                 ‘jsn::JSIdentifierCtx::JSIdentifierCtx(int32_t, int, const std::unordered_set<std::__cxx11::basic_string<char> >&, const std::unordered_set<std::__cxx11::basic_string<char> >&)’
   59 |     JSIdentifierCtx(int32_t depth, uint32_t max_scope_depth,
      |     ^~~~~~~~~~~~~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.h:56:7: note: ‘class jsn::JSIdentifierCtx’ defined here
   56 | class JSIdentifierCtx : public JSIdentifier
      |       ^~~~~~~~~~~~~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.cc: In member function ‘bool jsn::JSIdentifierCtx::is_substituted(const NormId&, bool)’:
/home/src/snort3/src/js_norm/js_identifier_ctx.cc:110:17: error: ‘const struct jsn::JSIdentifierCtx::NormId’ has no member named ‘type’
  110 |     return ((id.type & TYPE_NORMALIZED) != 0) ||
      |                 ^~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.cc:111:31: error: ‘const struct jsn::JSIdentifierCtx::NormId’ has no member named ‘type’
  111 |         (!is_property && ((id.type & TYPE_IGNORED_ID) != 0)) ||
      |                               ^~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.cc:112:30: error: ‘const struct jsn::JSIdentifierCtx::NormId’ has no member named ‘type’
  112 |         (is_property && ((id.type & TYPE_IGNORED_PROP) != 0));
      |                              ^~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.cc: In member function ‘const char* jsn::JSIdentifierCtx::acquire_norm_name(NormId&)’:
/home/src/snort3/src/js_norm/js_identifier_ctx.cc:126:12: error: ‘struct jsn::JSIdentifierCtx::NormId’ has no member named ‘type’
  126 |         id.type |= TYPE_NORMALIZED;
      |            ^~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.cc:127:17: error: ‘struct jsn::JSIdentifierCtx::NormId’ has no member named ‘type’
  127 |         if ((id.type & TYPE_IGNORED_ID) != 0)
      |                 ^~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.cc:129:22: error: ‘struct jsn::JSIdentifierCtx::NormId’ has no member named ‘type’
  129 |         else if ((id.type & TYPE_IGNORED_PROP) != 0)
      |                      ^~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.cc:133:40: error: no match for ‘operator=’ (operand types are ‘jsn::JSIdentifierCtx::NormId’ and ‘<brace-enclosed initializer list>’)
  133 |     return (id = {n, n, TYPE_NORMALIZED}).id_name;
      |                                        ^
/home/src/snort3/src/js_norm/js_identifier_ctx.h:75:12: note: candidate: ‘constexpr jsn::JSIdentifierCtx::NormId& jsn::JSIdentifierCtx::NormId::operator=(const jsn::JSIdentifierCtx::NormId&)’
   75 |     struct NormId
      |            ^~~~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.h:75:12: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const jsn::JSIdentifierCtx::NormId&’
/home/src/snort3/src/js_norm/js_identifier_ctx.h:75:12: note: candidate: ‘constexpr jsn::JSIdentifierCtx::NormId& jsn::JSIdentifierCtx::NormId::operator=(jsn::JSIdentifierCtx::NormId&&)’
/home/src/snort3/src/js_norm/js_identifier_ctx.h:75:12: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘jsn::JSIdentifierCtx::NormId&&’
/home/src/snort3/src/js_norm/js_identifier_ctx.cc: In member function ‘void jsn::JSIdentifierCtx::init_ignored_names()’:
/home/src/snort3/src/js_norm/js_identifier_ctx.cc:140:79: error: no match for ‘operator=’ (operand types are ‘jsn::JSIdentifierCtx::NormId’ and ‘<brace-enclosed initializer list>’)
  140 |             id_fast[(unsigned)iid[0]] = {iid.c_str(), nullptr, TYPE_IGNORED_ID};
      |                                                                               ^
/home/src/snort3/src/js_norm/js_identifier_ctx.h:75:12: note: candidate: ‘constexpr jsn::JSIdentifierCtx::NormId& jsn::JSIdentifierCtx::NormId::operator=(const jsn::JSIdentifierCtx::NormId&)’
   75 |     struct NormId
      |            ^~~~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.h:75:12: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const jsn::JSIdentifierCtx::NormId&’
/home/src/snort3/src/js_norm/js_identifier_ctx.h:75:12: note: candidate: ‘constexpr jsn::JSIdentifierCtx::NormId& jsn::JSIdentifierCtx::NormId::operator=(jsn::JSIdentifierCtx::NormId&&)’
/home/src/snort3/src/js_norm/js_identifier_ctx.h:75:12: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘jsn::JSIdentifierCtx::NormId&&’
/home/src/snort3/src/js_norm/js_identifier_ctx.cc:142:67: error: no match for ‘operator=’ (operand types are ‘std::unordered_map<std::__cxx11::basic_string<char>, jsn::JSIdentifierCtx::NormId>::mapped_type’ {aka ‘jsn::JSIdentifierCtx::NormId’} and ‘<brace-enclosed initializer list>’)
  142 |             id_names[iid] = {iid.c_str(), nullptr, TYPE_IGNORED_ID};
      |                                                                   ^
/home/src/snort3/src/js_norm/js_identifier_ctx.h:75:12: note: candidate: ‘constexpr jsn::JSIdentifierCtx::NormId& jsn::JSIdentifierCtx::NormId::operator=(const jsn::JSIdentifierCtx::NormId&)’
   75 |     struct NormId
      |            ^~~~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.h:75:12: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const jsn::JSIdentifierCtx::NormId&’
/home/src/snort3/src/js_norm/js_identifier_ctx.h:75:12: note: candidate: ‘constexpr jsn::JSIdentifierCtx::NormId& jsn::JSIdentifierCtx::NormId::operator=(jsn::JSIdentifierCtx::NormId&&)’
/home/src/snort3/src/js_norm/js_identifier_ctx.h:75:12: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘jsn::JSIdentifierCtx::NormId&&’
/home/src/snort3/src/js_norm/js_identifier_ctx.cc:149:41: error: ‘struct jsn::JSIdentifierCtx::NormId’ has no member named ‘type’
  149 |             id_fast[(unsigned)iprop[0]].type |= TYPE_IGNORED_PROP;
      |                                         ^~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.cc:154:29: error: ‘std::unordered_map<std::__cxx11::basic_string<char>, jsn::JSIdentifierCtx::NormId>::mapped_type’ {aka ‘struct jsn::JSIdentifierCtx::NormId’} has no member named ‘type’
  154 |             id_names[iprop].type |= TYPE_IGNORED_PROP;
      |                             ^~~~
/home/src/snort3/src/js_norm/js_identifier_ctx.cc: In member function ‘virtual bool jsn::JSIdentifierCtx::scope_push(jsn::JSProgramScopeType)’:
/home/src/snort3/src/js_norm/js_identifier_ctx.cc:163:26: error: ‘max_scope_depth’ was not declared in this scope
  163 |     if (scopes.size() >= max_scope_depth)
      |                          ^~~~~~~~~~~~~~~
make[2]: *** [src/js_norm/CMakeFiles/js_norm.dir/build.make:120: src/js_norm/CMakeFiles/js_norm.dir/js_identifier_ctx.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3203: src/js_norm/CMakeFiles/js_norm.dir/all] Error 2

...

any idea?
thanks

**Comment by VytalyGorbatov** [comment]
Hi @ROBERT-MCDOWELL, as a hotfix method you can add `#include <cstdint>` to snort3/src/js_norm/js_identifier_ctx.h file, on line 28. We will fix this as soon as possible, thanks.

**Comment by ROBERT-MCDOWELL** [comment]
any news? last git still shows this compilation errors:
In file included from /home/src/snort3/src/packet_io/sfdaq_config.cc:25:
/home/src/snort3/src/packet_io/sfdaq_config.h:59:25: error: ‘uint32_t’ has not been declared
   59 |     void set_batch_size(uint32_t);
      |                         ^~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.h:62:5: error: ‘uint32_t’ does not name a type
   62 |     uint32_t get_batch_size() const { return (batch_size == BATCH_SIZE_UNSET) ? BATCH_SIZE_DEFAULT : batch_size; }
      |     ^~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.h:26:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   25 | #include <vector>
  +++ |+#include <cstdint>
   26 |
/home/src/snort3/src/packet_io/sfdaq_config.h:63:5: error: ‘uint32_t’ does not name a type
   63 |     uint32_t get_mru_size() const { return (mru_size == SNAPLEN_UNSET) ? SNAPLEN_DEFAULT : mru_size; }
      |     ^~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.h:63:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/src/snort3/src/packet_io/sfdaq_config.h:71:5: error: ‘uint32_t’ does not name a type
   71 |     uint32_t batch_size;
      |     ^~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.h:71:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/src/snort3/src/packet_io/sfdaq_config.h:77:22: error: ‘uint32_t’ does not name a type
   77 |     static constexpr uint32_t BATCH_SIZE_UNSET = 0;
      |                      ^~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.h:77:22: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/src/snort3/src/packet_io/sfdaq_config.h:79:22: error: ‘uint32_t’ does not name a type
   79 |     static constexpr uint32_t BATCH_SIZE_DEFAULT = 64;
      |                      ^~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.h:79:22: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/src/snort3/src/packet_io/sfdaq_config.cc: In constructor ‘SFDAQConfig::SFDAQConfig()’:
/home/src/snort3/src/packet_io/sfdaq_config.cc:68:5: error: ‘batch_size’ was not declared in this scope; did you mean ‘set_batch_size’?
   68 |     batch_size = BATCH_SIZE_UNSET;
      |     ^~~~~~~~~~
      |     set_batch_size
/home/src/snort3/src/packet_io/sfdaq_config.cc:68:18: error: ‘BATCH_SIZE_UNSET’ was not declared in this scope
   68 |     batch_size = BATCH_SIZE_UNSET;
      |                  ^~~~~~~~~~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.cc: At global scope:
/home/src/snort3/src/packet_io/sfdaq_config.cc:99:6: error: variable or field ‘set_batch_size’ declared void
   99 | void SFDAQConfig::set_batch_size(uint32_t batch_size_value)
      |      ^~~~~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.cc:99:34: error: ‘uint32_t’ was not declared in this scope
   99 | void SFDAQConfig::set_batch_size(uint32_t batch_size_value)
      |                                  ^~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.cc:26:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   25 | #include "sfdaq_config.h"
  +++ |+#include <cstdint>
   26 |
/home/src/snort3/src/packet_io/sfdaq_config.cc: In member function ‘void SFDAQConfig::overlay(const SFDAQConfig*)’:
/home/src/snort3/src/packet_io/sfdaq_config.cc:126:16: error: ‘const struct SFDAQConfig’ has no member named ‘batch_size’; did you mean ‘set_batch_size’?
  126 |     if (other->batch_size != BATCH_SIZE_UNSET)
      |                ^~~~~~~~~~
      |                set_batch_size
/home/src/snort3/src/packet_io/sfdaq_config.cc:126:30: error: ‘BATCH_SIZE_UNSET’ was not declared in this scope
  126 |     if (other->batch_size != BATCH_SIZE_UNSET)
      |                              ^~~~~~~~~~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.cc:127:9: error: ‘batch_size’ was not declared in this scope; did you mean ‘set_batch_size’?
  127 |         batch_size = other->batch_size;
      |         ^~~~~~~~~~
      |         set_batch_size
/home/src/snort3/src/packet_io/sfdaq_config.cc:127:29: error: ‘const struct SFDAQConfig’ has no member named ‘batch_size’; did you mean ‘set_batch_size’?
  127 |         batch_size = other->batch_size;
      |                             ^~~~~~~~~~
      |                             set_batch_size
make[2]: *** [src/packet_io/CMakeFiles/packet_io.dir/build.make:104: src/packet_io/CMakeFiles/packet_io.dir/sfdaq_config.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3419: src/packet_io/CMakeFiles/packet_io.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by ROBERT-MCDOWELL** [comment]
...
