### ISSUE TITLE
flow logging

### ISSUE THREAD

**Issue by theflakes** [snort3/snort3#303]
Hello,

Is it possible to log metadata on all traffic flows? If so, can you point me to the config for this? Basically looking for output like nflow/sflow, Zeek, or Suricata flow logging.

thanks so much

**Comment by InverseRE** [comment]
@theflakes
What kind of data are you looking for? Can you provide a list?

At what stage flow's metadata should be logged: at the beginning, at the end, at other point in session (upon some event)?

**Comment by theflakes** [comment]
Looking for any flow logging that can emulate netflow, sflow, or Zeek logging. Sflow uses sampling, so its the least accurate and Zeek logs a flow after it ends but does some things for long running flows that I don't remember exactly. Zeek also treats UDP / ICMP like TCP when it comes to flows in order to log them.

But, I just wanted to verify that I wasn't missing something in the config that enables some type of flow logging in Snort3. From a threat hunting / investigative standpoint, logging the metadata around flows is a must. If Snort3 doesn't support this, then I can just add Zeek to the lab env I'm testing in.

Thanks

**Comment by InverseRE** [comment]
Processing unit is "packet", hence logging is done on per-packet basis.

Internally Snort can creae flow objects for TCP and UDP protocols, but one would need a custom plugin to track and log flow events: start, end, etc.
