### ISSUE TITLE
Question: how to log seperately with different rules?

### ISSUE THREAD

**Issue by donghao1107** [snort3/snort3#305]
Here is my use case: 
I need to implement a rule that log every tcp packet, record the src_ip/port, dst_ip/port, len, and save it to a logfile, the logfile will be large,

then I also want to implement some intrusion detection rules, I do not want to alert these into the previous log file,

I checked with the manual and find nothing useful information, could anyone help me to clarify is there some method to cover my use case?

**Comment by InverseRE** [comment]
AFAIK, existing loggers do not implement sorting mechanism.

However, one could write a plugin, where logger will filter out events (and log only some sub-set of events). As snort can run multiple loggers at a time, events will go to different places:
alert_custom_1 = { file = 'detection_alerts.log' } 
alert_custom_2 = { file = 'intrusion_alerts.log' }

Or a custom logger could do everything: sorting, writing to different files, etc.

**Comment by InverseRE** [comment]
Another possibility is to use bash (which is slower).

Let's say you have two sets of rules (designated by GID range, for example):
```
alert ( gid:10; sid: 123; msg: "a rule from 1st set"; )
alert ( gid:20; sid: 345; msg: "a rule from 2nd set"; )
```

Running snort with csv logger you will see messages in the following format:
05/23-04:51:22.456762, 41, TCP, raw, 136, C2S, 10.0.0.1:80, 192.168.0.1:1337, 10:123:0, allow
05/23-04:51:22.456762, 41, TCP, raw, 136, C2S, 10.0.0.1:80, 192.168.0.1:1337, 20:345:0, allow

which can be filtered out by grep commands: `grep ", 10:"` and `grep ", 20:"`.

Combining the above, the final command line looks like:
`snort -c conf.lua -A csv -q | tee >(grep "10:" > 1st.log) | grep "20:" > 2nd.log`

**Comment by donghao1107** [comment]
Thanks bro, I have solved it.
