### ISSUE TITLE
Capabilities for Monitoring Kubernetes Container/Pods

### ISSUE THREAD

**Issue by OmarGonzales** [snort3/snort3#308]
Dear Sir/Madam,

I am writing to inquire about the capabilities of your snort product in relation to monitoring Kubernetes container/pods behavior. My name is Omar, and I am currently engaged in testing various open-source security products. Specifically, I am seeking a security solution that can detect incidents such as container escapes within a Kubernetes environment.

I would greatly appreciate it if you could provide information on whether snort has the capability to fulfill this requirement.

Thank you for your attention to this matter. I eagerly await your response.

**Comment by Crowy-o** [comment]
Hello, I'm really not that familiar with Kubernetes stuff, but here's some of my thoughts.

I guess, you can take a look at https://github.com/snort3/snort3_aws - that will help you build snort in docker container.
Which should help you integrate Snort in your architecture.

Except passing all relevant network traffic cross the Snort, you'll need to write your custom IPS rules to determine "escape".
I'm not aware of which protocol you use to communicate, but if that one is not supported out-of-box by Snort, you'll have to write a custom inspector.
