### ISSUE TITLE
Why snort3 cant be clone in ubuntu? It is said that the connection refused. 

### ISSUE THREAD

**Issue by kudou16** [snort3/snort3#309]
![image](https://github.com/snort3/snort3/assets/137279064/afa1f0be-c7bd-4dbd-9c2c-212687dab316)

**Comment by AnnaNorokh** [comment]
Hi @kudou16, looks like your Ubuntu have some problems with Git Transport Protocol(git://). It may be due to your firewall settings. 

Can you try to clone Snort3 repo with https:// link or with SSH option?

**Comment by InverseRE** [comment]
Please, consider the answer above.
If it doesn't help and the issue still persists, feel free to re-open the case.
