### ISSUE TITLE
Hello everyone. I have error in ubuntu, 

### ISSUE THREAD

**Issue by kudou16** [snort3/snort3#312]
![image](https://github.com/snort3/snort3/assets/137279064/a21017b3-a788-4ee7-ac3f-77be7824d4c4)

**Comment by AnnaNorokh** [comment]
Hi @kudou16, looks like Snort can't find **libpcap** location. It may occur if you didn't install it or installed in an unusual location.

Please install libpcap (you can find it here: http://www.tcpdump.org/) if you didn't and try to build Snort again.

In case you're done the installation of libpcap, but the error is still here, please run:
./configure_cmake.sh --prefix=$my_path --with-pcap-includes=<DIR_PATH>  --with-pcap-libraries=<DIR_PATH>

**Comment by InverseRE** [comment]
Feel free to re-open if the reply above was not helpful.
