### ISSUE TITLE
Using snort2lua

### ISSUE THREAD

**Issue by ntallfellow** [snort3/snort3#313]
I have installed snort3 on Oracle Linux 8-U7. I can confirm it works both manually and via systemd. I am trying to use Snort2lua to convert my rules, and it is not working at all.
snort2lua -c snort.rules -r snort3.rules
bash: snort2lua: command not found

using lua or luajit in front of snort2lua gives me a "</127>" error as well..... Not sure how to solve this problem. 

Running which snort2lua snort gives me:
/usr/bin/which: no snort2lua anywhere
/sbin/snort (symlink)

**Comment by AnnaNorokh** [comment]
Hi @ntallfellow , snort2lua isn't a command it's just a binary. 

The right way to use it is `**$my_path/bin/snort2lua -r snort3.rules**`

Also note about options -c option, it should be provided with .conf file not .rules file.
More about snort2lua options work, you can check with `$my_path/bin/snort2lua --help`.

**Comment by ntallfellow** [comment]
Yes.Sorry I should have specified. Using snort2lua as specified does not work. No error was thrown.It comes back with bash: command not found.The only way I can get snort2lua to respond in any meaningful way is to add lua/luajit in front.Regardless of this, it will not work for me using OL8.Sent from my iPhoneOn Jun 27, 2023, at 10:21, AnnaNorokh ***@***.***> wrote:﻿
Hi @ntallfellow , snort2lua isn't a command it's just a binary.
The right way to use it is **$my_path/bin/snort2lua -r snort3.rules**
Also note about options -c option, it should be provided with .conf file not .rules file.
More about snort2lua options work, you can check with $my_path/bin/snort2lua --help.

**Comment by AnnaNorokh** [comment]
@ntallfellow could you please share screenshot of terminal with commands you're run, and it's output?

**Comment by ntallfellow** [comment]
Sent from my iPhoneOn Jun 29, 2023, at 06:54, AnnaNorokh ***@***.***> wrote:﻿
@ntallfellow could you please share screenshot of terminal with commands you're run, and it's output?

**Comment by finchy** [comment]
That didn’t work @ntallfellow

**Comment by ntallfellow** [comment]
Sent from Mail for Windows From: AnnaNorokhSent: Thursday, June 29, 2023 6:54 AMTo: snort3/snort3Cc: ntallfellow; MentionSubject: Re: [snort3/snort3] Using snort2lua (Issue ***@***.*** could you please share screenshot of terminal with commands you're run, and it's output?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by ntallfellow** [comment]
[https://imgur.io/a/2zrKyzV](url)

**Comment by AnnaNorokh** [comment]
@ntallfellow thank you for provided info! 

So the problem is that you are trying to run `snort2lua` (as a command). Instead, please try to run it as **./snort2lua**.  
So **./** is very important here as it specify that we run binary from current directory.
