### ISSUE TITLE
ERROR: server-webapp.rules: XXXX SO rule XXXXX not loaded  for Talos_LightSPD

### ISSUE THREAD

**Issue by grasstractor** [snort3/snort3#315]
System: MACOS 13.4.1
Snort version: snort 3.1.55.0 (installed by homebrew)
I download Talos_LightSPD.tar.gz on the page of https://www.snort.org/downloads#rules (registered and not subscription).
When I run it using the runsnort.sh script, I encounter a lot of errors loading the SO rules and I don't know what to do. The command I run is as follows:

./runsnort.sh /opt/homebrew/Cellar/snort/3.1.55.0 /usr/local/lib 3.1.0.0-0 3.1.44.0 aarch64 security-over-connectivity /Volumes/disk6s1/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-34-1

Some of the errors are as follows:

<img width="445" alt="image" src="https://github.com/snort3/snort3/assets/12790465/b4190091-b52f-47f6-987e-6c0d28d97fc7">

**Comment by grasstractor** [comment]
> I guess, these SO rules are not compiled for your platform.

I think so, and I'm trying to rerun it on Ubuntu 20.04. But isn't arm64 a kind of aarch64?

**Comment by allewi** [comment]
Has this issue been resolved? Are you using the correct rules for your platform?

**Comment by InverseRE** [comment]
LightSPD SO rules are not compiled for the targeted platform (not supported).
