### ISSUE TITLE
snort.lua port address incorrect for udp cip port

### ISSUE THREAD

**Issue by animator-ra** [snort3/snort3#318]
In the snort.lua file, the binder for cip is assigned 22222/udp.  The correct port number is 2222/udp
https://www[.]iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=40

wizard = default_wizard

binder =
{
    -- port bindings required for protocols without wizard support
    { when = { proto = 'udp', ports = '53', role='server' },  use = { type = 'dns' } },
    { when = { proto = 'tcp', ports = '53', role='server' },  use = { type = 'dns' } },
    { when = { proto = 'tcp', ports = '111', role='server' }, use = { type = 'rpc_decode' } },
    { when = { proto = 'tcp', ports = '502', role='server' }, use = { type = 'modbus' } },
    { when = { proto = 'tcp', ports = '2123 2152 3386', role='server' }, use = { type = 'gtp_inspect' } },
    { when = { proto = 'tcp', ports = '2404', role='server' }, use = { type = 'iec104' } },
    `{ when = { proto = 'udp', ports = '22222', role = 'server' }, use = { type = 'cip' } },`
    { when = { proto = 'tcp', ports = '44818', role = 'server' }, use = { type = 'cip' } },

**Comment by matirko** [comment]
This has been fixed, and will be present in the next release. Thank you again for reporting the issue!

**Comment by Priyanka-Gurudev** [comment]
Fix available from 3.1.67.0 onwards
