### ISSUE TITLE
Cannot be compiled on Linux Fedora 38

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [snort3/snort3#319]
here is the result after make install 

[ 19%] Building CXX object src/packet_io/CMakeFiles/packet_io.dir/sfdaq_config.cc.o
In file included from /home/src/snort3/src/packet_io/sfdaq_config.cc:25:
/home/src/snort3/src/packet_io/sfdaq_config.h:59:25: error: ‘uint32_t’ has not been declared
   59 |     void set_batch_size(uint32_t);
      |                         ^~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.h:62:5: error: ‘uint32_t’ does not name a type
   62 |     uint32_t get_batch_size() const { return (batch_size == BATCH_SIZE_UNSET) ? BATCH_SIZE_DEFAULT : batch_size; }
      |     ^~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.h:26:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   25 | #include <vector>
  +++ |+#include <cstdint>
   26 |
/home/src/snort3/src/packet_io/sfdaq_config.h:63:5: error: ‘uint32_t’ does not name a type
   63 |     uint32_t get_mru_size() const { return (mru_size == SNAPLEN_UNSET) ? SNAPLEN_DEFAULT : mru_size; }
      |     ^~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.h:63:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/src/snort3/src/packet_io/sfdaq_config.h:71:5: error: ‘uint32_t’ does not name a type
   71 |     uint32_t batch_size;
      |     ^~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.h:71:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/src/snort3/src/packet_io/sfdaq_config.h:77:22: error: ‘uint32_t’ does not name a type
   77 |     static constexpr uint32_t BATCH_SIZE_UNSET = 0;
      |                      ^~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.h:77:22: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/src/snort3/src/packet_io/sfdaq_config.h:79:22: error: ‘uint32_t’ does not name a type
   79 |     static constexpr uint32_t BATCH_SIZE_DEFAULT = 64;
      |                      ^~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.h:79:22: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/src/snort3/src/packet_io/sfdaq_config.cc: In constructor ‘SFDAQConfig::SFDAQConfig()’:
/home/src/snort3/src/packet_io/sfdaq_config.cc:68:5: error: ‘batch_size’ was not declared in this scope; did you mean ‘set_batch_size’?
   68 |     batch_size = BATCH_SIZE_UNSET;
      |     ^~~~~~~~~~
      |     set_batch_size
/home/src/snort3/src/packet_io/sfdaq_config.cc:68:18: error: ‘BATCH_SIZE_UNSET’ was not declared in this scope
   68 |     batch_size = BATCH_SIZE_UNSET;
      |                  ^~~~~~~~~~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.cc: At global scope:
/home/src/snort3/src/packet_io/sfdaq_config.cc:99:6: error: variable or field ‘set_batch_size’ declared void
   99 | void SFDAQConfig::set_batch_size(uint32_t batch_size_value)
      |      ^~~~~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.cc:99:34: error: ‘uint32_t’ was not declared in this scope
   99 | void SFDAQConfig::set_batch_size(uint32_t batch_size_value)
      |                                  ^~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.cc:26:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   25 | #include "sfdaq_config.h"
  +++ |+#include <cstdint>
   26 |
/home/src/snort3/src/packet_io/sfdaq_config.cc: In member function ‘void SFDAQConfig::overlay(const SFDAQConfig*)’:
/home/src/snort3/src/packet_io/sfdaq_config.cc:126:16: error: ‘const struct SFDAQConfig’ has no member named ‘batch_size’; did you mean ‘set_batch_size’?
  126 |     if (other->batch_size != BATCH_SIZE_UNSET)
      |                ^~~~~~~~~~
      |                set_batch_size
/home/src/snort3/src/packet_io/sfdaq_config.cc:126:30: error: ‘BATCH_SIZE_UNSET’ was not declared in this scope
  126 |     if (other->batch_size != BATCH_SIZE_UNSET)
      |                              ^~~~~~~~~~~~~~~~
/home/src/snort3/src/packet_io/sfdaq_config.cc:127:9: error: ‘batch_size’ was not declared in this scope; did you mean ‘set_batch_size’?
  127 |         batch_size = other->batch_size;
      |         ^~~~~~~~~~
      |         set_batch_size
/home/src/snort3/src/packet_io/sfdaq_config.cc:127:29: error: ‘const struct SFDAQConfig’ has no member named ‘batch_size’; did you mean ‘set_batch_size’?
  127 |         batch_size = other->batch_size;
      |                             ^~~~~~~~~~
      |                             set_batch_size
make[2]: *** [src/packet_io/CMakeFiles/packet_io.dir/build.make:104: src/packet_io/CMakeFiles/packet_io.dir/sfdaq_config.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3419: src/packet_io/CMakeFiles/packet_io.dir/all] Error 2

**Comment by allewi** [comment]
Thanks for reporting this issue. We will investigate it and get back to you.

**Comment by allewi** [comment]
Are you using workstation or server?
