### ISSUE TITLE
not able to generate alert for mms_data

### ISSUE THREAD

**Issue by biswajitutil** [snort3/snort3#323]
Hi,
I am using snort3 and trying to detect mms protocol. I am not able to generate any alert for the protocol. Please suggest where I am doing mistakes.

I have attached my configuration and output log seen.

Rules using

/usr/local/etc/rules/local.rules

alert tcp ( \
msg: "PROTOCOL-SCADA MMS Initiate-Request"; \
flow: to_server, established; \
mms_data; \
content:"|A8|", depth 1; \
sid:1000000; \
)

[MMS PCAP ](https://github.com/ITI/ICS-Security-Tools/blob/master/pcaps/IEC61850/MMS%20-%20Specific%20Commands/iec61850_write.pcap)
[mms_console_log.txt](https://github.com/snort3/snort3/files/12316126/mms_console_log.txt)
[snort.lua.txt](https://github.com/snort3/snort3/files/12316154/snort.lua.txt)
)

**Comment by VytalyGorbatov** [comment]
Hi @biswajitutil,

in your traffic the server uses port 102, which is not typical for MMS. Unfortunately, you end up on the s7commplus port binding: `126  { when = { proto = 'tcp', ports = '102', role = 'server' }, use = { type = 's7commplus' } },` so there's no MMS service evaluation going on, and therefore you don't have the mms_data buffer.

You can upgrade your snort3 to >= 3.1.44.0, from there the s7commplus port binding has been changed to wizard curse and your rule works as expected.

**Comment by biswajitutil** [comment]
Yes you are right. I disabled all protocol and only kept the below part, and it worked fine.

-- enable the mms wizard support
wizard = { curses = {'mms'}, }
-- enable the mms service inspector
mms = { }
-- add the mms binder entry
binder =
{
    { when = { service = 'mms' },              use = { type = 'mms' } },
    { use = { type = 'wizard' } }
}

Thanks
