### ISSUE TITLE
OSS-Fuzz Integration

### ISSUE THREAD

**Issue by capuanob** [snort3/snort3#324]
Hello,

I have submitted this repository to OSS-Fuzz to gauge the committee's interest in incorporating snort3 into their continuous fuzzing program. Before beginning my research and implementation, I wanted to ensure that this is something that the snort3 development team would be supportive of.

If so, what is a good email to list as an automatic CC for security-critical bug reports that may come up during fuzzing?

Thank you for your consideration and I hope to contribute to this project!

**Comment by snortadmin** [comment]
Hey Bailey,

Sure! Report any issues to ***@***.***

Russ

________________________________
From: Bailey Capuano ***@***.***>
Sent: Wednesday, September 27, 2023 11:26 PM
To: snort3/snort3 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [snort3/snort3] OSS-Fuzz Integration (Issue #324)


Hello,

I have submitted this repository to OSS-Fuzz to gauge the committee's interest in incorporating snort3 into their continuous fuzzing program. Before beginning my research and implementation, I wanted to ensure that this is something that the snort3 development team would be supportive of.

If so, what is a good email to list as an automatic CC for security-critical bug reports that may come up during fuzzing?

Thank you for your consideration and I hope to contribute to this project!

**Comment by capuanob** [comment]
@snortadmin 

Hey Russ, the email you sent was asterisked out. I currently have the email derived from source code for you listed in the project.yaml [here](https://github.com/google/oss-fuzz/pull/11000/files). Is this a good email?

**Comment by snortadmin** [comment]
I edited the response above. You can find the email at the bottom of this page:

https://snort.org/community#submit_bug
