### ISSUE TITLE
when I build snor3 ,the js_norm/pdf_tokenizer.cc file has error 

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [snort3/snort3#329]
![image](https://github.com/snort3/snort3/assets/28779327/d5c64b67-1167-4ded-94a9-e10bbf1fa25f)

**Comment by wangwenqiangGitHub** [comment]
![image](https://github.com/snort3/snort3/assets/28779327/9b959d31-a91e-454b-9001-337dfd7162db)

**Comment by wangwenqiangGitHub** [comment]
when i change the error, the build connitue util this error:
![image](https://github.com/snort3/snort3/assets/28779327/dfbcc4ce-f128-4bc8-b8fa-9691a9100e79)

**Comment by AnnaNorokh** [comment]
Hi @wangwenqiangGitHub  could you please share your FlexLexer version and your OS ?

**Comment by wangwenqiangGitHub** [comment]
> Hi @wangwenqiangGitHub could you please share your FlexLexer version and your OS ?


flex --version
flex 2.6.4

aarch64-linux-gnu-gcc --version
aarch64-linux-gnu-gcc (Linaro GCC 7.3-2018.05) 7.3.1 20180425 [linaro-7.3-2018.05 revision d29120a424ecfbc167ef90065c0eeb7f91977701]
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

**Comment by wangwenqiangGitHub** [comment]
I find this is flex problem ,  When I change to use flex master branch code , will solve this error, Sorry for the trouble, thank you for your answer
