### ISSUE TITLE
Using mSplit Parse Config File

### ISSUE THREAD

**Issue by JonlyLinux** [snort3/snort3#33]
Hi.
I write a test case for mSplit function, And
When parsing string by mSplit, it will not work right.
The test case core codes:
      const char *str = "\\a:\\b:\\c:\\d";
      const char *sep_chars = "abcd:";
      const int max_toks = 0,
      int num_toks = 0;
      const char meta_char = '\\';
	char ** strTable = mSplit(str, sep_chars, max_toks, &num_toks, meta_char);
	for (int i = 0; i < num_toks; i)
		printf("%s\n", strTable[i]);

Ouput:
      a
     \\
     \\
     \\
Expect:
     a
     b
     c
     d
Reason:
			if cur_tok >= 1, the function works not good.
			Because when do the second or more split, mSplit will exec this code.
			line: 236-251  
			/* Move past initial separator characters and whitespace */
			for (i = 0; i < strlen(str); i++)
			{
				for (j = 0; j < strlen(sep_chars); j++)
				{
					if ((str[i] == sep_chars[j]) ||
						isspace((int)str[i]))
					{
						break;
					}
				}

				/* Not a separator character or whitespace */
				if (j == strlen(sep_chars))
					break;
			}
			
			And then, i++
			line: 190
			for (i = 0; i < strlen(str); i++)
			
			mSplit ignored the 'escaped' character's function, 
			And treat the 'escaped' character as a normal character.

Fix:
	Modify line: 330:
	[-] tok_start = i; 
	[+] tok_start = i--;

**Comment by InverseRE** [comment]
There is no mSplit function in Snort3 anymore.
