### ISSUE TITLE
new build of snort3  on rocky9 SIGABRT (6) core dumps 

### ISSUE THREAD

**Issue by dcecchino** [snort3/snort3#330]
Hello,

I am able to start snort with the snort_defaults.lua configuration file, but when I start it with the (snort.lua) configuration it doesn't come up 

# cat /etc/redhat-release
Rocky Linux release 9.3 (Blue Onyx)

#  /usr/local/bin/snort -A Full -i ens192 -c /usr/local/etc/snort/snort.lua  -l /var/log/snort   -v
--------------------------------------------------
o")~   Snort++ 3.1.28.0
--------------------------------------------------
Loading /usr/local/etc/snort/snort.lua:
Loading snort_defaults.lua:
Finished snort_defaults.lua:
Loading file_magic.lua:
Finished file_magic.lua:
        Lua Allowlist Keywords for /usr/local/etc/snort/snort.lua:
                default_classifications, default_ftp_server, default_gtp,
                default_hi_port_scan, default_http_inspect, default_js_norm_ident_ignore,
                default_low_port_scan, default_med_port_scan, default_references,
                default_smtp, default_variables, default_wizard, file_magic,
                ftp_command_specs, gtp_v0_info, gtp_v0_msg, gtp_v1_info, gtp_v1_msg,
                gtp_v2_info, gtp_v2_msg, http_methods, icmp_hi_sweep, icmp_low_sweep,
                icmp_med_sweep, ip_hi_decoy, ip_hi_dist, ip_hi_proto, ip_hi_sweep,
                ip_low_decoy, ip_low_dist, ip_low_proto, ip_low_sweep, ip_med_decoy,
                ip_med_dist, ip_med_proto, ip_med_sweep, netflow_versions, sip_requests,
                smtp_default_alt_max_command_lines, tcp_hi_decoy, tcp_hi_dist, tcp_hi_ports,
                tcp_hi_sweep, tcp_low_decoy, tcp_low_dist, tcp_low_ports, tcp_low_sweep,
                tcp_med_decoy, tcp_med_dist, tcp_med_ports, tcp_med_sweep, telnet_commands,
                udp_hi_decoy, udp_hi_dist, udp_hi_ports, udp_hi_sweep, udp_low_decoy,
                udp_low_dist, udp_low_ports, udp_low_sweep, udp_med_decoy, udp_med_dist,
                udp_med_ports, udp_med_sweep
        active
        alerts
        daq
        decode
        host_cache
        host_tracker
        hosts
        network
        packets
        process
        search_engine
        so_proxy
        stream
        stream_icmp
        stream_udp
        stream_file
        back_orifice
        netflow
        normalizer
        pop
        rpc_decode
        sip
        ssh
        ssl
        telnet
        cip
        dnp3
        iec104
        mms
        modbus
        s7commplus
        dce_smb
        dce_tcp
        dce_udp
        gtp_inspect
        port_scan
        ftp_server
        ftp_client
        ftp_data
        http_inspect
        http2_inspect
        appid
        wizard

Snort (PID 106872) caught fatal signal: SIGABRT (6)
Version: 3.1.28.0

Aborted (core dumped)

# cat snort.lua 

snort.lua
---------------------------------------------------------------------------
-- Snort++ configuration
---------------------------------------------------------------------------

-- there are over 200 modules available to tune your policy.
-- many can be used with defaults w/o any explicit configuration.
-- use this conf as a template for your specific configuration.

-- 1. configure defaults
-- 2. configure inspection
-- 3. configure bindings
-- 4. configure performance
-- 5. configure detection
-- 6. configure filters
-- 7. configure outputs
-- 8. configure tweaks

---------------------------------------------------------------------------
-- 1. configure defaults
---------------------------------------------------------------------------

-- HOME_NET and EXTERNAL_NET must be set now
-- setup the network addresses you are protecting
HOME_NET = '192.168.1.20/32'

-- set up the external network addresses.
-- (leave as "any" in most situations)
EXTERNAL_NET = 'any'

include 'snort_defaults.lua'
include 'file_magic.lua'

stream = { }
stream_ip = { }
stream_icmp = { }
stream_tcp = { }
stream_udp = { }
stream_user = { }
stream_file = { }

arp_spoof = { }
back_orifice = { }
dns = { }
imap = { }
netflow = {}
normalizer = { }
pop = { }
rpc_decode = { }
sip = { }
ssh = { }
ssl = { }
telnet = { }

cip = { }
dnp3 = { }
iec104 = { }
mms = { }
modbus = { }
s7commplus = { }

dce_smb = { }
dce_tcp = { }
dce_udp = { }
dce_http_proxy = { }
dce_http_server = { }

-- see snort_defaults.lua for default_*
gtp_inspect = default_gtp
port_scan = default_med_port_scan
smtp = default_smtp

ftp_server = default_ftp_server
ftp_client = { }
ftp_data = { }

http_inspect = default_http_inspect
http2_inspect = { }

-- see file_magic.lua for file id rules
file_id = { file_rules = file_magic }
file_policy = { }

-- the following require additional configuration to be fully effective:

appid =
{
    -- appid requires this to use appids in rules
    app_detector_dir = '/usr/local/lib',
        log_stats = true,
}
wizard = default_wizard

binder =
{
    -- port bindings required for protocols without wizard support
    { when = { proto = 'udp', ports = '53', role='server' },  use = { type = 'dns' } },
    { when = { proto = 'tcp', ports = '53', role='server' },  use = { type = 'dns' } },
    { when = { proto = 'tcp', ports = '102', role = 'server' }, use = { type = 's7commplus' } },
    { when = { proto = 'tcp', ports = '111', role='server' }, use = { type = 'rpc_decode' } },
    { when = { proto = 'tcp', ports = '502', role='server' }, use = { type = 'modbus' } },
    { when = { proto = 'tcp', ports = '2123 2152 3386', role='server' }, use = { type = 'gtp_inspect' } },
    { when = { proto = 'tcp', ports = '2404', role='server' }, use = { type = 'iec104' } },
    { when = { proto = 'udp', ports = '22222', role = 'server' }, use = { type = 'cip' } },
    { when = { proto = 'tcp', ports = '44818', role = 'server' }, use = { type = 'cip' } },

    { when = { proto = 'tcp', service = 'dcerpc' },  use = { type = 'dce_tcp' } },
    { when = { proto = 'udp', service = 'dcerpc' },  use = { type = 'dce_udp' } },
    { when = { proto = 'udp', service = 'netflow' }, use = { type = 'netflow' } },

    { when = { service = 'netbios-ssn' },      use = { type = 'dce_smb' } },
    { when = { service = 'dce_http_server' },  use = { type = 'dce_http_server' } },
    { when = { service = 'dce_http_proxy' },   use = { type = 'dce_http_proxy' } },

    { when = { service = 'cip' },              use = { type = 'cip' } },
    { when = { service = 'dnp3' },             use = { type = 'dnp3' } },
    { when = { service = 'dns' },              use = { type = 'dns' } },
    { when = { service = 'ftp' },              use = { type = 'ftp_server' } },
    { when = { service = 'ftp-data' },         use = { type = 'ftp_data' } },
    { when = { service = 'gtp' },              use = { type = 'gtp_inspect' } },
    { when = { service = 'imap' },             use = { type = 'imap' } },
    { when = { service = 'http' },             use = { type = 'http_inspect' } },
    { when = { service = 'http2' },            use = { type = 'http2_inspect' } },
    { when = { service = 'iec104' },           use = { type = 'iec104' } },
    { when = { service = 'mms' },              use = { type = 'mms' } },
    { when = { service = 'modbus' },           use = { type = 'modbus' } },
    { when = { service = 'pop3' },             use = { type = 'pop' } },
    { when = { service = 'ssh' },              use = { type = 'ssh' } },
    { when = { service = 'sip' },              use = { type = 'sip' } },
    { when = { service = 'smtp' },             use = { type = 'smtp' } },
    { when = { service = 'ssl' },              use = { type = 'ssl' } },
    { when = { service = 'sunrpc' },           use = { type = 'rpc_decode' } },
    { when = { service = 's7commplus' },       use = { type = 's7commplus' } },
    { when = { service = 'telnet' },           use = { type = 'telnet' } },

    { use = { type = 'wizard' } }
}

references = default_references
classifications = default_classifications

ips =
{
    -- use this to enable decoder and inspector alerts
    --enable_builtin_rules = true,

    -- use include for rules files; be sure to set your path
    -- note that rules files can include other rules files
    -- (see also related path vars at the top of snort_defaults.lua)

    mode = inline,
        variables = default_variables,
    rules = [[
    include /usr/local/etc/rules/snort3-community-rules/snort3-community.rules
    ]]

}

alert_fast = {
        file = true,
        packet = false,
        limit = 10,
}

if ( tweaks ~= nil ) then
    include(tweaks .. '.lua')
end

**Comment by dcecchino** [comment]
]# gdb /usr/local/bin/snort
GNU gdb (GDB) Rocky Linux 10.2-11.el9
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/snort...
(gdb)  r  -i ens192 -c /usr/local/etc/snort/snort.lua  -l /var/log/snort  -i ens192 -D
Starting program: /usr/local/bin/snort -i ens192 -c /usr/local/etc/snort/snort.lua  -l /var/log/snort  -i ens192 -D

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

--------------------------------------------------
o")~   Snort++ 3.1.28.0
--------------------------------------------------
Loading /usr/local/etc/snort/snort.lua:
Loading snort_defaults.lua:
Finished snort_defaults.lua:
Loading file_magic.lua:
Finished file_magic.lua:
        ftp_client
        file_policy
        references
        alert_fast
        gtp_inspect
        classifications
        binder

Program received signal SIGABRT, Aborted.
0x00007ffff66a154c in __pthread_kill_implementation () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.34-83.el9.7.x86_64 hwloc-libs-2.4.1-5.el9.x86_64 libibverbs-46.0-1.el9.x86_64 libnl3-3.7.0-1.el9.x86_64 libuuid-2.37.4-15.el9.x86_64 openssl-libs-3.0.7-24.el9.x86_64 pcre-8.44-3.el9.3.x86_64 xz-libs-5.2.5-8.el9_0.x86_64 zlib-1.2.11-40.el9.x86_64

]# dnf debuginfo-install glibc-2.34-83.el9.7.x86_64 hwloc-libs-2.4.1-5.el9.x86_64 libibverbs-46.0-1.el9.x86_64 libnl3-3.7.0-1.el9.x86_64 libuuid-2.37.4-15.el9.x86_64 openssl-libs-3.0.7-24.el9.x86_64 pcre-8.44-3.el9.3.x86_64 xz-libs-5.2.5-8.el9_0.x86_64 zlib-1.2.11-40.el9.x86_64
enabling epel-debuginfo repository
enabling epel-cisco-openh264-debuginfo repository
Last metadata expiration check: 0:00:47 ago on Sat 25 Nov 2023 11:26:32 AM EST.
Could not find debuginfo package for the following installed packages: glibc-2.34-83.el9.7.x86_64, hwloc-libs-2.4.1-5.el9.x86_64, libibverbs-46.0-1.el9.x86_64, libnl3-3.7.0-1.el9.x86_64, libuuid-2.37.4-15.el9.x86_64, openssl-libs-1:3.0.7-24.el9.x86_64, pcre-8.44-3.el9.3.x86_64, xz-libs-5.2.5-8.el9_0.x86_64, zlib-1.2.11-40.el9.x86_64
Could not find debugsource package for the following installed packages: glibc-2.34-83.el9.7.x86_64, hwloc-libs-2.4.1-5.el9.x86_64, libibverbs-46.0-1.el9.x86_64, libnl3-3.7.0-1.el9.x86_64, libuuid-2.37.4-15.el9.x86_64, openssl-libs-1:3.0.7-24.el9.x86_64, pcre-8.44-3.el9.3.x86_64, xz-libs-5.2.5-8.el9_0.x86_64, zlib-1.2.11-40.el9.x86_64
Dependencies resolved.
Nothing to do.
Complete!

**Comment by dcecchino** [comment]
Okay odd behavior, I ran a loop and it finally started... any thoughts?


Snort (PID 39498) caught fatal signal: SIGABRT (6)
Version: 3.1.28.0

Aborted (core dumped)
--------------------------------------------------
o")~   Snort++ 3.1.28.0
--------------------------------------------------
Loading /usr/local/etc/snort/snort.lua:
Loading snort_defaults.lua:
Finished snort_defaults.lua:
Loading file_magic.lua:
Finished file_magic.lua:
        ftp_data
        http_inspect
        http2_inspect
        file_policy
        appid
        wizard

Snort (PID 39504) caught fatal signal: SIGABRT (6)
Version: 3.1.28.0

Aborted (core dumped)
--------------------------------------------------
o")~   Snort++ 3.1.28.0
--------------------------------------------------
Loading /usr/local/etc/snort/snort.lua:
Loading snort_defaults.lua:
Finished snort_defaults.lua:
Loading file_magic.lua:
Finished file_magic.lua:
        alert_fast
        trace
        file_policy
        dce_smb
        binder
        wizard
        appid
        file_id
        http2_inspect
        http_inspect
        ftp_data
        ftp_client
        ftp_server
        smtp
        port_scan
        gtp_inspect
        dce_http_server
        dce_udp
        ips
        modbus
        iec104
        cip
        ssl
        sip
        active
        alerts
        daq
        decode
        host_cache
        host_tracker
        hosts
        network
        packets
        process
        search_engine
        pop
        stream
        stream_ip
        stream_icmp
        stream_tcp
        stream_udp
        stream_user
        stream_file
        arp_spoof
        back_orifice
        dns
        imap
        netflow
        normalizer
        rpc_decode
        ssh
        telnet
        dnp3
        mms
        s7commplus
        dce_tcp
        dce_http_proxy
        so_proxy
        output
        references
        classifications
Finished /usr/local/etc/snort/snort.lua:
Loading ips.rules:
Loading /usr/local/etc/rules/snort3-community-rules/snort3-community.rules:
Finished /usr/local/etc/rules/snort3-community-rules/snort3-community.rules:
Finished ips.rules:
--------------------------------------------------
ips policies rule stats
              id  loaded  shared enabled    file
               0    4024       0    4024    /usr/local/etc/snort/snort.lua
--------------------------------------------------
rule counts
       total rules loaded: 4024
               text rules: 4024
            option chains: 4024
            chain headers: 317
                 flowbits: 48
     flowbits not checked: 23
--------------------------------------------------
port rule counts
             tcp     udp    icmp      ip
     any     473      58     147      22
     src     177      17       0       0
     dst     778     153       0       0
    both       6      11       0       0
   total    1434     239     147      22
--------------------------------------------------
service rule counts          to-srv  to-cli
                   dcerpc:        7       4
                     dhcp:        2       2
                      dns:       28       7
                      ftp:       90       4
                 ftp-data:        1      97
                     http:     2085     256
                    http2:     2085     256
                     imap:       35     118
                      irc:        5       2
                 kerberos:        5       0
                     ldap:        0       1
                    mysql:        3       0
              netbios-dgm:        1       1
               netbios-ns:        4       3
              netbios-ssn:       69      17
                     nntp:        2       0
                     pop3:       23     118
                      rdp:        5       0
                      sip:        5       5
                     smtp:      130       2
                     snmp:       18       7
                     ssdp:        3       0
                      ssl:       20      42
                   sunrpc:       68       4
                   telnet:       12       6
                     tftp:        1       0
                     wins:        1       0
                    total:     4708     952
--------------------------------------------------
fast pattern groups
                      src: 59
                      dst: 158
                      any: 4
                to_server: 47
                to_client: 34
--------------------------------------------------
search engine
                instances: 302
                 patterns: 7522
            pattern chars: 122098
               num states: 82566
         num match states: 7154
             memory scale: MB
             total memory: 2.58907
           pattern memory: 0.403095
        match list memory: 0.91655
        transition memory: 1.23256
        fast pattern only: 4971
--------------------------------------------------
pcap DAQ configured to passive.
Commencing packet processing
++ [0] ens192

**Comment by matirko** [comment]
Do you mind sharing how you're building Snort? Are you building with `ENABLE_DEBUG`? If so, that could potentially cause Snort to be hitting some `assert()` and raising `SIGABORT`

Also, can you provide a longer backtrace from the core it generated (is __pthread_kill_implementation all it shows, or are there more stack frames output by gdb?) Thanks!

**Comment by dcecchino** [comment]
Jan  7 07:30:03 zeus snort[87593]: [1:404:14] "PROTOCOL-ICMP Destination Unreachable Protocol Unreachable" [Classification: Misc activity] [Priority: 3] {ICMP} 70.184.244.197 -> 70.184.244.193
Jan  7 07:30:04 zeus snort[87593]: [1:404:14] "PROTOCOL-ICMP Destination Unreachable Protocol Unreachable" [Classification: Misc activity] [Priority: 3] {ICMP} 70.184.244.197 -> 70.184.244.193
Jan  7 07:30:04 zeus rc.local[87593]: FATAL: OpenAlertFile() => fopen() alert file ./appid_stats.log: Permission denied
Jan  7 07:30:04 zeus rc.local[87593]: Fatal Error, Quitting..
Jan  7 07:30:04 zeus rc.local[87593]: Snort (PID 87593) caught fatal signal: SIGABRT (6)
Jan  7 07:30:04 zeus rc.local[87593]: Version: 3.1.28.0
Jan  7 07:30:04 zeus rc.local[87593]: = Current DAQ Message (Type 1) =
Jan  7 07:30:04 zeus rc.local[87593]: == Header (56) ==
Jan  7 07:30:04 zeus rc.local[87593]: 4c99 9a65 0000 0000 3dd5 0900 0000 0000
Jan  7 07:30:04 zeus rc.local[87593]: 8900 0000 ffff ffff ffff ffff ffff ffff
Jan  7 07:30:04 zeus rc.local[87593]: 0000 0000 0000 0000 0000 0000 0000 0000
Jan  7 07:30:04 zeus rc.local[87593]: 0000 0000 0000 0000
Jan  7 07:30:04 zeus rc.local[87593]: == Data (137) ==
Jan  7 07:30:04 zeus rc.local[87593]: 0050 56b3 9e90 006b f146 14b1 0800 4500
Jan  7 07:30:04 zeus rc.local[87593]: 007b 0000 4000 ff2f 045c 46b8 f4c1 46b8
Jan  7 07:30:04 zeus rc.local[87593]: f4c5 1000 88be 7540 897c 1001 0064 0000
Jan  7 07:30:04 zeus rc.local[87593]: 0000 84b5 9cf8 0007 006b f146 1470 0800
Jan  7 07:30:04 zeus rc.local[87593]: 4500 0049 a9b0 4000 3f11 4060 6c12 d975
Jan  7 07:30:04 zeus rc.local[87593]: 0808 0404 bd82 0035 0035 fbcc aadc 0100
Jan  7 07:30:04 zeus rc.local[87593]: 0001 0000 0000 0000 0a69 6164 7663 656e
Jan  7 07:30:04 zeus rc.local[87593]: 7465 720c 6963 6e73 6f6c 7574 696f 6e73
Jan  7 07:30:04 zeus rc.local[87593]: 036e 6574 0000 1c00 01
Jan  7 07:30:04 zeus systemd[1]: Started Process Core Dump (PID 87641/UID 0).

**Comment by dcecchino** [comment]
I'm not sure where its trying to access the appid_stats.log, I have to -l /var/log option  in the cli

**Comment by Crowy-o** [comment]
Hello, crash is definitely an issue. We'll handle that part.
Regarding why it trying to create in no specified location - I'm not sure, I tested 3.1.77.0 and path looks correct.

In any case, once the issue will be handled, try again.

**Comment by Crowy-o** [comment]
[dcecchino](https://github.com/dcecchino) hello, the fix should be in 3.1.81.0

**Comment by InverseRE** [comment]
The fix should be available now.
@dcecchino feel free to reopen the issue if it still persists for you

**Comment by dcecchino** [comment]
Thank you! Sent from my iPhoneOn Feb 20, 2024, at 4:31 PM, InverseRE ***@***.***> wrote:﻿
The fix should be available now.
@dcecchino feel free to reopen the issue if it still persists for you
