### ISSUE TITLE
ERROR: /etc/snort/snort.lua: failed to parse the IP address: !$HOME_NET.

### ISSUE THREAD

**Issue by metavalent** [snort3/snort3#332]
A couple of days banging my head against this one. Issues, Forums, ChatGPT (lol), etc.

Total n00b to this, though seems a bit redundant to have same two lines is snort.lua and homenet.lua? Probably I'm missing something obvious, as usual. Grateful for guidance.

Relevant snippets:

```
System:
-------
OpenWrt 23.05.0 r23497-6637af95aa / LuCI openwrt-23.05 branch git-23.236.53405-fc638c8
```

```
   ,,_     -*> Snort++ <*-
  o"  )~   Version 3.1.61.0
   ''''    By Martin Roesch & The Snort Team
           http://snort.org/contact#team
           Copyright (C) 2014-2023 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using DAQ version 3.0.11
           Using LuaJIT version 2.1.0-beta3
           Using OpenSSL 3.0.12 24 Oct 2023
           Using libpcap version 1.10.4 (with TPACKET_V3)
           Using PCRE version 8.45 2021-06-15
           Using ZLIB version 1.2.13

```
```
./start_snort.sh
--------------------------------------------------
o")~   Snort++ 3.1.61.0
--------------------------------------------------
Loading /etc/snort/snort.lua:
Loading homenet.lua:
Finished homenet.lua:
Loading snort_defaults.lua:
Finished snort_defaults.lua:
	ips
ERROR: /etc/snort/snort.lua: failed to parse the IP address: !$HOME_NET.
	dce_http_proxy
```

```
snort.lua 
-------

---------------------------------------------------------------------------
-- 1. configure defaults
---------------------------------------------------------------------------

-- HOME_NET and EXTERNAL_NET must be set now
-- setup the network addresses you are protecting
-- we set HOME_NET and EXTERNAL_NET here or via an included file
-- set up the external network addresses.
-- (leave as "any" in most situations)

HOME_NET = [[ 10.10.11.11/29 ]]
EXTERNAL_NET = '!$HOME_NET'

include 'homenet.lua'
include 'snort_defaults.lua'

RULES_PATH = '/etc/snort/rules/'
BUILTIN_RULE_PATH = '/etc/snort/builtin_rules'
PLUGIN_RULE_PATH = '/etc/snort/so_rules'

```

```
homenet.lua
-------

- setup HOME_NET below with your IP range/ranges to protect
HOME_NET = [[ 10.10.11.11/29 ]]
EXTERNAL_NET = '!$HOME_NET'

```

**Comment by matirko** [comment]
Did you add `include 'homenet.lua'` to snort.lua? I might be missing something, but from what I can tell, we don't include that in [the default snort.lua](https://github.com/snort3/snort3/blob/master/lua/snort.lua). It's possible this is specific to OpenWRT though. I think that `include` can probably be removed along with the re-definitions of the variables.

 
I just tested this locally, adding the `HOME_NET` and `EXTERNAL_NET` you're using to both snort.lua, and a newly-included homenet.lua, and Snort seems to come up fine. As a test, can you try changing from `EXTERNAL_NET = '!$HOME_NET'` to `EXTERNAL_NET = 'any'`, just to see if that works?

**Comment by metavalent** [comment]
Yay! I'd tried `'any'` earlier, but that was before squashing a few other bugs. Removing the `include` and switching back to `'any'` worked this time. Thank you matirko!

**Comment by metavalent** [comment]
Ha! This is why we live for this stuff. It seems`'any'` apparently means **_any_** so snort also blocked direct `ssh` access? Maybe I've got it all wrong. What I do know is that the hopes of the output of the previous post derived from ...

`start_snort.sh' which is actually:

`snort -d -e -i eth0 -c /etc/snort/snort.lua --daq-dir /usr/lib/daq `

... as hopes were crushed by:

`/etc/init.d/snort start && /etc/init.d/snort enable`

I lost `ssh` access. LOL. 

**Recovery**

1. Restored most recent backup.
2. Copypasta'd local snort.lua to restored snort.lua (see below).<sup>1</sup>
3. Changed `'any'` back to `'!$HOME_NET'`.
4. Ran `snort -d -e -i eth0 -c /etc/snort/snort.lua --daq-dir /usr/lib/daq ` and got the same `failed to parse the IP address: $HOME_NET.` error.
5. Crossed fingers and ran `/etc/init.d/snort start && /etc/init.d/snort enable
`.
6. Ran `/etc/init.d/snort status` and received `running`.

As mentioned, I'm a n00b and don't even know what the snort command line options mean, just hacking one error at a time. I'm not satisfied with not understanding, but it seems to be part of the learning process. The goal someday will be true understanding gained along the way.

Since this is a snort on OpenWRT thread, I'll include a few details for potential future reference of others. One quirk of OpenWRT is when we restore the most recent backup (for my paranoia, like every 15 minutes) we still have to re-install additional `okpg` apps like snort3 all over again. [1] So you'll lose all config changes in that 15 minutes (which can be a lot!), so I often copypasta those changes over to a local file. 

**Next Mission**

How the heck to red-team myself by throwing some stuff at snort to know for sure it's working?

_P.S. Thanks again for the expertise and guidance! Remember, when it's not fun, go outside for a minute (or longer). Stretch. Get in a few reps. Drink more water. Keep reminding yourself, "I am dissolving all of the trauma ever accrued to this body and mind. Every single molecule. Every single synapse. I am happy. I am healthy. I am grateful. I am light. I am love." Okay, I'm projecting and preaching on that last part, as some preachers do, but hopefully the picture is received with the good will intended._

**Comment by InverseRE** [comment]
Starting from 3.1.78 `EXTERNAL_NET = '!$HOME_NET'` format will be supported as well.

**Comment by InverseRE** [comment]
Commit 40813cb enabled syntax like `EXTERNAL_NET = '!$HOME_NET'`

**Comment by leeclemens** [comment]
I thought I was hitting this same issue, but using 3.1.78:

```
HOME_NET = [[ 127.0.0.0/8 10.0.0.0/8 ]]
EXTERNAL_NET = '!$HOME_NET'
```

`Undefined variable in the string: $EXTERNAL_NET.`
