### ISSUE TITLE
Missing license file for src/catch/catch.hpp

### ISSUE THREAD

**Issue by puck** [snort3/snort3#333]
Hey,

I'm in the process of updating the Debian packages for Snort, and I've noticed that src/catch/catch.hpp is licensed by the Boost Software License, which requires that the license be provided along with the source, however the license is missing.

It looks to me like the content of https://www.boost.org/LICENSE_1_0.txt should be included in the src/catch directory (or another suitable location) within the Snort++ source.

Cheers,
Andrew

**Comment by InverseRE** [comment]
Fixed in 3.1.77 1bf89c3b468b2b9710d5082c954e2306e776aaa7

@puck Thanks for reporting the issue.
