### ISSUE TITLE
Variable link's problem blacklist, whitelist and rules

### ISSUE THREAD

**Issue by ptroms** [snort3/snort3#351]
Make the subject short. 

Snort3 only works following configuration.
Configuration file **snort.lua**:
```
...
file_id = { rules_file = '$RULE_PATH/snort3-community.rules' }
...
```
**snort_defaults.lua**
```
...
RULE_PATH = '/usr/local/snorty/etc/snort/rules/'
...
```
Test outcome:
_Snort successfully validated the configuration (with 0 warnings)._
However, according to the manual it should be:

```
file_id = { rules_file = '$RULE_PATH/snort3-community.rules' }
RULE_PATH = '/usr/local/snorty/etc/snort/rules'
```
Which in my case ends up the following error:
 _ERROR: /usr/local/snorty/etc/snort/rulessnort3-community.rules:1 unable to open rules file '/usr/local/snorty/etc/snort/rulessnort3-community.rules': No such file or directory_

Bypassing this problem, the same occurrences appear in blacklist/whitelist (reputation section). Here is even funnier.
Proper WHITE_LIST_PATH, and BLACK_LIST_PATH ends up in an error:
```
ERROR: /usr/local/snorty/etc/snort/snort.lua: can't find reputation.blacklist
ERROR: /usr/local/snorty/etc/snort/snort.lua: can't find reputation.whitelist
```
Software:
           -*> Snort++ <*-
           Version 3.1.82.0
           Using DAQ version 3.0.14
           Using LuaJIT version 2.1.1710088188
           Using OpenSSL 1.1.1n  15 Mar 2022
           Using libpcap version 1.8.1
           Using PCRE version 8.39 2016-06-14
           Using ZLIB version 1.2.11
           Using LZMA version 5.2.4

Any ideas, what would be the problem?

**Comment by kuceros** [comment]
The problem about 'reputation' config - you should use 'blocklist' instead of 'blacklist' and 'allowlist' instead of 'whitelist'. @stechew changed it...

**Comment by Crowy-o** [comment]
Hello, there's a bug in parsing of paths with variables where the next character after the name of path will be trimmed.
Our team will handle that, thanks

**Comment by ROBERT-MCDOWELL** [comment]
any news?

**Comment by Crowy-o** [comment]
Hello, we'll handle it at some point.

As for now, you can use workaround - just add an extra symbol.
So, as an example, for RULE_PATH, instead of '/usr/local/snorty/etc/snort/rules' -> use '/usr/local/snorty/etc/snort/rules/'

Without a bug, that should be concatenated to "...../snort/rules//snort3-community.rules". But due to the issue, the result looks like "...../snort/rules/snort3-community.rules", which is also fine.

**Comment by ROBERT-MCDOWELL** [comment]
@Crowy-o 
none of them worked but the suggestion of @kuceros worked.
I replaced whitelist and blacklist by allowlist and blocklist.
thanks
