### ISSUE TITLE
Segmentation fault snort3-Pulledpork3

### ISSUE THREAD

**Issue by PhucTran07Nov** [snort3/snort3#357]
![image](https://github.com/snort3/snort3/assets/142483435/1f49bfb8-d669-43d4-b31a-56d69f4aede1)

When I run it, the error "Segmentation fault" appears. I've found out what it is but it's not specific, please help me

**Comment by snortadmin** [comment]
3.1.18 is like 2.5 years old. Update to the latest and reopen if you are still crashing.
