### ISSUE TITLE
Snort 3.2.1.0 build error on openwrt aggregate 'SetNoCores

### ISSUE THREAD

**Issue by xxxx81** [snort3/snort3#369]
On openwrt the compilation aborts with the following error:

`/home/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.2.1.0/src/utils/util.cc: In function 'void SetNoCores()':
/home/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.2.1.0/src/utils/util.cc:88:19: error: aggregate 'SetNoCores()::rlimit rlim' has incomplete type and cannot be defined
   88 |     struct rlimit rlim;
      |                   ^~~~
/home/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.2.1.0/src/utils/util.cc:90:15: error: 'RLIMIT_CORE' was not declared in this scope
   90 |     getrlimit(RLIMIT_CORE, &rlim);
      |               ^~~~~~~~~~~
/home/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.2.1.0/src/utils/util.cc:90:5: error: 'getrlimit' was not declared in this scope; did you mean 'rlimit'?
   90 |     getrlimit(RLIMIT_CORE, &rlim);
      |     ^~~~~~~~~
      |     rlimit
/home/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.2.1.0/src/utils/util.cc:92:5: error: 'setrlimit' was not declared in this scope; did you mean 'rlimit'?
   92 |     setrlimit(RLIMIT_CORE, &rlim);
      |     ^~~~~~~~~
      |     rlimit`

**Comment by InverseRE** [comment]
Looks like #include <sys/resource.h> is missing.
Will take a look.

**Comment by Crowy-o** [comment]
Hello, fix for the issue should be available since 3.2.2.0

**Comment by xxxx81** [comment]
Snort 3.2.2.0 fixed the issue thanks.
