### ISSUE TITLE
Snort 3.2.2.0 openwrt build Linking CXX executable src/snort error

### ISSUE THREAD

**Issue by xxxx81** [snort3/snort3#371]
Snort 3.2.2.0 cannot be built on openwrt because the link with src/snort does not work.

`ninja: Entering directory `/home/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.2.2.0'
[1/86] Linking CXX executable src/snort
FAILED: src/snort
...
util.cc:(.text+0x8b): multiple definition of `SetNoCores()'; src/main/CMakeFiles/main.dir/process.cc.o:process.cc:(.text+0xeb8): first defined here
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[2]: *** [Makefile:146: /home/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.2.2.0/.built] Error 1
make[2]: Leaving directory '/home/openwrt/openwrt/feeds/packages/net/snort3'
time: package/feeds/packages/snort3/compile#0.28#0.13#0.41
    ERROR: package/feeds/packages/snort3 failed to build.
make[1]: *** [package/Makefile:129: package/feeds/packages/snort3/compile] Error 1
make[1]: Leaving directory '/home/openwrt/openwrt'
make: *** [/home/openwrt/openwrt/include/toplevel.mk:232: package/snort3/compile] Fehler 2
`

**Comment by Crowy-o** [comment]
Hello, our team will handle it.

As of now, you can add configuration option "--enable-corefiles" to force Snort be compiled without problematic function.
That shouldn't affect typical workflow, the difference will be visible only in case of crash.

Another way - manually delete extra function definition from util.cc:84-94

**Comment by xxxx81** [comment]
Thanks I have created a patch with your information that has fixed the problem I have now managed to compile an executable Snort so the other bug can also be closed.
