### ISSUE TITLE
How to Integrate VPP with Snort?

### ISSUE THREAD

**Issue by amirsalarpd74** [snort3/snort3#382]
The figure below mentions a section called 'VPP ZC DAQ' that establishes IPC communication between the VPP framework and Snort over a shared memory platform. I want your guidance on where to find this 'VPP ZC DAQ' section.

Thank you!

![next_generation_firewall](https://github.com/user-attachments/assets/2df949da-6f76-48cd-879e-c03f45636864)

**Comment by VytalyGorbatov** [comment]
Hey @amirsalarpd74!
In this context, `VPP ZC DAQ` is a specific plugin developed for VPP<->Snort data communication. DAQ stands for 'Data Acquisition', which is a tool that allows Snort to read packets from the data source. You can find VPP DAQ at https://github.com/FDio/vpp/tree/master/src/plugins/snort.

Also, I believe the guide you were reading (https://networkbuilders.intel.com/docs/networkbuilders/next-generation-firewall-optimizations-with-intel-xeon-scalable-processor-solution-brief-1676017799.pdf) provides a good usage example on page 23.

And, just a quick note, it's better to use [snort-users@lists.snort.org](mailto:snort-users@lists.snort.org) mailer thread for such questions, as it doesn't fit under the **_Issue_** definition and there's more people that can help you with such use-cases.
