### ISSUE TITLE
Does Snort3 currently support decoding Linux SLL packets in Snort2

### ISSUE THREAD

**Issue by wshe1** [snort3/snort3#386]
Does Snort3 currently support decoding Linux SLL packets? If there is no support for future integration plans.

**Comment by allewi** [comment]
Yes. See the README file in the Snort3_extras folder.



Albert Lewis

Email: ***@***.******@***.***>

________________________________
From: wshe1 ***@***.***>
Sent: Thursday, October 10, 2024 3:57 AM
To: snort3/snort3 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [snort3/snort3] Does Snort3 currently support decoding Linux SLL packets (Issue #386)


Does Snort3 currently support decoding Linux SLL packets? If there is no support for future integration plans.

**Comment by InverseRE** [comment]
Thanks, @allewi 


@wshe1 
https://github.com/snort3/snort3_extra/blob/master/src/codecs/cd_linux_sll/cd_linux_sll.cc

For now I'm closing the case. Feel free to reopen if you get more questions on this.
