### ISSUE TITLE
snort3 linker error 

### ISSUE THREAD

**Issue by kendallgreen** [snort3/snort3#388]
I get the following errors when building snort3 v3.3.7.0 on FreeBSD 14.1 with libdaq 3.0.16, libpcap 1.10.4-2 and pkgconf 2.3.0,1: ld: error: undefined symbol: std::__detail::_List_node_base::_M_unhook()
>>> referenced by stl_list.h:2016 (/usr/local/lib/gcc13/include/c++/bits/stl_list.h:2016)
>>>               libdaq_static_fst_la-daq_fst.o:(FlowStateTable::move_node_to_timeout_list(FstNode*, FstTimeoutList::ID)) in archive /usr/local/lib/libdaq_static_fst.a
>>> referenced by stl_list.h:2016 (/usr/local/lib/gcc13/include/c++/bits/stl_list.h:2016)
>>>               libdaq_static_fst_la-daq_fst.o:(FlowStateTable::extract_node(FstNode*)) in archive /usr/local/lib/libdaq_static_fst.a
>>> referenced by stl_list.h:2016 (/usr/local/lib/gcc13/include/c++/bits/stl_list.h:2016)
>>>               libdaq_static_fst_la-daq_fst.o:(FlowStateTable::extract_node(FstNode*)) in archive /usr/local/lib/libdaq_static_fst.a

ld: error: undefined symbol: std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)
>>> referenced by stl_list.h:2006 (/usr/local/lib/gcc13/include/c++/bits/stl_list.h:2006)
>>>               libdaq_static_fst_la-daq_fst.o:(FlowStateTable::move_node_to_timeout_list(FstNode*, FstTimeoutList::ID)) in archive /usr/local/lib/libdaq_static_fst.a
>>> referenced by stl_list.h:2006 (/usr/local/lib/gcc13/include/c++/bits/stl_list.h:2006)
>>>               libdaq_static_fst_la-daq_fst.o:(FlowStateTable::insert(FstKey const&, std::shared_ptr<FstEntry>)) in archive /usr/local/lib/libdaq_static_fst.a

ld: error: undefined symbol: std::__throw_bad_array_new_length()
>>> referenced by new_allocator.h:139 (/usr/local/lib/gcc13/include/c++/bits/new_allocator.h:139)
>>>               libdaq_static_fst_la-daq_fst.o:(FlowStateTable::extract_node(FstNode*)) in archive /usr/local/lib/libdaq_static_fst.a
>>> referenced by new_allocator.h:139 (/usr/local/lib/gcc13/include/c++/bits/new_allocator.h:139)
>>>               libdaq_static_fst_la-daq_fst.o:(void std::deque<_daq_msg const*, std::allocator<_daq_msg const*>>::_M_push_back_aux<_daq_msg const* const&>(_daq_msg const* const&)) in archive /

**Comment by xxxx81** [comment]
Try to build with libdaq 3.0.17 which was released at the same time. In my case it was due to an outdated Daq3 version.

**Comment by kendallgreen** [comment]
I downloaded libdaq 3.0.17

**Comment by kendallgreen** [comment]
But snort3 built with 3.0.16.  how do I force it to use the newer version

**Comment by xxxx81** [comment]
Unfortunately I can't help you, I have no idea about Freebsd, I'm using openwrt and it's best to ask in the Freebsd forum.

**Comment by matirko** [comment]
Did you rerun the entire libdaq build process and then rebuild Snort? If you share out your build steps I can take a look.

Also, if you're using the ports tree, it looks like right now [libdaq has its version set to 3.0.16](https://cgit.freebsd.org/ports/tree/net/libdaq/Makefile) so you'll have to manually use 3.0.17 if you wish to install from ports. I'll see if I can get that version bumped.

**Comment by kendallgreen** [comment]
after cloning libdaq3.0.17, I ran ./bootstrap ./configure --prefix=/usr/local/lib/daq_s3 sudo make and sudo make install.  I then moved to snort3 directory and ran /configure_cmake.sh --prefix=/usr/local/snort --enable-tcmalloc --with-daq-include=/usr/local/lib/daq_s3/bin --with-daq-include=/usr/local/lib/daq_s3/lib.
then I moved to build directory and ran sudo make but got the errors I reported.  It still reports using libdaq 3.0.16 from /usr/local/lib/daq_s3 directory

**Comment by kendallgreen** [comment]
I deleted libdaq and rebuild libdaq-3.0.17 and snort3. it compiled without error. Thanks.
