### ISSUE TITLE
The issue of multi-threaded CPU usage in Snort3

### ISSUE THREAD

**Issue by wshe1** [snort3/snort3#389]
hello：
I use the parameter '--max-packet-threads 4', and the CPU usage of snort3 is higher than that of the CPU that does not apply this parameter.
Are the packages captured by different threads in Snort3 duplicated? Is my command used correctly? What needs to be configured?
The command is as follows:
   sudo /usr/local/snort/bin/snort -i ens39  --plugin-path=/usr/local/snort/extra --max-packet-threads 4
--------------------------------------------------
o")~   Snort++ 3.3.7.0
--------------------------------------------------
--------------------------------------------------
pcap DAQ configured to passive.
Commencing packet processing
++ [0] ens39
++ [1] ens39
++ [2] ens39
++ [3] ens39

**Comment by InverseRE** [comment]
Roughly speaking, running snort in a single thread consumes 1 CPU core. Running in 4 threads consumes 4 CPU cores. Hence, more of total CPU usage.

LibDAQ defines the exact mechanism how packets from a single interface are spread across processing threads.

I'd suggest afpacket DAQ. For fine control see its `fanout_type` option.
AFAIK, libpcap (pcap DAQ) is not thread-safe (multiple threads on a single interface).

**Comment by InverseRE** [comment]
Not an issue in snort.

About snort usage, you can find more at snort-users@lists.snort.org (Snort-users mailing list):
https://lists.snort.org/mailman/listinfo/
