### ISSUE TITLE
Can't Find luajit! and I don't seem to be using --with-luajit-includes right

### ISSUE THREAD

**Issue by blasphemetheus** [snort3/snort3#392]
![image](https://github.com/user-attachments/assets/ee36e618-ac53-45df-aacb-fd5af5794ff6)
running whereis luajit returns -> luajit: /usr/local/bin/luajit
running luajit -> LuaJIT 2.1.1731601260 -- etc
![image](https://github.com/user-attachments/assets/7f6c9fc2-a922-49a1-9e68-a2ff93a447ec) is produced when running ./configure_cmake.sh

How do you properly direct this configure script to look at where LuaJIT is? LUAJIT_INCLUDE_DIR seems to be the variable that counts here. Is setting that variable enough?

In the  --with-luajit-includes part of the flag case statement in configure_cmake.sh it references LUAJIT_INCLUE_DIR_HINT. I don't suppose this has anything to do with it?

Any help here would be appreciated

**Comment by harshithsaiv** [comment]
1. Verify the exact location of the LuaJIT include files on your system by running this command:
-->   find /usr/local -name "luajit.h"

2. Try the configuration command to use the appropriate LUAJIT_INCLUDE_DIR 
 ./configure_cmake.sh --with-luajit-libraries=/usr/local/lib/luajit-5.1.a --with-luajit-includes= Updated dir
 
 Even after this if it shows the same error you can try to set the LUAJIT_INCLUDE_DIR environment variable and try
 --> export LUAJIT_INCLUDE_DIR= dir of lurajit
---> ./configure_cmake.sh

**Comment by blasphemetheus** [comment]
Ok, find /usr/local -name "luajit.h" -> returns /usr/local/include/luajit-2.1/luajit.h
that luajit-2.1 folder includes other .h files including lauxlib.h, luaconf.h lua.h, lua,hpp, lualib.h
/usr/local/lib contains libluajit-5.1.a and libluajit-5.1.so and libluajit-5.1.so.2 and libluajit-5.1.so.2.1.1731601260 -> 5.1 is version of lua I'm assuming and 2.1 is version of luajit?
/usr/local/bin contains the file luajit (the binary)

--with-luajit-libraries should look at /usr/local/lib/luajit-5.1.a and --with-luajit-includes should look at /usr/local/include/luajit-2.1, so let me try that

![image](https://github.com/user-attachments/assets/d98f017d-c93f-43f3-8696-3e4f538e7f22)
Yup, built. Thank you!

**Comment by blasphemetheus** [comment]
https://github.com/snort3/snort3/issues/92 Ran into this issue with libdaq.so.3 and libluajit-5.1.so.2 but the symlinking solution for each fixed both. Woo! 
![image](https://github.com/user-attachments/assets/78a8e92d-3a64-4942-9b4b-62ff2f58976f)
