### ISSUE TITLE
Logging and its proper configuration

### ISSUE THREAD

**Issue by ChrisRG711** [snort3/snort3#393]
Sorry for the newbie post. I have been struggling to get logging to work in a way that makes it easy to be consumed by the google agent installed on the vm. I thought the best way was to just use syslog but i cant get that configured so it doesnt error 
ERROR: /usr/local/etc/snort/snort.lua: invalid alert_syslog.facility = 'LOG_LOCAL1'
ERROR: /usr/local/etc/snort/snort.lua: can't find alert_syslog.short
ERROR: /usr/local/etc/snort/snort.lua: can't find alert_syslog.priority
ERROR: /usr/local/etc/snort/snort.lua: can't find alert_syslog.tag

**Im not seeing enough docs to point to what needs to be here***

I tried JSON etc but no luck. 

My end goal is to just log all SNORT logs to a specific log file that then GCP can pick up. I have seen lots of blogs but 90% of them are outdated or dont work.

Anyone out there feel like helping out a new guy?

**Comment by allewi** [comment]
Can you share your config file and the command being used to run snort please?



Albert Lewis

Email: ***@***.******@***.***>

________________________________
From: Chris ***@***.***>
Sent: Wednesday, December 11, 2024 5:24 PM
To: snort3/snort3 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [snort3/snort3] Logging and its proper configuration (Issue #393)


Sorry for the newbie post. I have been struggling to get logging to work in a way that makes it easy to be consumed by the google agent installed on the vm. I thought the best way was to just use syslog but i cant get that configured so it doesnt error
ERROR: /usr/local/etc/snort/snort.lua: invalid alert_syslog.facility = 'LOG_LOCAL1'
ERROR: /usr/local/etc/snort/snort.lua: can't find alert_syslog.short
ERROR: /usr/local/etc/snort/snort.lua: can't find alert_syslog.priority
ERROR: /usr/local/etc/snort/snort.lua: can't find alert_syslog.tag

Im not seeing enough docs to point to what needs to be here*

I tried JSON etc but no luck.

My end goal is to just log all SNORT logs to a specific log file that then GCP can pick up. I have seen lots of blogs but 90% of them are outdated or dont work.

Anyone out there feel like helping out a new guy?

**Comment by ChrisRG711** [comment]
thank you very much for your response. I do appreciate it. 
[snort(1).lua.txt](https://github.com/user-attachments/files/18111306/snort.1.lua.txt)

sudo snort -c /usr/local/etc/snort/snort.lua

if you have any good articles to use that help with this. I tired a few an none worked. I almost had it but then found out i was using snort 2.9

**Comment by InverseRE** [comment]
Feel free to re-open if you get more questions on this.
