### ISSUE TITLE
Reload via HUP fails and finally Segmentation fault

### ISSUE THREAD

**Issue by serg-ku** [snort3/snort3#42]
I'm trying to test snort++, It's version 3.0.0-243
I'm testing react action, but this is also happens with reject action.
IPS inline mode, NFQ dac, snort starts correctly, loads rules and sending react messages to clients as expected, but after sending -HUP to snort process it's reloading incorrectly, it doesn't load react {} and reject {} sections from config, so all react and reject rules are throwing errors, and any traffic, matching this rules leads to process crash with "Segmentation fault"

rules:
```
react tcp any any -> any any ( flow:to_server; msg:"test uri"; http_uri: path; content:"123"; sid:1; )
reject tcp any any -> any 80 (msg:"test2"; http_uri; content:"/test";sid:2;)
```

first startup:
```
# /opt/snort3/bin/snort -c /etc/snort3/snort.lua --create-pidfile --warn-all --plugin-path=/opt/snort3/lib/snort_extra -v -z 1 -Lalert_full -Q -Anone
...
Loading /etc/snort3/snort.lua:
        binder
        stream_tcp
        normalizer
        search_engine
        reject
        react
        ips
        latency
        http_inspect
        stream_ip
        active
        daq
        stream
        alert_full
Finished /etc/snort3/snort.lua.
Loading rules:
Loading main.conf.rules:
Loading /etc/snort3/rules/test.rules:
Finished /etc/snort3/rules/test.rules.
Finished main.conf.rules.
Finished rules.
```

right after -HUP:
```
** caught reload-config signal
.. reloading configuration
Loading /etc/snort3/snort.lua:
        binder
        stream_tcp
        normalizer
        search_engine
        ips
        latency
        http_inspect
        stream_ip
        active
        daq
        stream
Finished /etc/snort3/snort.lua.
Loading rules:
Loading main.conf.rules:
Loading /etc/snort3/rules/test.rules:
ERROR: /etc/snort3/rules/test.rules:4 unconfigured rule action 'react'
ERROR: /etc/snort3/rules/test.rules:7 unconfigured rule action 'reject'
Finished /etc/snort3/rules/test.rules.
Finished main.conf.rules.
Finished rules.
```
as you can see for some reasons it's not loading reject, react and alert_full after HUP, but this is the same config and rules.

and finally Segmentation fault in case of matching traffic.

also 
react = {  msg = true }
isn't working, it's always sending default message, but this is another story.

**Comment by snortadmin** [comment]
Thanks, we have a bug open and will prioritize this.
