### ISSUE TITLE
Snort++ 3.0.0-245 - Systemd failure due to LUA library dependency

### ISSUE THREAD

**Issue by moojit65** [snort3/snort3#49]
When trying to configure system for Snort, service does not start and exits with following error:

no file '/usr/lib64/lua/5.1/snort_config.so'
no file '/usr/local/lib/lua/5.1/loadall.so'

Snort starts and operates just fine from the command line.  Below is output from snort -V
[root@snort ~]# /usr/local/snort/bin/snort -V

   ,,_     -*> Snort++ <*-
  o"  )~   Version 3.0.0 (Build 245) from 2.9.11
   ''''    By Martin Roesch & The Snort Team
           http://snort.org/contact#team
           Copyright (C) 2014-2018 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using DAQ version 2.2.2
           Using LuaJIT version 2.0.4
           Using OpenSSL 1.0.2k-fips  26 Jan 2017
           Using libpcap version 1.5.3
           Using PCRE version 8.32 2012-11-30
           Using ZLIB version 1.2.7
           Using FlatBuffers 1.8.0
           Using Hyperscan version 4.7.0 2018-06-04
           Using LZMA version 5.2.2

**Comment by snortadmin** [comment]
Looks like you haven't exported LUA_PATH (and probably SNORT_LUA_PATH as well) in your service startup environment.  Without LUA_PATH, you will typically see the above "no file" lines as well as several others like this:

FATAL: can't init ./install/etc/snort/snort.lua: ./install/etc/snort/snort.lua:34: module 'snort_config' not found:
	no field package.preload['snort_config']
	no file './snort_config.lua'
	no file '/Users/rucombs/install/lj2/share/luajit-2.0.3/snort_config.lua'
	no file '/usr/local/share/lua/5.1/snort_config.lua'
	no file '/usr/local/share/lua/5.1/snort_config/init.lua'
	no file '/Users/rucombs/install/lj2/share/lua/5.1/snort_config.lua'
	no file '/Users/rucombs/install/lj2/share/lua/5.1/snort_config/init.lua'
	no file './snort_config.so'
	no file '/usr/local/lib/lua/5.1/snort_config.so'
	no file '/Users/rucombs/install/lj2/lib/lua/5.1/snort_config.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
Fatal Error, Quitting..

**Comment by moojit65** [comment]
Environment variable have been set in service file
[Unit]
Description = Snort 3 Service
After = network.target

[Service]
Type = simple
Restart = on-abort
User = root
Group = root
Environment = "LD_LIBRARY_PATH=/usr/lib:/usr/local/lib"
Environment = "LUA_PATH=/usr/local/snort/include/snort/lua/\?.lua\;\;"
Environment = "SNORT_LUA_PATH=/usr/local/snort/etc/snort"

ExecStart = /usr/local/snort/bin/snort -c /usr/local/snort/etc/snort/snort.lua -l /log/var/snort -k none -i em4 -D

[Install]
WantedBy = multi-user.target

**Comment by snortadmin** [comment]
If /usr/local/snort/include/snort/lua/snort_config.lua exists don't know what the issue is.  You could try posting to snort-users list where more folks will see it.

**Comment by ZAJDAN** [comment]
I am facing exactly same problem on freeBSD
enviroment variable has been set correctly:
`
root@IDS-IPS:/ # env
SHELL=/bin/csh
SSH_CLIENT=192.168.6.116 55810 22
LOGNAME=supervisor
PAGER=more
MAIL=/var/mail/supervisor
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
EDITOR=vi
ENV=/home/supervisor/.shrc
PWD=/
TERM=xterm
SSH_TTY=/dev/pts/0
HOME=/root
USER=supervisor
SSH_CONNECTION=192.168.6.116 55810 192.168.6.129 22
BLOCKSIZE=K
HOSTTYPE=FreeBSD
VENDOR=amd
OSTYPE=FreeBSD
MACHTYPE=x86_64
SHLVL=2
GROUP=wheel
HOST=IDS-IPS
REMOTEHOST=192.168.6.116
SNORT_LUA_PATH=/usr/local/snort/etc/snort
LUA_PATH=/usr/local/snort/include/snort/lua/?.lua\;\;
root@IDS-IPS:/ # 

`
