### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dreizehnutters** [snort3/snort3#56]
When I tried to build snort++ on my 16.04 Ubuntu today I encountered an issue.

me@escher:~/Workspace/snort3/build$ make -j $(nproc) install
[  0%] Building CXX object src/codecs/CMakeFiles/codecs.dir/codec_api.cc.o
[  0%] Building CXX object src/codecs/root/CMakeFiles/root_codecs.dir/cd_eth.cc.o
[  0%] Building CXX object src/connectors/tcp_connector/CMakeFiles/tcp_connector.dir/tcp_connector.cc.o
[  0%] Building CXX object src/actions/CMakeFiles/ips_actions.dir/actions.cc.o
[  0%] Building CXX object src/codecs/CMakeFiles/codecs.dir/codec_module.cc.o
[  0%] Building CXX object src/actions/CMakeFiles/ips_actions.dir/ips_actions.cc.o
[  0%] Building CXX object src/actions/CMakeFiles/ips_actions.dir/act_replace.cc.o
[  0%] Built target codecs
[  0%] Building CXX object src/connectors/tcp_connector/CMakeFiles/tcp_connector.dir/tcp_connector_module.cc.o                                                                                                            
[  0%] Building CXX object src/codecs/root/CMakeFiles/root_codecs.dir/cd_raw.cc.o
[  0%] Building CXX object src/codecs/link/CMakeFiles/link_codecs.dir/cd_arp.cc.o
[  0%] Built target root_codecs
[  0%] Building CXX object src/codecs/ip/CMakeFiles/ip_codecs.dir/cd_ipv4.cc.o
[  0%] Built target tcp_connector
[  0%] Building CXX object src/codecs/misc/CMakeFiles/misc_codecs.dir/cd_default.cc.o
[  0%] Building CXX object src/actions/CMakeFiles/ips_actions.dir/act_react.cc.o
[  1%] Building CXX object src/codecs/misc/CMakeFiles/misc_codecs.dir/cd_gtp.cc.o
[  1%] Building CXX object src/codecs/link/CMakeFiles/link_codecs.dir/cd_erspan2.cc.o
/home/me/Workspace/snort3/src/codecs/ip/cd_ipv4.cc: In member function ‘virtual bool {anonymous}::Ipv4Codec::decode(const snort::RawData&, snort::CodecData&, DecodeData&)’:
/home/me/Workspace/snort3/src/codecs/ip/cd_ipv4.cc:223:28: error: ‘DAQ_PKT_FLAG_REAL_ADDRESSES’ was not declared in this scope
     if ((raw.pkth->flags & DAQ_PKT_FLAG_REAL_ADDRESSES) and codec.ip_layer_cnt == 1)
                            ^
/home/me/Workspace/snort3/src/codecs/ip/cd_ipv4.cc:227:33: error: ‘const struct _daq_pkthdr’ has no member named ‘real_sIP’
         real_src.set(&raw.pkth->real_sIP,
                                 ^
/home/me/Workspace/snort3/src/codecs/ip/cd_ipv4.cc:228:33: error: ‘DAQ_PKT_FLAG_REAL_SIP_V6’ was not declared in this scope
             ((raw.pkth->flags & DAQ_PKT_FLAG_REAL_SIP_V6) ? AF_INET6 : AF_INET));
                                 ^
/home/me/Workspace/snort3/src/codecs/ip/cd_ipv4.cc:229:33: error: ‘const struct _daq_pkthdr’ has no member named ‘real_dIP’
         real_dst.set(&raw.pkth->real_dIP,
                                 ^
/home/me/Workspace/snort3/src/codecs/ip/cd_ipv4.cc:230:33: error: ‘DAQ_PKT_FLAG_REAL_DIP_V6’ was not declared in this scope
             ((raw.pkth->flags & DAQ_PKT_FLAG_REAL_DIP_V6) ? AF_INET6 : AF_INET));
                                 ^
src/codecs/ip/CMakeFiles/ip_codecs.dir/build.make:62: recipe for target 'src/codecs/ip/CMakeFiles/ip_codecs.dir/cd_ipv4.cc.o' failed
make[2]: *** [src/codecs/ip/CMakeFiles/ip_codecs.dir/cd_ipv4.cc.o] Error 1
CMakeFiles/Makefile2:598: recipe for target 'src/codecs/ip/CMakeFiles/ip_codecs.dir/all' failed
make[1]: *** [src/codecs/ip/CMakeFiles/ip_codecs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  1%] Building CXX object src/codecs/link/CMakeFiles/link_codecs.dir/cd_erspan3.cc.o
[  1%] Building CXX object src/codecs/link/CMakeFiles/link_codecs.dir/cd_ciscometadata.cc.o
[  1%] Building CXX object src/actions/CMakeFiles/ips_actions.dir/act_reject.cc.o
[  1%] Building CXX object src/codecs/link/CMakeFiles/link_codecs.dir/cd_fabricpath.cc.o
[  1%] Building CXX object src/codecs/misc/CMakeFiles/misc_codecs.dir/cd_icmp4_ip.cc.o
[  1%] Building CXX object src/codecs/link/CMakeFiles/link_codecs.dir/cd_mpls.cc.o
[  1%] Built target ips_actions
[  1%] Building CXX object src/codecs/link/CMakeFiles/link_codecs.dir/cd_ppp_encap.cc.o
[  2%] Building CXX object src/codecs/link/CMakeFiles/link_codecs.dir/cd_pppoe.cc.o
[  2%] Building CXX object src/codecs/link/CMakeFiles/link_codecs.dir/cd_trans_bridge.cc.o
[  2%] Building CXX object src/codecs/misc/CMakeFiles/misc_codecs.dir/cd_icmp6_ip.cc.o
[  2%] Building CXX object src/codecs/link/CMakeFiles/link_codecs.dir/cd_vlan.cc.o
[  2%] Building CXX object src/codecs/misc/CMakeFiles/misc_codecs.dir/cd_llc.cc.o
[  2%] Building CXX object src/codecs/misc/CMakeFiles/misc_codecs.dir/cd_teredo.cc.o
[  2%] Building CXX object src/codecs/misc/CMakeFiles/misc_codecs.dir/cd_user.cc.o
In file included from /home/me/Workspace/snort3/src/codecs/misc/cd_user.cc:28:0:
/home/me/Workspace/snort3/src/packet_io/sfdaq.h:68:51: error: ‘DAQ_QueryFlow_t’ has not been declared
     SO_PUBLIC int query_flow(const DAQ_PktHdr_t*, DAQ_QueryFlow_t*);
                                                   ^
/home/me/Workspace/snort3/src/codecs/misc/cd_user.cc: In member function ‘virtual bool UserCodec::decode(const snort::RawData&, snort::CodecData&, DecodeData&)’:
/home/me/Workspace/snort3/src/codecs/misc/cd_user.cc:101:5: error: ‘DAQ_QueryFlow_t’ was not declared in this scope
     DAQ_QueryFlow_t query { DAQ_USR_QUERY_PCI, 0, nullptr };
     ^
/home/me/Workspace/snort3/src/codecs/misc/cd_user.cc:103:61: error: ‘query’ was not declared in this scope
     if ( SFDAQ::get_local_instance()->query_flow(raw.pkth, &query) != DAQ_SUCCESS or
                                                             ^
/home/me/Workspace/snort3/src/codecs/misc/cd_user.cc:109:46: error: ‘query’ was not declared in this scope
     const DAQ_UsrHdr_t* pci = (DAQ_UsrHdr_t*)query.value;
                                              ^
src/codecs/misc/CMakeFiles/misc_codecs.dir/build.make:206: recipe for target 'src/codecs/misc/CMakeFiles/misc_codecs.dir/cd_user.cc.o' failed
make[2]: *** [src/codecs/misc/CMakeFiles/misc_codecs.dir/cd_user.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  2%] Built target link_codecs
CMakeFiles/Makefile2:653: recipe for target 'src/codecs/misc/CMakeFiles/misc_codecs.dir/all' failed
make[1]: *** [src/codecs/misc/CMakeFiles/misc_codecs.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

I followed the steps you provided in the README but it failed, did i do something wrong ?

**Comment by snortadmin** [comment]
Looks like you do not have daq-2.2.2 which is available on the snort.org downloads page under Snort 3.0.

**Comment by dreizehnutters** [comment]
thanks for the hint :+1: 

The build was successful now.

**Comment by snortadmin** [comment]
Cool, thanks for reporting back.
