### ISSUE TITLE
snort2lua rule converter

### ISSUE THREAD

**Issue by dreizehnutters** [snort3/snort3#57]
This is a very minor issue but i noticed that that the snort2lua tool does not convert empty lines corretly.

Example:
$my_path/bin/snort2lua -c snort3-protocol-icmp.rules -r test.rules
diff snort3-protocol-icmp.rules test.rules 
```
20d19
< 
169d167
< 

```

**Comment by mjs717** [comment]
This is not something that we plan to address at this point.
