### ISSUE TITLE
module 'snort_config' not found:

### ISSUE THREAD

**Issue by ZAJDAN** [snort3/snort3#63]
Hello,
in **/usr/local/snort/etc/snort/snort.lua** is
```
export LUA_PATH=/usr/local/snort/include/snort/lua/?.lua\;\;
export SNORT_LUA_PATH=/usr/local/snort/etc/snort/
```
I am using **csh shell** on FreeBSD
would be helpful put in the configuration file samples for a few kind of shells
so I have put the environment variable via:
```
#setenv LUA_PATH "/usr/local/snort/include/snort/lua/?.lua\;\;"
#setenv SNORT_LUA_PATH /usr/local/snort/etc/snort
#env |grep LUA
SNORT_LUA_PATH=/usr/local/snort/etc/snort
LUA_PATH=/usr/local/snort/include/snort/lua/?.lua\;\;
```
but still Snort have some problem:
```
# /usr/local/snort/bin/snort -c /usr/local/snort/etc/snort/snort.lua -i bridge0
o")~   Snort++ 3.0.0-248
--------------------------------------------------
Loading /usr/local/snort/etc/snort/snort.lua:
FATAL: can't init /usr/local/snort/etc/snort/snort.lua: /usr/local/snort/etc/snort/snort.lua:39: module 'snort_config' not found:
        no field package.preload['snort_config']
        no file '/usr/local/snort/include/snort/lua/snort_config.lua\'
        no file '\'
        no file './snort_config.so'
        no file '/usr/local/lib/lua/5.1/snort_config.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
Fatal Error, Quitting..
```

**Comment by ZAJDAN** [comment]
one thing what I tried:
```
root@IDS-IPS:/ # /usr/local/snort/bin/snort -c /usr/local/snort/include/snort/lua/snort_config.lua  -i bridge0
--------------------------------------------------
o")~   Snort++ 3.0.0-248
--------------------------------------------------
Loading /usr/local/snort/include/snort/lua/snort_config.lua:
Finished /usr/local/snort/include/snort/lua/snort_config.lua.
--------------------------------------------------
pcap DAQ configured to passive.
Commencing packet processing
++ [0] bridge0
```
without error :_)
will be nice with which *.lua I should start the Snort
**# /usr/local/snort/bin/snort -c /usr/local/snort/etc/snort/snort.lua**
or
**# /usr/local/snort/bin/snort -c /usr/local/snort/include/snort/lua/snort_config.lua**

**Comment by Xiche** [comment]
LUA_PATH and SNORT_LUA_PATH are environment variables, not something to be put into snort.lua.

**Comment by Xiche** [comment]
Make sure the backslashes don't end up in the environment variable.  They were given in the example to escape special characters in bash.  The actual environment variables should look like this:
```
#env |grep LUA
SNORT_LUA_PATH=/usr/local/snort/etc/snort
LUA_PATH=/usr/local/snort/include/snort/lua/?.lua;;
```

**Comment by Xiche** [comment]
> 
> With which *.lua I should start the Snort?
> 
> **# /usr/local/snort/bin/snort -c /usr/local/snort/etc/snort/snort.lua**
> _is it same as # /usr/local/snort/bin/snort ?_
> or
> **# /usr/local/snort/bin/snort -c /usr/local/snort/include/snort/lua/snort_config.lua**

snort.lua

**Comment by ZAJDAN** [comment]
Xiche:
The problem was with the escaping marks in environment variable as You wrote.
I changed to:
**#setenv LUA_PATH "/usr/local/snort/include/snort/lua/?.lua;;"
#env |grep LUA
SNORT_LUA_PATH=/usr/local/snort/etc/snort
LUA_PATH=/usr/local/snort/include/snort/lua/?.lua;;**
and Snort works without error :_)
Thank You
