### ISSUE TITLE
Daemon mode doesn't create pidfile

### ISSUE THREAD

**Issue by ZAJDAN** [snort3/snort3#68]
Seems to be, that Snort3 has hard-defined path and name of the pidfile.

1) when I launch Snort with switch '**-D**' (daemon):
#/usr/local/snort/bin/snort -D -i bridge0 -c /usr/local/snort/etc/snort/snort.lua
the pid file is not created / I can not find the file

2) when I launch with switch '**--create-pidfile**'
#/usr/local/snort/bin/snort --create-pidfile -i bridge0 -c /usr/local/snort/etc/snort/snort.lua
returns:
Writing PID "4133" to file "./snort.pid"

Why daemon doesn't create pidfile?
How can I define name of the pidfile and also path to the file?

_Snort3 compiled from GIT on FreeBSD 11.2_

**Comment by snortadmin** [comment]
Hi Zajdan,

Snort 3 does not hard code any paths.  The path of the pid file is set with the -l option and defaults to the working directory.  Daemon mode and pid file creation are frequently used together but not always so they are two different options.

You can not set the name of the pid file, consistent with all other Snort 3 output files.  Log files in particular are per packet thread and must be named uniquely so Snort assumes that responsibility based on a number of options.  Although not specifically applicable here, we opted for consistency.

Do you have a need to use a name other than snort.pid?

Russ

**Comment by ZAJDAN** [comment]
Hi...
I have read that the option pid-path has been deleted
_* deleted --pid-path and --no-interface-pidfile_
so I was confused how to define the path.
The name of the pidfile with Snort2 could be defined:
_-R name  Use name as a suffix to the snort pidfile._
It is not necessary set the name of pidfile, but I can image situation where it will be helpful.
For example rc script from Snort2 use syntax to create/amend the pidfile:
```
....
[ -n "$snort_interface" ] && snort_flags="$snort_flags -i $snort_interface" \
                                  && pidfile="/var/run/snort_${snort_interface}.pid"
...
```
thank You for answer
Regards ZAJDAN

**Comment by snortadmin** [comment]
Thanks.  ${snort_interface} could be put in the path (via -l).

**Comment by finchy** [comment]
That's Snort 2 documentation.

**Comment by ZAJDAN** [comment]
> That's Snort 2 documentation.

anyway same it is written in manual for Snort3
**stringsnort.-l: <logdir> log to this directory instead of current directory**

**Comment by snortadmin** [comment]
Yes, there is one option to set the "log" directory.  The pid file is where the pid is "logged".  :)

We can update that documentation to make it clear that applies to the pid file.  Thanks for pointing that out.
