### ISSUE TITLE
Time change

### ISSUE THREAD

**Issue by ZAJDAN** [snort3/snort3#69]
Hello,
at this Sunday was time change at Europe(winter time). Overturned 1 hour back.
Now I am watching log and Snort still use old time:
`# date`
Mon Oct 29 **08:27:04** CET 2018
in same moment:
10/29-**09:26:51**.356881 [**] [112:1:1] "(arp_spoof) unicast ARP request" [**] [Priority: 3] {ARP}  -

is somehow possible set Snort so that the time will be synchronized with system time?

**Comment by Xiche** [comment]
Snort packet threads primarily operate on packet time (especially events), so if the timestamps on the incoming packets hadn't updated for the time change, it would still use the old time for reporting.  I'd be surprised if the problem didn't end up correcting itself.  Most Linux systems will use AF_PACKET behind the scenes, for example, which gets its timestamps from the kernel packet buffer entries it receives.  Not sure there's much else we can do about it.
