### ISSUE TITLE
Unable to find libsfbpf.so.0 if libdaq is not in the default path

### ISSUE THREAD

**Issue by chenchix** [snort3/snort3#76]
Configure parameters:

../configure_cmake.sh --with-hyperscan-libraries=/root/project/gerrit/hyperscan/ --with-hyperscan-includes=/root/project/gerrit/hyperscan/src --prefix=/root/project/snort_srcs/staging/ --with-daq-includes=/root/project/snort_srcs/staging/include --with-daq-libraries=/root/project/snort_srcs/staging/lib/

~ ls libsfbpf*
/root/project/snort_srcs/staging/lib/libsfbpf.a
/root/project/snort_srcs/staging/lib/libsfbpf.so.0
/root/project/snort_srcs/staging/lib/libsfbpf.so
/root/project/snort_srcs/staging/lib/libsfbpf.so.0.0.1
/root/project/snort_srcs/staging/lib/libsfbpf.la

[ 97%] Documents: building commands.txt with 
cd /root/project/snort_srcs/snort3/objdir/build/doc && ../../../doc/scripts/generate_help.sh /root/project/snort_srcs/snort3/objdir/build/src/snort commands.txt
/root/project/snort_srcs/snort3/objdir/build/src/snort: error while loading shared libraries: libsfbpf.so.0: cannot open shared object file: No such file or directory
doc/CMakeFiles/all_built_sources.dir/build.make:80: recipe for target 'doc/commands.txt' failed
make[2]: *** [doc/commands.txt] Error 127
make[2]: *** Deleting file 'doc/commands.txt'
make[2]: Leaving directory '/root/project/snort_srcs/snort3/objdir/build'
CMakeFiles/Makefile2:6000: recipe for target 'doc/CMakeFiles/all_built_sources.dir/all' failed
make[1]: *** [doc/CMakeFiles/all_built_sources.dir/all] Error 2
make[1]: Leaving directory '/root/project/snort_srcs/snort3/objdir/build'
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Xiche** [comment]
You need to have any shared libraries in non-standard paths in the runtime library path (LD_LIBRARY_PATH) to run Snort.  Snort will, by default, attempt to generate its internal module documentation at build time, which required running the Snort binary.

**Comment by ewh1901** [comment]
What are the steps to do this fix?

**Comment by a1139056159** [comment]
Try 
sudo /sbin/ldconfig -v
if you're using ubuntu.
