### ISSUE TITLE
errors when starting snort3 (fresh today's git) with nfq and -z (to increase number of packet processing threads)

### ISSUE THREAD

**Issue by paolss** [snort3/snort3#77]
Command to start snort:

/opt/snort/bin/snort -c /opt/snort/etc/snort/snort.lua -R /opt/snort/rules/snort3-community.rules -l /var/itcsoc/snort --daq nfq --daq-dir /usr/local/lib64/daq -A alert_fast --plugin-path /opt/snort/extra -Q -z 4

and error:
nfq DAQ configured to inline.
Commencing packet processing
++ [0] 
++ [1] 
++ [2] 
++ [3] 
Can't initialize DAQ nfq (-1) - nfq_daq_initialize: nf queue creation failed

Can't initialize DAQ nfq (-1) - nfq_daq_initialize: nf queue creation failed

-- [1] 
-- [2] 
Can't initialize DAQ nfq (-1) - nfq_daq_initialize: nf queue creation failed

-- [3] 

------------------------
/opt/snort/bin/snort --daq-list    
Available DAQ modules:
pcap(v4): readback live multi unpriv
nfq(v7): live inline multi
ipfw(v3): live inline multi unpriv
dump(v4): readback live inline multi unpriv
afpacket(v6): live inline multi unpriv

**Comment by InverseRE** [comment]
Looks like, running with NFQ requires higher privileges. 
Please, feel free to reopen the issue if this doesn't help.
