### ISSUE TITLE
Snort Crashes

### ISSUE THREAD

**Issue by kdrypr** [snort3/snort3#78]
Hi,

Snort crashed after 9 minutes later. Very frequent crashes occur in traffic of 1 gbit and above

**Comment by snortadmin** [comment]
Hi - can you give us a little more to go on?  It would help if we could get a backtrace from the debugger.  Even better, do configure_cmake.sh --enable-address-sanitizer and send us the error output.  Thanks.

**Comment by kdrypr** [comment]
We have 3Gbit network mirror traffic. Snort crashed with no output after 8 minutes later.

on the other hand, our local office have least traffice and snort didnt crash.

**Comment by snortadmin** [comment]
Thanks.  Are you using the default snort.lua or do you have a custom config?  If the latter, can you share it with us?

**Comment by kdrypr** [comment]
We use custom lua file. can you share your email address with me because we use it for our customer?

**Comment by snortadmin** [comment]
rucombs@cisco.com thx.
