### ISSUE TITLE
Snort rule match fails when setting detection cursor

### ISSUE THREAD

**Issue by smlx** [snort3/snort3#79]
I have two rules, the only difference between them being that I set the detection cursor to `http_uri` in rule b:

    alert tcp any any -> any 8080 ( msg:"test rule a"; flow:to_server,established; content:"attack",fast_pattern,nocase; sid:10000001; rev:1; )
    alert tcp any any -> any 8080 ( msg:"test rule b"; flow:to_server,established; http_uri; content:"attack",fast_pattern,nocase; sid:10000002; rev:1; )

I expect both rules to match a request like this:

    curl http://192.168.1.134:8080/attack

However, I only get a single alert (alert_fast format):

    04/12-05:56:46.760940 [**] [1:10000001:1] "test rule a" [**] [Priority: 0] {TCP} 192.168.1.192:37664 -> 192.168.1.134:8080

Is this a bug, is my rule syntax broken, or is there something else going on here?

I am using 3.0.0-252, but the same thing happens with 3.0.0-251. Both built like this:

```
-------------------------------------------------------
snort version 3.0.0

Install options:
    prefix:     /usr/local
    includes:   /usr/local/include/snort
    plugins:    /usr/local/lib64/snort

Compiler options:
    CC:             /usr/bin/cc
    CXX:            /usr/bin/c++
    CFLAGS:            -fvisibility=hidden   -DNDEBUG -g -ggdb   
    CXXFLAGS:          -fvisibility=hidden   -DNDEBUG -g -ggdb   
    EXE_LDFLAGS:        
    MODULE_LDFLAGS:     

Feature options:
    Flatbuffers:    ON
    Hyperscan:      ON
    ICONV:          ON
    LZMA:           ON
    RPC DB:         TIRPC
    SafeC:          ON
    TCMalloc:       OFF
    UUID:           ON
-------------------------------------------------------
```

**Comment by snortadmin** [comment]
I'm getting 10000002 for my reproduction of your case with the default snort.lua.  Is your config the same?  If you send a pcap and conf (rucombs@cisco.com) I will test with that.

Thanks
Russ

**Comment by smlx** [comment]
Hi Russ,
I've pushed a Docker environment that you can use to reproduce the issue, including a .pcap.

https://github.com/smlx/snort3-testcase

Thanks

**Comment by snortadmin** [comment]
Thanks we'll take a look.

**Comment by btholpady** [comment]
Hello,

This rule is not broken. This alert will fire in inline mode. Please run your pcap against these rule in inline mode and you will see an alert.

Thank you!

**Comment by smlx** [comment]
@btholpady 
Could you point to some documentation for this limitation?
Many (most?) of the Talos rules uses similar constructs, so does that mean those rules are useless except in inline mode?

**Comment by btholpady** [comment]
@smlx 

Actually the issue isn't with the rule. The HTTP request you are trying to match on is not acknowledged by the server. Hence no rebuilt packets are generated in passive mode. In inline mode  packets are rebuilt regardless of the ACKs. The http IPS options only work on rebuilt packets in Snort3. So by switching to inline mode you will see the alerts.

Let me know if you have more questions.

**Comment by smlx** [comment]
@btholpady 
Thanks, a response to the request seems to trigger the rule when using `--daq afpacket`. So my main problem is solved.

But, just for my own understanding, I can't figure out if there's a way to run in inline mode against a pcap. Is that possible?

**Comment by btholpady** [comment]
@smlx : Thank you for the update. That is correct. As long as the packets are ACK'ed in passive mode, http_uri will work.

Can you please send me the pcap for the issue mentioned above?

Thanks!

**Comment by InverseRE** [comment]
You could use a mechanism whioh doesn't require ACK on wire:
`bool stream_tcp.no_ack = false: received data is implicitly acked immediately`

For example, by adding the following command line option to start Snort:
`--lua "stream_tcp.no_ack=true"`
