### ISSUE TITLE
How to upload alert log

### ISSUE THREAD

**Issue by EggUncle** [snort3/snort3#81]

**Comment by EggUncle** [comment]
in snort2, use config about ' output alert_syslog: host=xxx.xxx.xxx.xxx:xxx,LOG_AUTH LOG_ALERT ' to send log to remote server,but how to send log in snort3. I try  to use snort2lua to conver snort.conf of snort2,but in my new snort.lua,there is 
'''
 --BINDINGS REQUIRED!! hostname --> --> host=(my remote ip and port),LOG_AUTH
'''

**Comment by snortadmin** [comment]
syslog host config was Snort 2 Windows only.  Did you switch from Windows to Linux?  Can you share your config that causes that error?

**Comment by EggUncle** [comment]
I use it in Linux, now I use 'alert_unixsock' send alert log.Thanks for your reply  :  )
