### ISSUE TITLE
snort_default.lua and snort.lua files working differently

### ISSUE THREAD

**Issue by berkbykn** [snort3/snort3#82]
Hello, when i use snort_default.lua for tcp alerts it works fine. But when i use snort_deafult.lua it doesn't give me any log outputs.. And when i use snort.lua file for snorting, rules that i created do not works. Only icmp alert works and then i can see logs output. Can you help me with configuration please? I want to see tcp traffic alerts and logs output.
When i use the command below, tcp rules and alerts do not work.
"snort -c /usr/local/etc/snort/snort.lua -R /usr/local/etc/snort/rules/local.rules \-i eth0 -A full -s 65535 -k none -l /var/log/snort"

**Comment by InverseRE** [comment]
**snort_default.lua** is not a complete config, it just provides some useful definitions (defaults values).
**snort.lua** is a config, but it can be tuned further for better efficacy/performance.

Please note that github is for issues in the code.
As  for the use cases, you could ask at snort-users@lists.snort.org
