### ISSUE TITLE
A question of keyword ‘sameip’.

### ISSUE THREAD

**Issue by EggUncle** [snort3/snort3#83]
Hi:
    In snort2 , we can use keyword ‘sameip’ to detect src ip and dst ip same , but in snort3 , the 'sameip' rule option keyword is no longer supported. There are other keywords can instand of keyword ' sameip ' in snort 3 ?

Thanks.

**Comment by EggUncle** [comment]
I find it in file 'builtins.rules' :

alert ( msg:"DECODE_BAD_TRAFFIC_SAME_SRCDST"; sid:151; gid:116; rev:1; metadata:rule-type decode; reference:cve,1999-0016; reference:cve,2005-0688; reference:bugtraq,2666; reference:url,www.microsoft.com/technet/security/bulletin/ms05-019.mspx; classtype:bad-unknown; )

it can work.

emmmm... maybe you can add a tips to snort2lua when user try to conver snort2 rules to snort3 rules.
When I use snort2lua to conver snort2 rules with keyword 'sameip' , I just get message "# The 'sameip' rule option keyword is no longer supported" , it make me be at a loss.

Thanks.

**Comment by snortadmin** [comment]
Thanks, we will provide a more helpful message.  Glad you figured it out.

Russ
