### ISSUE TITLE
How to compare two type packet count in some time In snort3 ？

### ISSUE THREAD

**Issue by EggUncle** [snort3/snort3#84]
Hi:
    Can I use snort3 to compare two type packet count in some time?
    For example, if I need to send alert when TCP-SYN packet count more than TCP-ACK packet in 10 sec, how to write my rule or config file? 
    In fact , I want to use this function to detect NMAP TCP scan , I read doc & rules of snort3, but NMAP TCP SCAN rules has been ' delete ' type. So I try  to make it by myself, because nmap tcp scan will send many different SYN packet to different port , so many port, but just a little port can reply ACK packet , so I want to compare SYN packet count with ACK packet to detect NMAP TCP SCAN.
     Maybe snort3 can't support this function at now, but can you give me some tips about how to develop this function?  I used to read snort code and complete some custom function,and I will try to do it.

Thanks.

**Comment by EggUncle** [comment]
Peg count can record packet num and show it after stop snort . Can  it used in rule?

**Comment by snortadmin** [comment]
snort3_extra has a pkt_num rule option that matches a number or interval.
