### ISSUE TITLE
in which file rules is defined not getting alert message

### ISSUE THREAD

**Issue by vija9751** [snort3/snort3#86]
i want to know where i have to chane the rule
ex: alert tcp any any -> $HOME_NET 9389 (msg:"SS POLICY Active Directory Web Services"; flow:to_server,established; flags:PA; content:"/ActiveDirectoryWebServices/Windows/Enumeration"; classtype:attempted-recon; sid:1000001;) where i have to write exactly

alert tcp any any -> any any (msg:"Feature1"; content:"#JN1"; nocase;

how to get this

05/-22:56:55.056993 [] [1:2019:0] Feature1 [] [Priority: 0] {TCP}
46.20.153.125:80 -> 10.0.2.15:56216

how to get message of Feature1

**Comment by vija9751** [comment]
i have seen all snort.conf file changes the rule on every file but i couldn't find where in which rule i have to write or change the rule

**Comment by kdrypr** [comment]
you can create a new rule file in rules directory and write new rule in this file. After that restart snort.
as root:
touch /usr/local/etc/snort/rules/local.rules
nano /usr/local/etc/snort/rules/local.rules

copy line below;

alert tcp any any -> any any ( msg:"Feature1"; content:"#JN"", nocase; sid:3000001; )

start snort with local.rules file.

**Comment by InverseRE** [comment]
> start snort with local.rules file.

`snort -R local.rules`
