### ISSUE TITLE
Getting an error when trying to make Snort 3. Any idea what i'm doing wrong? 

### ISSUE THREAD

**Issue by asotogil** [snort3/snort3#89]
~/snort_src/snort3/build$ make 
[  0%] Built target tcp_connector
[  0%] Building CXX object src/actions/CMakeFiles/ips_actions.dir/actions.cc.o
In file included from /home/asotogil/snort_src/snort3/src/protocols/packet_manager.h:31:0,
                 from /home/asotogil/snort_src/snort3/src/packet_io/active.h:28,
                 from /home/asotogil/snort_src/snort3/src/actions/actions.cc:27:
/home/asotogil/snort_src/snort3/src/protocols/packet.h:143:5: error: ‘DAQ_Msg_h’ does not name a type; did you mean ‘DAQ_Mode’?
     DAQ_Msg_h daq_msg;              // DAQ message this packet came from
     ^~~~~~~~~
     DAQ_Mode
In file included from /home/asotogil/snort_src/snort3/src/actions/actions.cc:27:0:
/home/asotogil/snort_src/snort3/src/packet_io/active.h:136:25: error: ‘DAQ_Msg_h’ has not been declared
     static int send_eth(DAQ_Msg_h, int, const uint8_t* buf, uint32_t len);
                         ^~~~~~~~~
/home/asotogil/snort_src/snort3/src/packet_io/active.h:137:24: error: ‘DAQ_Msg_h’ has not been declared
     static int send_ip(DAQ_Msg_h, int, const uint8_t* buf, uint32_t len);
                        ^~~~~~~~~
src/actions/CMakeFiles/ips_actions.dir/build.make:62: recipe for target 'src/actions/CMakeFiles/ips_actions.dir/actions.cc.o' failed
make[2]: *** [src/actions/CMakeFiles/ips_actions.dir/actions.cc.o] Error 1
CMakeFiles/Makefile2:368: recipe for target 'src/actions/CMakeFiles/ips_actions.dir/all' failed
make[1]: *** [src/actions/CMakeFiles/ips_actions.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Xiche** [comment]
You need the latest version of libdaq from the master branch in https://github.com/snort3/libdaq.

**Comment by asotogil** [comment]
Awesome, thank you, that worked.

**Comment by idanc15** [comment]
I installed libdaq and I still get this error message. What can be the reason?

**Comment by skunniyur** [comment]
Hi,
I have cloned the github master folder, but the issue still persists during my make. What exactly was done for the issue?

**Comment by rdpmc** [comment]
./configure_cmake.sh --with-daq-includes=PATH_TO_WHERE_daq.h_EXISTS

чт, 10 окт. 2019 г. в 14:09, skunniyur <notifications@github.com>:
