### ISSUE TITLE
Getting this error when testing snort with default configuration file

### ISSUE THREAD

**Issue by asotogil** [snort3/snort3#90]
asotogil@asotogil-VirtualBox:~$ snort -c /usr/local/etc/snort/snort.lua
Running in IDS mode

        --== Initializing Snort ==--
Initializing Output Plugins!
Initializing Preprocessors!
Initializing Plug-ins!
Parsing Rules file "/usr/local/etc/snort/snort.lua"
ERROR: /usr/local/etc/snort/snort.lua(0) Unable to open rules file "/usr/local/etc/snort/snort.lua": No such file or directory.

Fatal Error, Quitting..

**Comment by Xiche** [comment]
Please send questions such as this and your previous one that you've opened as issues to the Snort Users mailing list instead (see: https://snort.org/community#mailing_lists).  In this case, it appears that you're trying to use a Snort 2.x binary with a Snort 3 configuration file.

**Comment by asotogil** [comment]
Thank you, Sorry about that.
