### ISSUE TITLE
Getting an error when trying to make Snort3 cannot find “libdaq.so.3”. Installed latest libdaq it is located in standard location but created file called ‘libdaq.so.4'

### ISSUE THREAD

**Issue by Gianna918** [snort3/snort3#92]
Getting an error when trying to make Snort3. cannot find “libdaq.so.3”. Installed latest libdaq it is located in standard location but created file called ‘libdaq.so.4’

System is running Ubuntu 18.04.2 LTS

Error message:
[ 98%] Documents: building commands.txt with
/home/devsnort/snort_src/snort3/build/src/snort: error while loading shared libraries: libdaq.so.3: cannot open shared object file: No such file or directory
doc/CMakeFiles/all_built_sources.dir/build.make:79: recipe for target 'doc/commands.txt' failed
make[2]: *** [doc/commands.txt] Error 127
make[2]: *** Deleting file 'doc/commands.txt'
CMakeFiles/Makefile2:6083: recipe for target 'doc/CMakeFiles/all_built_sources.dir/all' failed
make[1]: *** [doc/CMakeFiles/all_built_sources.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

Locating libdaq files:
locate libdaq.so
/home/devsnort/snort_src/daq-2.2.2/api/.libs/libdaq.so
/home/devsnort/snort_src/daq-2.2.2/api/.libs/libdaq.so.4
/home/devsnort/snort_src/daq-2.2.2/api/.libs/libdaq.so.4.0.2
/usr/local/lib/libdaq.so
/usr/local/lib/libdaq.so.4
/usr/local/lib/libdaq.so.4.0.2

**Comment by Xiche** [comment]
The latest from the master branch (DAQ 3.0.0) will have a .3 soname.  You need to remove the LibDAQ 2.2.2 libraries and headers.

**Comment by GregorioSecurity** [comment]
@Xiche Can you send an article or something on how to do that? I couldn't seem to find out how to do it.

**Comment by FabrizioFubelli** [comment]
@Gianna918 
 ### This works for me:
`ln -s /usr/local/lib/libdaq.so.3 /lib/`

**Comment by MohammadAlavi1986** [comment]
```
git clone https://github.com/snort3/libdaq.git
cd libdaq
./bootstrap
./configure
make
sudo make install

ln -s /usr/local/lib/libdaq.so.3 /lib/
```
