### ISSUE TITLE
Suppress Between 2 IP Addresses

### ISSUE THREAD

**Issue by kdrypr** [snort3/snort3#95]
Can you add function of to suppress between two IP address with single or multiple sid?

**Comment by snortadmin** [comment]
It's in our backlog but not high priority.  Are you trying to suppress builtin rules or other rules (text and SO)?

**Comment by kdrypr** [comment]
I'm trying to suppress builtin rules. In the feature we will suppress other rules. for ex: I have a traffic sid=635 between 2 IP addresses but i want to suppress because this traffic is valid for us.

**Comment by InverseRE** [comment]
You could have a dedicated IPS policy, where rule states are different.

snort.lua:
```
binder = { { when = { nets = '192.168.1.1' }, use = { ips_policy = 'allow.lua'} } }
ips = { enable_builtin_rules = true, include = 'rule.rules' }
```

allow.lua
```
 -- suppresses rule 635:536, while other rules are inherited from the base policy
ips = { states = [[ alert (gid:635; sid:536; enable:'no') ]] }
```
