### ISSUE TITLE
error installing snort on ubuntu 16.04 server

### ISSUE THREAD

**Issue by judoal** [snort3/snort3#97]
running the following commands:
`git clone git://github.com/snortadmin/snort3.git
cd snort3
./configure_cmake.sh --prefix=/opt/snort
cd build
make
sudo make install`

Error produced:

make
Scanning dependencies of target tcp_connector
[  0%] Building CXX object src/connectors/tcp_connector/CMakeFiles/tcp_connector.dir/tcp_connector.cc.o
[  0%] Building CXX object src/connectors/tcp_connector/CMakeFiles/tcp_connector.dir/tcp_connector_module.cc.o
[  0%] Built target tcp_connector
Scanning dependencies of target ips_actions
[  0%] Building CXX object src/actions/CMakeFiles/ips_actions.dir/actions.cc.o
In file included from /home/judoal/snort_src/snort3-3.0.0-257/src/protocols/packet_manager.h:31:0,
                 from /home/judoal/snort_src/snort3-3.0.0-257/src/packet_io/active.h:28,
                 from /home/judoal/snort_src/snort3-3.0.0-257/src/actions/actions.cc:27:
/home/judoal/snort_src/snort3-3.0.0-257/src/protocols/packet.h:143:5: error: ‘DAQ_Msg_h’ does not name a type
     DAQ_Msg_h daq_msg;              // DAQ message this packet came from
     ^
In file included from /home/judoal/snort_src/snort3-3.0.0-257/src/actions/actions.cc:27:0:
/home/judoal/snort_src/snort3-3.0.0-257/src/packet_io/active.h:136:25: error: ‘DAQ_Msg_h’ has not been declared
     static int send_eth(DAQ_Msg_h, int, const uint8_t* buf, uint32_t len);
                         ^
/home/judoal/snort_src/snort3-3.0.0-257/src/packet_io/active.h:137:24: error: ‘DAQ_Msg_h’ has not been declared
     static int send_ip(DAQ_Msg_h, int, const uint8_t* buf, uint32_t len);
                        ^
src/actions/CMakeFiles/ips_actions.dir/build.make:62: recipe for target 'src/actions/CMakeFiles/ips_actions.dir/actions.cc.o' failed
make[2]: *** [src/actions/CMakeFiles/ips_actions.dir/actions.cc.o] Error 1
CMakeFiles/Makefile2:368: recipe for target 'src/actions/CMakeFiles/ips_actions.dir/all' failed
make[1]: *** [src/actions/CMakeFiles/ips_actions.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

I don't know if this is a problem with DAQ or the snort build.

**Comment by judoal** [comment]
building with an earlier version (build 247) works.   The info is: 


   ,,_     -*> Snort++ <*-
  o"  )~   Version 3.0.0 (Build 247) from 2.9.11
   ''''    By Martin Roesch & The Snort Team
           http://snort.org/contact#team
           Copyright (C) 2014-2018 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using DAQ version 2.2.2
           Using LuaJIT version 2.0.4
           Using OpenSSL 1.0.2g  1 Mar 2016
           Using libpcap version 1.7.4
           Using PCRE version 8.38 2015-11-23
           Using ZLIB version 1.2.8
           Using FlatBuffers 1.11.0
           Using Hyperscan version 4.6.0 2019-07-28
           Using LZMA version 5.1.0alpha

**Comment by snortadmin** [comment]
Make sure that you build and install the latest DAQ (DAQ 3) for the latest builds.
