### ISSUE TITLE
safec not being detected by Snort3 b258

### ISSUE THREAD

**Issue by NDietrich** [snort3/snort3#98]
Snort is not detecting the latest safec from github

Download and install the latest release (same issue if I git clone the head) of Safec:
```
wget https://github.com/rurban/safeclib/releases/download/v04062019/libsafec-04062019.0-ga99a05.tar.gz
tar -xzvf libsafec-04062019.0-ga99a05.tar.gz 
cd libsafec-04062019.0-ga99a05/
./configure
make
sudo make install
```

Verify that snort should be able to see safec (the .pc file is in the right place): 
```
noah@snort3:~/snort_src/snort3$ echo $PKG_CONFIG_PATH
/usr/local/lib/pkgconfig/

noah@snort3:~/snort_src/snort3$ tree /usr/local/lib/pkgconfig/
/usr/local/lib/pkgconfig/
├── libhs.pc
├── libpcrecpp.pc
├── libpcre.pc
├── libpcreposix.pc
├── libprofiler.pc
├── libsafec.pc         <<<<<<<<<<<<<<<<<<<
├── libtcmalloc_debug.pc
├── libtcmalloc_minimal_debug.pc
├── libtcmalloc_minimal.pc
├── libtcmalloc.pc
```
install libdaq 3.0 from github, tthen snort3 head from github:
```
./configure_cmake.sh --prefix=/usr/local --enable-tcmalloc
```
and you see that safec isn't found (but all the other installed tools are found):
```
Feature options:
    DAQ Modules:    Static (afpacket;bpf;dump;fst;pcap;trace)
    Flatbuffers:    ON
    Hyperscan:      ON
    ICONV:          ON
    LZMA:           ON
    RPC DB:         Built-in
    SafeC:          OFF    <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    TCMalloc:       ON
    UUID:           ON
-------------------------------------------------------
```

**Comment by Xiche** [comment]
Reini finally merged my pull request into LibSafeC to have sanely unversioned files a year after I put it up and, unfortunately, after I'd already hacked up our own code to work with his previous (versioned) pkgconfig/header files.  I need to go back and clean it up now that libsafec is operating properly; thanks for the reminder.

**Comment by NDietrich** [comment]
Thank you. if you wouldn't mind letting me know when this is fixed, i'll test it on my system (updating this issue will notify me).
thanks
noah

**Comment by Xiche** [comment]
Thanks for the offer - I'm actually away right now, so I'll likely get to it toward the end of next week.

**Comment by NDietrich** [comment]
I've verified that this is now fixed. Thanks!
